### ISSUE TITLE
Failed to save options

### ISSUE THREAD

**Issue by manaten** [mintty/wsltty#1]
I tried to save options, but mintty failed with these messages.

![2016-09-12 02 48 52](https://cloud.githubusercontent.com/assets/586064/18419420/29e6708e-7895-11e6-891a-83aed1ff1b53.png)

When I create `%LOCALAPPDATA%\wsltty\home\username` , mintty succeed to save options.
I think it is better to create this directory at the time of install.

**Comment by mintty** [comment]
As a workaround, you can create %APPDATA%/mintty/config which mintty will save to.
As a side-effect, this configuration is shared among various mintty installations on your system.

**Comment by manaten** [comment]
I saw above commit.  I think `%LOCALAPPDATA%\wsltty\home\%USERNAME%` is correct instead of `%LOCALAPPDATA%\wsltty\%USERNAME%`.

**Comment by mintty** [comment]
Released 0.5.
