### ISSUE TITLE
Need help with title bar in full-screen mode on Insider editions of Win10

### ISSUE THREAD

**Issue by klauern** [mintty/wsltty#100]
I'm not sure if this is a bug on my side of the version of Windows I'm running, or if this is going to be a new "default" setup for windows, but for whatever reason, there's a weird title bar that I cannot remove when I try to "full screen" WSL with `Alt+Enter`:

![Image of title bar in full screen mode](https://i.imgur.com/nGTYqUe.png)

Here's a bigger closeup:

![image](https://user-images.githubusercontent.com/4735/39680506-f91d9ae8-5166-11e8-8f81-57da9071effe.png)

When you click on the upper-left, you get this:

![image](https://user-images.githubusercontent.com/4735/39680509-0645eb4e-5167-11e8-94a8-082200ab7e69.png)

Anyways, I'm not sure if this is a new "feature" of Windows 10, or a bug, but I thought it worth bringing to your attention in case you're not running bleeding edge versions of Windows and don't want to be caught off guard.

![image](https://user-images.githubusercontent.com/4735/39680523-329dc248-5167-11e8-97df-54e25173f969.png)

```
C:\Users\klauer
λ  [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17661  0
```

**Comment by mintty** [comment]
That doesn't look like the normal title bar, which would have the mintty icon in the upper left corner.
Maybe you have some special window manager configuration?

**Comment by klauern** [comment]
That's how a lot of my title bars look.  The Settings app, Hyper-V Manager, and a lot of the Electron-based desktop apps also have this "look" to them.  That's why I wasn't sure if it was a new default setting that other apps had work around.

There are apps that don't have that bar, like Google Chrome, Firefox, etc., but I am assuming that their dev teams are so massive they already accounted for the change.

**Comment by klauern** [comment]
Well, it could be a bug if I wanted it to be fullscreen without that bar.  As it stands, I cannot get to full screen with this console feature.  Thus, I would argue it is a bug.

**Comment by Biswa96** [comment]
The go to this repository https://github.com/Microsoft/console find any issue that matches your question.

**Comment by Biswa96** [comment]
The go to this repository https://github.com/Microsoft/console find any issue that matches your question. Or ask your problem in Insider feedback app.

**Comment by Biswa96** [comment]
The go to this repository https://github.com/Microsoft/console find any issue that matches your question. Or ask your problem in Insider feedback app. 
Also from the screenshot I think you're using cmder. Checkout their repository also.

**Comment by AsharLohmar** [comment]
I recall reading something about windows adding tabbed view capability to all apps, being on and Insider release that might be the case. There's some advertisement [here](https://www.theverge.com/2017/11/28/16709190/microsoft-windows-10-tabs-file-explorer-sets-feature) and some tech talk [here](https://www.tenforums.com/tutorials/102362-turn-off-tabs-apps-sets-windows-10-a.html) hints on how to turn on the "feature" maybe it will help to turn it off also, or at least get some insight on how it works.
On the "official"/"public" 1803 I don't have the problem
![image](https://user-images.githubusercontent.com/4039805/39782408-60a042c2-5312-11e8-9f0a-cb68ccf73952.png)

**Comment by mintty** [comment]
You may want to check Microsoft/console#49 and perhaps add a request about flexible full-screen behaviour; it would be good to have API control about the Tab bar.

**Comment by Biswa96** [comment]
The tab console feature may depend on  Desktop Windows Manager (DWM). When I disable DWM the tabs are all gone.

**Comment by mintty** [comment]
OK, but the idea is it should be switchable per window, and even dynamically, i.e. only when in fullscreen mode. This is something that we should request as long as the Windows feature is under evaluation (once released, you can't expect a response from them anymore...)

**Comment by mintty** [comment]
Closing this in favour of more targetted issue #102.
