### ISSUE TITLE
Sessions grouping with new Sets feature in Windows

### ISSUE THREAD

**Issue by dannyk81** [mintty/wsltty#102]
Hey!

First of, thanks for this great tool!

Quick question about the new [Sets](https://insider.windows.com/en-us/articles/introducing-sets/) feature in latest Windows Insider builds.

Any thought on how this can be used to "group" this sessions so that they can be tabbed?

**Comment by mintty** [comment]
I'll check that out when I have the feature.
As I understand it, tabbing will work automatically, right?

**Comment by dannyk81** [comment]
Well, from the description I've read, indeed it should capture and group windows of the same application and tab them, however - not happening in case of wsltty.

Can't say if it's something missing in Windows or something that needs to done on the application level to support it.

**Comment by ksze** [comment]
@dannyk81 I wonder if this has to do with #96.

**Comment by dannyk81** [comment]
That's a good point, but I do have `-o AppID=wsltty` in the shortcut and all the sessions are grouped together on the taskbar under a single icon, so not sure if this is the issue.

**Comment by mintty** [comment]
As the Virtual Tabs feature in mintty has been closed after further improvement, and Windows Sets seems to be postponed anyway, I'm closing this issue.
If Windows Sets ever come and there is a problem, open a new issue.

**Comment by Biswa96** [comment]
Though Windows Sets goes into cave there are some [tweets about it](https://twitter.com/h0x0d/status/1174973635515142145) by @WalkingCat. Also Windows Terminal uses tab thing but I don't know if it's normal Win32 APIs or fancier C++ WinRT things.
