### ISSUE TITLE
"Show bold as font" has no effect unless options saved or applied everytime a new wsltty window is opened.

### ISSUE THREAD

**Issue by ksze** [mintty/wsltty#103]
Using wsltty 1.8.5. I suppose this also applies to wsltty 1.8.5.2 since the only difference is the lack of a script to generate shortcuts during installation.

This is what I see when I start "WSL Terminal", and then immediately open options:
![image](https://user-images.githubusercontent.com/381556/40418081-f8f0137a-5eb3-11e8-9a2c-3e75bc4252c5.png)

Note that "Show bold as font" is *already* checked and saved.

However, I don't actually get font bolding until I click "Save" or "Apply" again:
![image](https://user-images.githubusercontent.com/381556/40418000-c64be78c-5eb3-11e8-872e-3e09dc2d080c.png)

**Comment by Biswa96** [comment]
Hmm... You want something like a preview.

But this is by-design in mintty. Click apply when you've set the option, then if you like it press save if not press cancel. That's it.

**Comment by ksze** [comment]
@Biswa96 No, I don't mean like a preview. The "Show bold as font" option was already enabled and saved, before I even opened the Options dialog. The weird thing is that the option isn't applied when the wsltty window is launched.

**Comment by mintty** [comment]
It happens due to parameter `--configdir="$APPDATA/wsltty"` if that directory contains a `config` file with an entry `BoldAsFont=-1`. Reproducible also without WSL.
To be analyzed: how that entry gets into the config file.

**Comment by mintty** [comment]
Released 1.9.0.
