### ISSUE TITLE
CTRL-Click URL does not work

### ISSUE THREAD

**Issue by imagesafari** [mintty/wsltty#104]
Like it does in mintty. Should it?

**Comment by mintty** [comment]
Yes, it should.

**Comment by mintty** [comment]
Well, actually, I suppose you clicked a relative pathname (problem descriptions would help...).
In that case, it should not. Or better, it cannot, unless you would use the current directory setting escape sequence in your prompt. Without that, mintty cannot know the reference point of the relative pathname.

**Comment by mintty** [comment]
OK, the OSC 7 trick does *not* yet work in WSL...

**Comment by imagesafari** [comment]
Sorry for the lack of detail, I just wasn't sure if it was supposed to work at all.

I did some testing, and it works in the shell on a URL, but it isn't working in weechat. Any ideas?

Thanks!

**Comment by mintty** [comment]
This is, again, unclear. What is weechat and what difference would it make.
What makes a difference, however, is whether the link is within the WSL root tree or in a (WSL-mounted) Windows folder tree.

**Comment by imagesafari** [comment]
weechat is a terminal-mode IRC client. I'm not sure what OSC 7 is, but the links I am referring to are web URLs.

**Comment by mintty** [comment]
https://github.com/mintty/mintty/wiki/CtrlSeqs#working-directory

Web URLs? Work well here. Please describe your issue *precisely*.

**Comment by Biswa96** [comment]
@imagesafari It will be better if you attach a screenshot or GIF image of your issue 😉

**Comment by imagesafari** [comment]
Here's a screenshot: http://km8v.com/u/40ynm

Typing a URL in at a bash or zsh prompt, CTRL-click works fine.

A URL in the ncurses IRC client, not so much. Happy to provide whatever additional detail.

Thanks!

**Comment by mintty** [comment]
Weird. Can you provide a reproducible test case, without having to install weechat? I.e. a screen log (e.g. using `tee`) that can be output with `cat` and exhibits the issue?

**Comment by imagesafari** [comment]
I'm not sure how well an ncurses output of weechat will translate with tee, but I can give it a shot.

**Comment by imagesafari** [comment]
[weechat.log](https://github.com/mintty/wsltty/files/2085911/weechat.log)

**Comment by mintty** [comment]
Thanks, but this file contains the github link 5 times, plus a lot of other stuff, and I did not succeed to reproduce the issue. Can you strip it down to a *reproducible test case*, please?

**Comment by imagesafari** [comment]
I am unable to reproduce the issue by cat'ing out a tee'd log of the weechat session. I can assure you that I can reproduce it by running weechat and trying to ctrl-click on a URL.

Any other ideas on how to capture some useful information?

**Comment by mintty** [comment]
OK, weechat is available as a cygwin package and I installed it. Entering a URL on the input line and clicking it works. How can I reproduce the situation in the screenshot?

**Comment by imagesafari** [comment]
Hmm. Backing out to default weechat config and it seems to work. It must have to do with one of the custom weechat buffer plugins. It may not be worth pursuing at this point, but if you'd like to I can send you some config files.

**Comment by mintty** [comment]
OK, I could have asked before; did you activate some application mouse mode for weechat?
In that case you'd need to press Shift+Ctrl+click to override.

**Comment by imagesafari** [comment]
Shift+Ctrl+Click does the trick. Thank you!

**Comment by mintty** [comment]
Released 1.9.0.
