### ISSUE TITLE
Suggestion: Query State registry value before invoking bash.exe

### ISSUE THREAD

**Issue by Biswa96** [mintty/wsltty#107]
In Insider builds there is a hidden enum of State registry value (in Lxss\GUID key). The enum looks like this:

```c
enum LxssDistributionState {
    Installed = 1,
    Installing = 3,
    Upgrading = 5
};
```

When `wsl.exe` or `bash.exe` is first executed that `State` registry value is queried as follows: 

```c
RegOpenCurrentUser(KEY_WRITE, &hKey);
const wchar_t* lpSubKey = L"Software\\Microsoft\\Windows\\CurrentVersion\\Lxss";
RegCreateKeyExW(hKey, lpSubKey, 0, NULL, 0, 0x2001Fu, NULL, phkResult, NULL);
RegGetValueW(phkResult, NULL, L"State", RRF_RT_REG_DWORD, NULL, value, sizeof(int));
return value;
```

The registry _value should be ONE_ (aka. Installed) before executing ELF64 binary. This procedure is done by `LxssManager.dll` internally. As `mintty` and `wslbridge` both requires GUID to run specified distro, it may be better if `wslbridge` or `mintty` query that `State` value. If the value is other than ONE, `wsl.exe` or `bash.exe` would not run and eventually `wslbridge` also.

**Comment by mintty** [comment]
Not quite clear. So if the value is Installing or Upgrading, there will be an error? With a proper error message (from wslbridge, likely)? In that case everything is OK, I'd say.

**Comment by Biswa96** [comment]
Yes, it's not so serious as I said before this is handled by LxssManager service. I saw it in newer versions of Windows so I share this. 

At the time of installing or upgrading, if a user launch wsltty he/she would see a warning like "can't launch....". So mintty or wslbridge may query that value. It's optional. 

This is just for discussion. @rprichard would like to know this.

**Comment by mintty** [comment]
I guess this is in fact for wslbridge, if at all. Thus closing.
I wouldn't expect any application, however, to behave properly at all while not yet fully installed, and very few will handled this explicitly.

**Comment by mintty** [comment]
I guess this is in fact for wslbridge, if at all. Thus closing.
I wouldn't expect any application, however, to behave properly at all while not yet fully installed, and very few will handled this explicitly.

**Comment by mintty** [comment]
Or is this actually the #116 or #72 issue?
