### ISSUE TITLE
zsh ctrl-r history search is garbled in wsltty 

### ISSUE THREAD

**Issue by dman777** [mintty/wsltty#108]
Using zsh in my linux cloud. The command search history feature(ctrl-r) is giving me issues. Specifically, the text gets garbled. Everything executes correctly regardless, but UX it's a bad experience.

The way I use wsltty is I ssh into my linux cloud from Windows 10 WSL. This issue with the garbled text in Zsh for ctrl search history _only happens in wsltty_. It does not happen on my Ubuntu laptop where I run urxvt as the terminal emulator. 

How can I fix it to where the text does not get garbled? The example below shows in red circles the text that is messed up and in green what it should look like.

![image](https://user-images.githubusercontent.com/887815/41164246-4f6dc64a-6b00-11e8-961f-f991ac808d32.png)

**Comment by mintty** [comment]
I've seen something similar reported, I guess to wslbridge, but don't find it again right now.
@Biswa96, any clue?
In any case, this is not a terminal issue.

**Comment by dman777** [comment]
@Biswa96 

Thanks! 

![image](https://user-images.githubusercontent.com/887815/41169154-afb79564-6b0d-11e8-8ecf-3d01ec2b8a1e.png)

For zsh:

```
% zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```

**Comment by mintty** [comment]
Similar to rprichard/wslbridge#15, however, there wslbridge was mistakenly run in a Windows console.
Might still be a communication issue between wslbridge frontend and backend, though.
Or something completely different and obscure...

**Comment by Biswa96** [comment]
@dman777 Are you using any type of themes or customisation or shell script to look zsh better?

**Comment by dman777** [comment]
No, I am not. I am using a barebones zsh system. Although I am using menu completion if that matters, but that is native also. Here are my options enabled:

```
% setopt
alwaystoend
autocd
nobeep
correct
extendedglob
interactive
kshglob
login
monitor
printeightbit
shinstdin
zle
```

Also,  here is my PS1 prompt:
```
%K{blue}%n@%m%k %B%F{green}%(4~|...|)%3~%F{white}
%# %b
```

**Comment by mintty** [comment]
If obscure things happen, potential influence factors should be reduced.
Change your prompt to something trivial (no %).
Also, a cross-check with another terminal would be useful.

**Comment by dman777** [comment]
I used the windows console yesterday instead(the Ubuntu command) and did not have this issue with zsh. I also don't have this zsh issue with urxvt in Linux. Is that what you mean by cross check with another terminal?

**Comment by Biswa96** [comment]
Try to check that issue with only wslbridge.

**Comment by mintty** [comment]
You mean urxvt in native Linux? Or urxvt e.g. from cygwin, then running WSL?
A significant cross-check should take out the component being questioned and leave in as many other components as possible (WSL and perhaps wslbridge in this case).
It might be even more helpful on the other hand, to clear your prompt to a basic one, as a test case.

**Comment by Biswa96** [comment]
Go to this folder `C:\Users\your_user_name\AppData\Local\wsltty`. See `wslbridge.exe`, double click on it and repeat what you've done before. If that problem persists then the issue related to wslbridge. If not the the issue related to mintty.

* Formula: wsltty = wslbridge + mintty

**Comment by mintty** [comment]
Yet there are some diagnostic options that might help.
1. Please make a terminal log, with `tee` (on WSL) and also with mintty (Log to File in context menu).
2. Do strip your prompt of all magic functions (beginning with '%'). I'm asking this for the third time now...

**Comment by dman777** [comment]
How will I use tee with zsh ctrl-R command history search? the issue is only when I use ctr-r and do searches in history the display text get garbled.

**Comment by mintty** [comment]
tee zsh

**Comment by dman777** [comment]
It just hangs when I use `tee zsh`.... like it's taking stdio directly to tee instead of the shell. ctrl-r will only produce `^R`.

**Comment by mintty** [comment]
I intend to close the issue due to missing response to my repeated request to minimize the test case.

**Comment by dman777** [comment]
If I do `PROMPT="%"` I do not seem to have the issue in wsltty.

**Comment by dman777** [comment]
I haven't had any success with getting the config file feature to work. I start wsltty with `C:\\Users\darin.hensley\AppData\Local\wsltty\bin\mintty.exe --WSL= --configdir="C:\\wsltty-config" -~`, but when I try to save I get the error message:

![image](https://user-images.githubusercontent.com/887815/41784044-25592624-7604-11e8-9368-02c245d88301.png)

**Comment by Biswa96** [comment]
Only single slash not double slash.

**Comment by mintty** [comment]
Not sure what you're trying to save, the log file cannot be configured in the Options menu.
Run this
`C:\Users\darin.hensley\AppData\Local\wsltty\bin\mintty.exe --WSL= -l log108.txt`
to create a log file in the current directory.

**Comment by dman777** [comment]
Ok, I cut out from the log where I do the reverse search. I see a lot of ASCII characters that look gibberish :

```
bck-i-search: edit_[K[A
[A[2Cvi[6P[70C[4medit[24m.ht[24mm[24ml[24m      [A[65C[72D[32mv[32mi[39m[70C[24me[24md[24mi[24mt[2B
[K[A[A[74C>[?2004l[2B
[?1049h[?1h=[2;1H▽[6n[2;1H  [1;1H[1;62r[?12;25h[?12l[?25h[27m[23m[m[38;5;253m[H[2J[?25l[62;1H<c/sp-elements/sp-static-forms/sp-disabilities/sp-disabilities-form-edit.html"
```

**Comment by mintty** [comment]
If I `cat` this text to the terminal, I get a clear, ungarbled output of
`<c/sp-elements/sp-static-forms/sp-disabilities/sp-disabilities-form-edit.html"`
So what's wrong with this? I asked for a test case and you send a text that contains a chaotic mix of control sequences, but apparently no wrong output...

**Comment by mintty** [comment]
Closing as there is no indication of a bug.
