### ISSUE TITLE
Two windows open per session

### ISSUE THREAD

**Issue by caksoylar** [mintty/wsltty#109]
I recently upgraded to 1.8.5.2 using https://github.com/mintty/wsltty/archive/1.8.5.zip and running the install script. (I mention this because the installer never configured the shortcuts properly because I believe mkshortcut didn't work, which might be the subject of another issue.) After upgrading using install.bat, I get two windows open per session, which looks like this:
![wsltty double window](https://user-images.githubusercontent.com/7876996/41174416-ec3800b8-6b0e-11e8-9ec4-2710593aa7e6.png)
The first window (on top) is not interactive. Same things happens if I run %localappdata%\wsltty\bin\mintty.exe, which shows an error on the second window "/bin/bash not found" which I assume is expected.

I am running Insider preview build 17686 (which has the sets feature that shows these tabs) and disabling tabs for the shortcut doesn't change things. Let me know if there is additional information I can provide and thanks for all the work on mintty/wsltty.

**Comment by Biswa96** [comment]
Did you check `cygwin-console-helper.exe` present in `%LocalAppData%\wsltty\bin` folder?

**Comment by caksoylar** [comment]
No I only have the following files in that folder:
![image](https://user-images.githubusercontent.com/7876996/41175160-063d565a-6b11-11e8-8daa-f01b681c373b.png)
Is that supposed to come with the installation?

**Comment by Biswa96** [comment]
Yes, I've saw this issue before while working with wsltty.appx. mintty suggested me to place that executable file in `/bin` folder. You can grab that console helper from a matching cygwin installation.

@mintty May you share some views about that console helper? Where's the source code of that executable?

**Comment by Biswa96** [comment]
If this issue is solved you may close it.

**Comment by mintty** [comment]
The console-helper is a cygwin base component.
If the background window in the screenshot is a console, that explains it. I wasn't sure because it also shows indications of the new Windows Sets (i.e. Tabs) feature and I had the suspicion this might interfere.

**Comment by caksoylar** [comment]
Yeah the background one is the actual working console. I also suspected the Sets feature but I added the program to its exceptions and it didn't change anything. Closing the issue as it was user error regarding the installation.
