### ISSUE TITLE
Question: what does "Leading: 2" mean in "Options" -> "Text"?

### ISSUE THREAD

**Issue by ksze** [mintty/wsltty#113]
I'm talking about this:
![image](https://user-images.githubusercontent.com/381556/42194459-a71e14bc-7ea6-11e8-8284-52e7cab872a2.png)

What does that do? Is that configurable (maybe via manually editing a config file)?

For the record, I have been a long term user of Cygwin and I still have that on my Windows 10 machine. I also see that "Leading: 2" in Cygwin's mintty options.

**Comment by mintty** [comment]
It's the additional vertical distance between text lines. Its value is derived from font properties and can be further modified with option `RowSpacing`. See also https://github.com/mintty/mintty/wiki/Tips#window-geometry-rows-and-columns.

**Comment by ksze** [comment]
I see. Thanks for the quick explanation!
