### ISSUE TITLE
WSL Couldn't find distribution

### ISSUE THREAD

**Issue by JAffleck** [mintty/wsltty#116]
After installing Debian WSL from windows store.
I then installed `wsltty` from chocolatey with these commands:
`choco install wsltty`
`choco upgrade wsltty`
IIRC I ran the `Generate WSL shortcuts` command,
Then ran the `configure WSL shortcuts` from windows start menu.
I then tried running `WSL Terminal` and `WSL Terminal %`
Both would return the same error as [this issue](https://github.com/mintty/wsltty/issues/72#issuecomment-345061676)
I tried re-running `configure WSL shortcuts` and had no luck.
I then ran `wslconfig /l`, and it gave the output  

`Windows Subsystem for Linux Distributions:`
`Debian (Default)`

I then ran 
`wslconfig /s Debian`

And IIRC I re-ran the `configure WSL shortcuts`
And then ran the 
`WSL Terminal` and `WSL Terminal %`
And both ran properly without the error that it couldn't find the distribution like before.

Hopefully this helps troubleshoot the issue, of why wsltty isn't finding a distribution or provides simple documentation for anyone else hitting the error for how to fix it.

**Comment by mintty** [comment]
> Both would return the same error as this issue

As you can see in that issue, error information had been extended since. Can you reproduce the issue and quote the full error information?

**Comment by mintty** [comment]
Any further insights or reproducible test case? Otherwise intending to close eventually...
