### ISSUE TITLE
wsltty is not hidpi aware?

### ISSUE THREAD

**Issue by damex** [mintty/wsltty#117]
hello,

i just tried last wsl tty from the windows/msi installer (1.9.0.2) and it is not hidpi aware.

all the menus in wsltty on 2k 14' screen is very small/barely usable and on 4k 15' screen is non-readable/non-usable.

is there anything that could be done?

**Comment by mintty** [comment]
Actually, 1.9.0 has just added support for the new DPI handling V2, so if you run the latest Windows version (maybe it's a developer preview still), everything should be fine.
Before that, in fact menus used to be scaled down (or rather, not scaled up properly). This is a Windows deficiency, not a wsltty bug, cf. mintty/mintty#588.

**Comment by damex** [comment]
okay, i guess it is scaled but if that is how it is scaled - let's close it.

it is still look very small and unusable in my case :(

**Comment by mintty** [comment]
I did not mean to suggest the observed behaviour is correct. But the fix is in Windows not in mintty. Wait for the update.
