### ISSUE TITLE
backend program is missing

### ISSUE THREAD

**Issue by Epaenetus** [mintty/wsltty#118]
I get the following error when trying to build the source. 

> error: 'C:\cygwin64\bin\wslbridge-backend' backend program is missing

Here is more detailed log:

	$ make
	# checking suitable host environment; run `make pkg` to bypass
	# check cygwin (vs msys) for proper drag-and-drop paths:
	uname | grep CYGWIN
	CYGWIN_NT-10.0
	# check 32 bit to ensure 32-Bit Windows support, just in case:
	#uname -m | grep i686
	# check 64 bit to provide 64-Bit stability support:
	uname -m | grep x86_64
	x86_64
	curl -R -L --connect-timeout 55 https://github.com/rprichard/wslbridge/archive/4                                                                                                                                                                                               7b41bec6c32da58ab01de9345087b1a4fd836e3.zip -o wslbridge-47b41bec6c32da58ab01de9                                                                                                                                                                                               345087b1a4fd836e3.zip
	% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
									Dload  Upload   Total   Spent    Left  Speed
	100   158    0   158    0     0    158      0 --:--:-- --:--:-- --:--:--   459
	100 37014    0 37014    0     0  37014      0 --:--:-- --:--:-- --:--:-- 37014
	unzip -o wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3.zip
	Archive:  wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3.zip
	47b41bec6c32da58ab01de9345087b1a4fd836e3
	creating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/.gitattributes
	extracting: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/.gitignore
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/CHANGES.md
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/LICENSE.txt
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/README.md
	extracting: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/VERSION.txt
	creating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/backend/
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/backend/Makefile                                                                                                                                                                                               
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/backend/wslbridg                                                                                                                                                                                               e-backend.cc
	creating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/common/
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/common/SocketIo.                                                                                                                                                                                               cc
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/common/SocketIo.                                                                                                                                                                                               h
	creating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/appveyor.ym                                                                                                                                                                                               l
	creating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/cygwin-preb                                                                                                                                                                                               uilts/
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/cygwin-preb                                                                                                                                                                                               uilts/appveyor.yml
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/cygwin-preb                                                                                                                                                                                               uilts/dllversion.py
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/cygwin-preb                                                                                                                                                                                               uilts/make-cygwin-prebuilts.py
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/cygwin-preb                                                                                                                                                                                               uilts/make-msys2-prebuilts.py
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/make-backen                                                                                                                                                                                               d-package.py
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/make-bin-pa                                                                                                                                                                                               ckage.bat
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/make-fronte                                                                                                                                                                                               nd-packages.py
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/dist/util.py
	creating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/frontend/
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/frontend/Makefil                                                                                                                                                                                               e
	inflating: wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/frontend/wslbrid                                                                                                                                                                                               ge.cc
	tr -d '\015' < wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/LICENSE.txt >                                                                                                                                                                                                LICENSE.wslbridge
	cd wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/frontend; make
	make[1]: Entering directory '/home/user/wsltty/wslbridge-47b41bec6c32da58ab01de                                                                                                                                                                                               9345087b1a4fd836e3/frontend'
	mkdir -p ../out
	g++ -std=c++11 -fno-exceptions \
			-static -static-libgcc -static-libstdc++ \
			-D_GNU_SOURCE -D_WIN32_WINNT=0x0600 -DUNICODE -D_UNICODE \
			-DWSLBRIDGE_VERSION=0.2.5-dev \
			-Wall -O2 wslbridge.cc ../common/SocketIo.cc -o ../out/wslbridge.exe
	strip ../out/wslbridge.exe
	make[1]: Leaving directory '/home/user/wsltty/wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/frontend'
	strip wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/out/wslbridge.exe
	mkdir -p bin
	cp wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/out/wslbridge.exe bin/
	cd wslbridge-47b41bec6c32da58ab01de9345087b1a4fd836e3/backend; wslbridge make
	error: 'C:\cygwin64\bin\wslbridge-backend' backend program is missing
	make: *** [makefile:119: wslbridge-backend] Error 1

Let me know if you need any further information.

**Comment by mintty** [comment]
To build wsltty from cygwin, wslbridge-backend needs to installed at least once already in the default WSL installation. Similar trouble may occur when updating wslbridge and an older version backend is still installed. It's a kind of hen-or-egg problem: you need the WSL gcc to build the backend, but you can't access it (from the build script) without a backend... So initially, the backend must be built manually on the WSL side. I'll check how to clarify that in the descriptions.

**Comment by Epaenetus** [comment]
Thank you for the reply, I really appreciate it!

I have WSL installed by follow these [instructions](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

So if I'm understanding this properly, I need to build the [WSL backend ](https://github.com/rprichard/wslbridge)manually in WSL. Once its built, will the makefile automatically find it or will I need to copy it to a specific location? 

I'm still new to the WSL and Cygwin environment so let me know if I'm missing something.

**Comment by mintty** [comment]
I've removed the hen-or-egg dependency on wslbridge-backend for building wslbridge, at least for 64 bit.
It invokes wsl make via cmd /C (which does not work from cygwin 32 bit).

**Comment by mintty** [comment]
If you confirm the patch works, we could close the issue.

**Comment by mintty** [comment]
Released wsltty 1.9.2.
