### ISSUE TITLE
Windows Context Menu item... Removal!

### ISSUE THREAD

**Issue by thejimmyjames** [mintty/wsltty#12]
Mintty for BASH on WSL installs a not-always-wanted (as in, I never want context menu crap) context menu handler. I can't find it in Regedit to remove it.

I need to know how because I hate having crap in my Explorer menus. Also, no uninstall for minty for Bash on WSL so I can't remove it to eliminate the unwanted menu item.

**Comment by thejimmyjames** [comment]
Batch file found in ~/appdata/local/thingy to remove application and its offending context menu handler.

Please ask permission to install that crap. Thanks. I won't be reinstalling this software.

**Comment by mintty** [comment]
Uninstall from Start menu is a fair request. Note that this is still release 0.something of the package, so your consequence sounds a bit harsh. The context menu was added in response to request of other users.

The wsltty installer uses a very basic Windows stock installer generator that does not offer any way of interaction to choose installation options. You are welcome to make a proposal to improve that.

**Comment by thejimmyjames** [comment]
A fair suggestion! I do also apologize for that harshness, I didn't intend for it to be such. In the meantime, would it be possible for you to publish the Registry key that the installer invokes to enable the context menu item for manual removal?

I'd like to use mintty, but I'm very picky about the right-click menus.

**Comment by thejimmyjames** [comment]
I found a deceptively simple way to fix the issue without uninstalling the application!

I edited the uninstall.bat file and rem'd out the lines that actually remove it. So I was able to eliminate the menu without losing minty!

I... Honestly have no idea why I didn't think of doing that when I saw that a batch file was used for uninstall.
