### ISSUE TITLE
Console.ReadKey(true) fails with InvalidOperationException

### ISSUE THREAD

**Issue by Memphizzz** [mintty/wsltty#120]
This happens on Windows 10 and any C# .NET console application that calls ReadKey(true) instead of ReadLine (which works fine).
I've seen this problem on Mintty with cygwin, but I was hoping that WSLtty was able to work around this.

Is this a bug currently or is this the same as in cygwin, wont ever work?

I've read about conin, don't know if thats what I need, if so, how would I be able to use it in C#?

Thank you very much for WSLtty/Mintty and keep up the great work!

**Comment by Biswa96** [comment]
Need some information.
1. What's your Windows build number?
2. Did you see this issue only with wsltty? Did you try with bare CMD or Powershell?
3. Provide a sample code snippet that causes the issue.

**Comment by Memphizzz** [comment]
Hi, 

of course:
1. 1803 (17134.228)
2. I saw this on Mintty using cygwin as well. In CMD and PowerShell it works fine.
3.

`using System;

namespace Universe
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello world");
            Console.ReadKey(true);
            Console.WriteLine("Goodbye world!");
        }
    }
}`

I've attached a compiled version of it. Its targeting .NET Framework 2.0.

Thanks!

[HelloWorld.zip](https://github.com/mintty/wsltty/files/2358860/HelloWorld.zip)

**Comment by Memphizzz** [comment]
Sorry for the delay, I just tested it. It doesn't work but it also messes up the consoles input line. I can't see what im typing anymore. But by pressing the up arrow twice I get to execute the HelloWorld.exe and it crashes as well.

**Comment by mintty** [comment]
This runs fine in cygwin with winpty.
It does not run via wslbridge, but:
It neither runs in plain WSL, from a Windows console.
As mintty is not involved in the latter case (nor is wslbridge), I'm closing the issue. Please try at https://github.com/Microsoft/WSL/issues or https://github.com/Microsoft/console/issues.
