### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by skywind3000** [mintty/wsltty#122]
mintty for cygwin supports background image now: https://github.com/mintty/mintty/issues/18,
which is really cool.

can wsltty include this feature too.

**Comment by Biswa96** [comment]
One of my favorite feature of mintty ❤️ This feature is from mintty version 2.9.0.

What I do:
1. Open mintty with ` /bin/bash.exe -l -i` option in _Cygwin_.
2. Run `mintheme` command with picture file path. For example: `/bin/mintheme -p picture_file.png`
3.  Copy `wslbridge.exe` and `wslbridge-backend` in Cygwin `/bin` folder.
4. Run `/bin/wslbridge` command in mintty.

[Screenshot](https://user-images.githubusercontent.com/31443074/45572688-a13c9d00-b887-11e8-841c-d5eddf330449.PNG)

But I can not run `mintty.exe mintheme --WSL` command simultaneously.

**Comment by mintty** [comment]
You can configure a background image in your config file (for WSL, that should be %APPDATA%/wsltty/config) or dynamically with an escape sequence (ESC]11;_image.pngESC\).
However, from WSL, a WSL pathname should be used.
A Windows pathname should also be accepted but apparently that does not work yet.

**Comment by skywind3000** [comment]
Thanks, I have appended this line to my `%APPDATA%/wsltty/config`:

```
Background=_/mnt/c/Users/XXXXX/sierra.bmp,39
```

And it works.

**Comment by mintty** [comment]
Released wsltty 1.9.2.
