### ISSUE TITLE
Would it be feasible to add some syntax highlighting (regex matching that can be customized) to the SSH terminal? Like one can in Mobax?

### ISSUE THREAD

**Issue by i7cud4** [mintty/wsltty#124]

**Comment by Biswa96** [comment]
wslbridge is not completely same as SSH. Did you mean to say the Linux SSH?

**Comment by mintty** [comment]
That is not a terminal feature. Also wslbridge is used to establish the terminal functionality within the WSL terminal, it is not really a communication component. Therefore marking invalid and closing soon.

**Comment by i7cud4** [comment]
> wslbridge is not completely same as SSH. Did you mean to say the Linux SSH?
