### ISSUE TITLE
wsl/mintty only - bad glyphs rendered-

### ISSUE THREAD

**Issue by aabatpurdue** [mintty/wsltty#125]
On my machine, the WSL _mintty_ does not seem to be able to render at least two glyphs (see second line below).  This seems to occur on the WSL _mintty_ only. The _mintty`s`_ on **MSYS2**, **Cygwin** and **Git for Windows** render properly.  The glyphs should be a "single open (left) quote", "single closing (right) quote" pair.  Note that these two glyphs are three(3) bytes long below.   My default font is 11-point Consolas.  I also tried 11-point Lucida Console but it made no difference.  I'm using **Ubuntu 18.04**.  FWIW - I get identical _od_ output on **MSYS2**, etc..

```
 $ stty -f
stty: invalid argument ▒▒▒-f▒▒▒
Try 'stty --help' for more information.
 $ stty -f 2>&1 | od -tx1z
0000000 73 74 74 79 3a 20 69 6e 76 61 6c 69 64 20 61 72  >stty: invalid ar<
0000020 67 75 6d 65 6e 74 20 e2 80 98 2d 66 e2 80 99 0a  >gument ...-f....<
0000040 54 72 79 20 27 73 74 74 79 20 2d 2d 68 65 6c 70  >Try 'stty --help<
0000060 27 20 66 6f 72 20 6d 6f 72 65 20 69 6e 66 6f 72  >' for more infor<
0000100 6d 61 74 69 6f 6e 2e 0a                          >mation..<
0000110
 $
```

**Comment by mintty** [comment]
This does not look like a glyph problem, rather an encoding problem.
Please check your locale setting in the mintty Options menu.
How do you start wsltty? Maybe you changed the character set explicitly for some reason in a common configuration file, like $APPDATA/mintty/config?

**Comment by aabatpurdue** [comment]
There was an errant `Charset=` in the rc file, that's `Charset=zilch`.  Removing it cleared up the problem.  Setting which _mintty_ option would cause that?
