### ISSUE TITLE
Launching from the taskbar starts a new task, rather than keep the task in the place of the icon

### ISSUE THREAD

**Issue by markusjevringgoeuro** [mintty/wsltty#126]
I get that the description is a bit wonky, but I'm not sure what the correct words are. It's like this: I have pinned the shortcut (I've tried all version of the shortcuts, etc, and nothing works) to my taskbar. When I click it, I expect the application to launch, and the task bar to be where the button is. However, this doesn't happen. It launches a second task in the taskbar.

This wasn't the case with my previous wsltty version, but unfortunately I don't know what version that was

**Comment by markusjevringgoeuro** [comment]
Here's a screenshot and explanation https://imgur.com/a/ffr31dC

**Comment by willpower232** [comment]
Sounds very similar to https://github.com/mintty/wsltty/issues/96

**Comment by mintty** [comment]
Yes, and it's actually a Windows problem, not an application problem.
See for example also [Some taskbar pinned icons are duplicated when an instance of the application is running](https://superuser.com/questions/214400/some-taskbar-pinned-icons-are-duplicated-when-an-instance-of-the-application-is).

**Comment by markusjevringgoeuro** [comment]
Sorry, I'm running 1.9.0.2, downloaded mere hours ago.

**Comment by markusjevringgoeuro** [comment]
I've tried `AppID=@` in various forms on the command-line, including the `-o` option in the referenced ticket, but without any luck

**Comment by markusjevringgoeuro** [comment]
That linked stackoverflow response makes a good point. We do pin the shortcut, rather than the application itself. However, pinning the application itself (which I also tried) doesn't work. We might be able to produce a think wsltty.exe wrapper, but then we won't have the option of passing it any command-line arguments.

**Comment by mintty** [comment]
If you download yourself, you should update minttyver=2.9.1 in the makefile to refer to a newer version and have the option value AppID=@ available.
If you produce a wrapper it should not be a problem to pass on arguments.
Who is "we" in this context? Any project that might be interesting for mintty?

**Comment by markusjevringgoeuro** [comment]
"We" in this case simply meant "wsltty users".

**Comment by markusjevringgoeuro** [comment]
I checked another computer which has this feature working, and that was wsltty 1.8.4, with mintty 2.8.4. Just for reference.

**Comment by mintty** [comment]
See also #127. Please check whether really *all* use cases work as expected in your 1.8.4 setup.

**Comment by mintty** [comment]
Released 1.9.4.
