### ISSUE TITLE
Start menu/taskbar "Ubuntu-18.04 Terminal" shortcut funnies --

### ISSUE THREAD

**Issue by aabatpurdue** [mintty/wsltty#127]
Funny 1)
If I left click on the start menu shortcut icon for `Ubuntu-18.04 Terminal` that's defined as
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL="Ubuntu-18.04" --configdir="%APPDATA%\wsltty" -~ `
it instantiates fine as
`"C:\Users\me\AppData\Local\wsltty\bin\mintty.exe" --WSL="Ubuntu-18.04" --configdir="C:\Users\me\AppData\Roaming\wsltty" -~ `

Now if I right click on the resulting Penguin icon in the taskbar and then left click on "Terminal" (note it's not "Ubuntu-18.04 Terminal"), it instantiates as
`"C:\Users\me\AppData\Local\wsltty\bin\mintty.exe" `
which of course doesn't work worth beans. 

Funny 2)
I can create a permanent Penguin taskbar icon if I right click on the start menu shortcut icon for `Ubuntu-18.04 Terminal` then left click on "More" then left click on "Add to taskbar".  Now I can left click on that taskbar Penguin icon all day long and it will always instantiate properly.  If I right click on the icon, I can left click on `Ubuntu-18.04 Terminal` (note it's not `Terminal`) with the same result.  The funny part is that a second Penguin icon is generated that represents the instantiations generated by clicking on the first icon.  Right clicking on the second icon shows `Terminal` and left clicking on that results with same problem as "Funny 1".

I did a reinstall but no changes were observed.  FMI - I noticed a couple of "can't find such-and-such-path" in the data displayed in the Console Prompt window and was wondering if there is an install log of them so that I could have checked to see what they were.  They went by too fast for these old eyes to decipher (:-}).

--  Thanks

**Comment by mintty** [comment]
The behaviour of taskbar icons is influenced by the AppID (which can be set for mintty/wsltty with an AppID parameter). If you add `AppID=something` to the start icon, you may experience different behaviour.
However, Microsoft in their infinite wisdom have designed the taskbar mechanism so that it does not seem to be possible to support all use cases properly at the same time...

**Comment by mintty** [comment]
Released 1.9.4 which may enhance the behaviour.
