### ISSUE TITLE
Doesn't scroll up in `less` program

### ISSUE THREAD

**Issue by soundlake** [mintty/wsltty#128]
wsltty version: 1.9.2

Instruction to reproduce the issue:
- Open a text file, i.e. log file, with `less` program.
- scroll down with `j` key
- scroll up with `k` key

There's no problem of scroll down, but when you scroll up, only the first line of the screen is updated, and the rest of screen remains same.

**Comment by mintty** [comment]
Yes, that's why the 1.9.2 installer was meanwhile deleted from the release.
Wait for the 1.9.3 update today.

**Comment by soundlake** [comment]
@mintty Thank you very much. It works just fine!
