### ISSUE TITLE
Sending numeric keypad keys to the terminal

### ISSUE THREAD

**Issue by ksze** [mintty/wsltty#129]
mintty 1.9.3
Window 10 Pro 1809
WSL distro: Ubuntu 18.04 LTS (https://www.microsoft.com/store/productId/9N9TNGVNDL3Q)

I use vim as my main text editor. There's this really nice vim plugin called "vim-mark" (https://github.com/inkarkat/vim-mark). The plugin allows you to highlight multiple pattern groups, each in a different colour, and also use the numeric keypad to quickly jump to occurrences of a particular pattern group.

The numeric keypad works in **gvim** in the GNOME desktop of a real Ubuntu 18.04 host (not VM guest, not WSL). However, they don't work when I'm using vim in the WSL Ubuntu via wsltty. I bet it's because wsltty doesn't send the real numeric keypad keycodes to the terminal.

`$TERM` is reported as `xterm-256color`.

To be fair, there seems to be a similar problem when using vim (not gvim) in the GNOME Terminal app in a GNOME session on the real Ubuntu 18.04 host. Same thing when using WSL Ubuntu via Windows' Console Window Host (`conhost.exe`).

**Comment by Biswa96** [comment]
There is a dependency hierarchy wsltty. wsltty --> mintty + wslbridge --> bash.exe + conhost.exe. Hence if there is any bug with conhost.exe it is reflected in wsltty. You can follow this [Microsoft/console](https://github.com/Microsoft/console/issues) issue tracker. There are many issues with vi, vim, nano, tmux etc.

**Comment by Biswa96** [comment]
There is a dependency hierarchy wsltty. wsltty --> mintty + wslbridge --> bash.exe + conhost.exe. Hence if there is any bug with conhost.exe it is reflected in wsltty. 

The `$TERM` environment variable is configured to `xterm-256` in `lxss` registry by LxssManager service. You can change that from `regedit.exe`. I don't if this is related with your real issue.

Follow this [Microsoft/console](https://github.com/Microsoft/console/issues) issue tracker for further details. There are many issues with vi, vim, nano, tmux etc.

**Comment by Biswa96** [comment]
wsl.exe and bash.exe use these: 1. `SetConsoleCP(CP_UTF8);` and `SetConsoleOutputCP(CP_UTF8);` for UTF-8 code page 2. `ENABLE_VIRTUAL_TERMINAL_INPUT` flag for stdin and `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag for stdout/stderr.

**Comment by ksze** [comment]
Trying to supply the test cases is proving quite hard.

I have tried using the numeric keypad in a few ways:

1. vim in the GNOME Terminal app, in a GNOME session.
2. vim in a "real" tty (e.g., the one you get when you press Ctrl+Alt+F3 in Ubuntu).
3. gvim in a GNOME session.

We already know that the numeric keypad doesn't work in the 1st case. Surprisingly, it also doesn't work in the 2nd case. So far, the numeric keypad only works correctly in the 3rd case (gvim in a GNOME session). However, if I `kill -9` gvim, the whole window just disappears and I can't even try the Ctrl+V trick.

Not all hope is lost, however. I grep'ed the vim source code and found the definitions for the numeric keypad keys at https://github.com/vim/vim/blob/master/src/keymap.h#L403-L412

```c
#define K_K0		TERMCAP2KEY('K', 'C')	/* keypad 0 */
#define K_K1		TERMCAP2KEY('K', 'D')	/* keypad 1 */
#define K_K2		TERMCAP2KEY('K', 'E')	/* keypad 2 */
#define K_K3		TERMCAP2KEY('K', 'F')	/* keypad 3 */
#define K_K4		TERMCAP2KEY('K', 'G')	/* keypad 4 */
#define K_K5		TERMCAP2KEY('K', 'H')	/* keypad 5 */
#define K_K6		TERMCAP2KEY('K', 'I')	/* keypad 6 */
#define K_K7		TERMCAP2KEY('K', 'J')	/* keypad 7 */
#define K_K8		TERMCAP2KEY('K', 'K')	/* keypad 8 */
#define K_K9		TERMCAP2KEY('K', 'L')	/* keypad 9 */
```

They use a `TERMCAP2KEY` macro, which is defined at https://github.com/vim/vim/blob/master/src/keymap.h#L125:

```c
#define TERMCAP2KEY(a, b) (-((a) + ((int)(b) << 8)))
```

If my calculations are correct, that the numeric keypad "1" is translated thus:

a == 'K' == 75 in decimal
b == 'D' == 68 in decimal
(-((a) + ((int)(b) << 8))) =
(-((75) + (68 * 256))) =
(-(75 + 17408)) =
-17483

Which would be the byte sequence 0xb5 0xbb in little endian order.

Not sure if any of this makes any sense. ¯\_(ツ)_/¯

**Comment by mintty** [comment]
Actually gvim is not significant as it does not run in a terminal as you noticed.
So there is no case of these keys working inside a terminal? This makes analysis more complicated.
I suggest you ask that project how it's supposed to be integrated inside a terminal.
From quickly browsing its source, it seems they didn't care at all. But I'm sure it's possible to add that with some suitable vim macros.
There's one thing you could try meanwhile, without expecting much though: from the mintty extended context menu (Control+right-click), select "VT220 keyboard".

**Comment by mintty** [comment]
Browsing the referred plugin docs again, it seems to make use of some <Leader> key prefix without explaining what that is. Maybe some generic vim concept. Does it work in any context in the terminal?
Summarizing, if you want to achieve functionality provided by the plugin within a terminal, you'd first need to acquire information from the plugin what _key codes_ (i.e. escape sequences) the plugin actually expects. Missing such information, I'm marking this issue as invalid for now.
Note however that mintty supports all kinds of usage of the keypads and its modified key combinations.

**Comment by flashflexpro** [comment]
this is actually impport to be consistent with Windows, because num pad with a "num lock" can switch in between numbers and navigation keys, and it should work same way in WSL!

**Comment by mintty** [comment]
NumLock does switch to numbers in mintty. You can still generate escape sequences from the numeric keypad with modifiers (like Ctrl, Shift).
