### ISSUE TITLE
Additional options for installer

### ISSUE THREAD

**Issue by thejimmyjames** [mintty/wsltty#13]
Just a couple of options that would be nice!

I'm not a fan of desktop icons or right-click menu items, but diff'rent strokes for diff'rent folks. It would be nice to be able to choose whether to install those items during setup.

Amazing 3D graphics with dancing dinosaurs and a soundtrack by Sting and the Police during the install would be cool but immaterial to the project, so I don't suggest pursuing those features ;)

**Comment by mintty** [comment]
The plan is:
* add a Start Menu folder, with a sub-folder "Context Menu Shortcuts", with these items:
  * install Context Menu shortcuts to start WSL in current (selected or open) folder or drive
  * uninstall those shortcuts
* include Desktop Shortcuts to start in User Profile or Linux Home in Start Menu folder
* not install them by default on the desktop anymore
* not install them in the Start Menu (top above folders) anymore

Comments welcome. Maybe one more visible Shortcut by default would be good but where and which one?

**Comment by thejimmyjames** [comment]
Have all the options in a "Mintty for WSL" folder in Start's "All Apps" list? Sounds very nice. I don't think it would be that bad if "BASH on UoW in Mintty" remains top-level.

**Comment by mintty** [comment]
Revised set of installed shortcuts and command-line scripts in 0.7.0.
