### ISSUE TITLE
Font Symbol issue

### ISSUE THREAD

**Issue by sagarrabadiya** [mintty/wsltty#130]
Hi, Thanks for the great terminal app, I am having an issue with the default prompt's right side arrow character, it doesn't show correctly, previously it was working but after update, it doesn't show right side arrow character, I am already using powerline fonts and other characters are shown as expected, please check attached screenshot.

![image](https://user-images.githubusercontent.com/5405403/47133986-b6fb1300-d2c8-11e8-98cc-a8362777ff00.png)

**Comment by Biswa96** [comment]
Provide some information
* What shell are you using bash or zsh?
* Is there any script to configure the prompt characters?
* Does only bash.exe or wsl.exe show that error? 
And of course the Windows 10 version and wsltty version.

**Comment by sagarrabadiya** [comment]
I am using ZSH (oh-my-zsh)
there is no script to configure prompt characters, its default prompt of oh-my-zsh (robbyrussell)
bash.exe and wsl.exe both has this problem,
windows version 1809, (build 17763.55) wsltty 1.9.3, which includes mintty 2.9.3

**Comment by sagarrabadiya** [comment]
also with the same font, Visual studio code, integrated terminal shows that character correctly (check screenshot). so seems the problem is not with the font, but with the wsltty or mintty font rendering.

![image](https://user-images.githubusercontent.com/5405403/47136712-33deba80-d2d2-11e8-92a3-45fbb38a96be.png)

**Comment by mintty** [comment]
What's the actual character being output, including escape sequences that may impact the result?
Using a logfile or any other trick, try to extract the prompt into a plain text file which, when output with `cat`, demonstrates the issue. Then include or upload it here or hexdump it with `od`.
Which font have you configured? Provide a download link.

**Comment by sagarrabadiya** [comment]
Fonts are here https://github.com/whitecolor/my-nerd-fonts/tree/master/Consolas%20NF

the actual text is `➜ ` when i paste it in github comment it changes to arrow

od -c filename.txt output is as below
```
od -c ~/robbyrussel.txt
│0000000 342 236 234      \n
│0000005
```

[robyrussle.txt](https://github.com/mintty/wsltty/files/2490830/robyrussle.txt)

also the file is attached here which contains only that character and nothing else.

**Comment by mintty** [comment]
Reproduced; it looks like the symbol is simply not contained in the font.
You say it used to work? Which version? Any other changes since? Can you reproduce it now?
With DejaVu Sans Mono the symbol is shown. Sure you used the same font before?

**Comment by sagarrabadiya** [comment]
yes, I am pretty sure, I previously used Ubuntu Mono for powerline font and that symbol was showing that time, after that I got windows 10 octorber 2018 update, and after that this symbol doesn't show with neither of the font, you can try with ubuntu mono for powerline font also it doesn't show this symbol surprisingly with dejavu sans mono it shows, but if i use same consolas NF font in vscode terminal it shows that symbol as expected. so even i am not sure where the actual problem is in font or in wsltty?

**Comment by sagarrabadiya** [comment]
also with same font, terminus emulator or hyperterm shows that character as expected although other characters missing,
https://github.com/Eugeny/terminus/releases

check screenshot of that character
![1](https://user-images.githubusercontent.com/5405403/47143252-5a0c5680-d2e2-11e8-88a8-9ebd3defb0f1.png)

**Comment by sagarrabadiya** [comment]
can you suggest possible solution for this?

**Comment by mintty** [comment]
No, I was hoping someone could take up the challenge and craft a patch.

**Comment by rayjoy** [comment]
I meet this problem today。Is there someone who has solved it？

**Comment by mintty** [comment]
Actually, the arrow reported above, `➜`, is a Dingbats symbol, and you cannot really expect good font coverage of it, especially if font fallback is involved.
Try `➞` or `→` instead.

**Comment by mintty** [comment]
Grooming old issues; meanwhile there have been two potentially related changes in mintty:
  * Glyph checking (OSC 7771) considers FontChoice. (3.1.0, only if you actively determine the glyph)
  * Support alternative font choice for symbols and pictographs (#892). (3.0.3)
  * Script-specific secondary font choice (#580, #821, #883). (3.0.2, option FontChoice)

Can this issue be close?

**Comment by sagarrabadiya** [comment]
please don't mind but I have moved to windows terminal so if the font choice is fixed then ues certainly this issue can be closed. :)
