### ISSUE TITLE
How can I add "open with vim" to context menu?

### ISSUE THREAD

**Issue by fountainer** [mintty/wsltty#131]
[wsl-terminal](https://github.com/goreliu/wsl-terminal)  provides tool that can add "open with vim". How can I do this with `wsltty`?

**Comment by fountainer** [comment]
> [wsl-terminal](https://github.com/goreliu/wsl-terminal) uses a AutoHotKey script [open-wsl.ahk](https://github.com/goreliu/wsl-terminal/blob/master/src/open-wsl.ahk). See these 5 lines:
> 
> ```ahk
> mintty_path = "%A_ScriptDir%\bin\mintty"
> mintty_base = %mintty_path% --wsl --rootfs=// --configdir "%A_ScriptDir%\etc" -i "%icon_path%"
> wslbridge_base = -e /bin/wslbridge %distro_option% -e SHELL="%shell%" -e LANG
> Run, %mintty_base% %mintty_options% -t "%arg%" %wslbridge_base% -t ./"%filename%"
> ```
> 
> You can make a shortcut with the path of wsltty.exe in AppData folder. Or add the path in registry which opens a file in a directory.

I do not understand those 5 lines. I know how to add "open with vim" for `gvim.exe`, setting the `command` to `D:\software\vim\gvim.exe --remote-silent "%1"` in registry. However, I don't know which path should I add to use vim on WSL.

**Comment by nickjj** [comment]
Here's a step by step guide on getting an "Open with Vim" for files using `wsltty` without needing AHK:

https://nickjanetakis.com/blog/launching-wsl-programs-from-a-right-click-windows-menu

**Comment by Biswa96** [comment]
@nickjj I would suggest to add https://mintty.github.io/mintty.1.html link for the option details in your blog.
