### ISSUE TITLE
Copy/paste doesn't work properly when changing prompt colors

### ISSUE THREAD

**Issue by olivierpons** [mintty/wsltty#134]
Open a prompt, try to do this:

- type this code: `export PS1="\e[1;30m-30-\e[m >"`
- copy it with your mouse (select the code + copy it (I have auto-copy when I select with the mouse enabled))
- close the prompt
- open a brand new prompt
- immediately paste it (SHIFT INS)
- type "HOME" key and "END" key, you'll see the cursor go to logical positions (start and end of the code)
- now press ENTER
- you prompt changes the colors
- immediately paste it (SHIFT INS)
- type "HOME" key and "END" key, you'll see the cursor go to *illogical* positions (offset problem)

This means if I apply colors to the prompt I can't copy/paste + change my copied code...

**Comment by willpower232** [comment]
Your PS1 seems to also produce similar results in real bash (tried in Ubuntu) so it sounds like your specific prompt does funny things to bash(?)

**Comment by olivierpons** [comment]
It should just change the colors of the prompt (and that's what it does actually). Do you think it does something else we dont see?

**Comment by mintty** [comment]
Your prompt is broken. You need to enclose escape sequences in pairs of `\e[` and `\e]` or you'll have that offset problem. Not a mintty issue, as Will observed.

**Comment by mintty** [comment]
Sorry, should have been `\[` and `\]`. Fixing above. Read the bash manual.

**Comment by olivierpons** [comment]
I'm sorry you're right, I should take some time to read the bash manual. Sorry for that.

**Comment by willpower232** [comment]
I had no idea this was a thing. FWIW my PS1 ends in a newline which I presume resolves everything...

**Comment by mintty** [comment]
Admittedly, the bash manual is not very clear about the importance of using the escape embedding of non-printing characters in order to enable bash (or rather readline) to maintain its proper column position.
In tcsh, it's `%{` and `%}`.
