### ISSUE TITLE
environment variables to be passed into WSL

### ISSUE THREAD

**Issue by goreliu** [mintty/wsltty#14]
- A brief description

`/init cmd /C set` contains too few environment variables, some softwares run failed, like `shutdown`. In bash.exe, everything is OK.

```
$ /init shutdown
The system could not find the environment option that was entered.(203)

$ /init cmd /C 'set COMPUTERNAME=MY-PC & shutdown'
Usage: shutdown ...
```

And without `TMP` variable, some softwares run failed.

```
$ /init cmd /C set
COMSPEC=C:\WINDOWS\System32\cmd.exe
PATH=C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0;C:\WINDOWS\SYSTEM32;C:\WINDOWS;%LOCALAPPDATA%\MICROSOFT\WINDOWSAPPS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\mine\app\0misc\bin;C:\Users\goreliu\AppData\Local\Microsoft\WindowsApps
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.JS;.WS;.MSC
PROMPT=$P$G
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
WINDIR=C:\WINDOWS
```
- Your Windows build number

```
14951.1000
```
- Steps / All commands required to reproduce the error from a brand new installation

```
/init shutdown
```

https://github.com/Microsoft/BashOnWindows/issues/1257

**Comment by mintty** [comment]
See my comment in the WSL issue. I suggest you reopen it.

**Comment by mintty** [comment]
So you are effectively asking to transfer all environment variables to WSL.
Have you tested whether that's not already the case, perhaps? What if you call `wsl.bat` after setting a variable?

**Comment by goreliu** [comment]
I will test it later.

**Comment by mintty** [comment]
@rprichard `wslbridge` does not seem to take over the environment to WSL. Could that be added?

**Comment by rprichard** [comment]
wslbridge has an `-E` option that transfers explicitly listed variables.  (The syntax is either `-E VAR` to transfer `VAR` or `-E VAR=VAL` to set `VAR` to `VAL`.)  It doesn't currently have a way to copy all the environment variables.

FWIW: When I last checked, Microsoft's `bash.exe` adapter didn't copy anything.  If `wslbridge` did copy all the variables, I'd have a few questions about the behavior:

(1) Does wslbridge unset variables that weren't set on the Cygwin side?
(2) Maybe wslbridge would only set variables that weren't already set on the WSL side?
(3) Are certain variables blacklisted?  (e.g. PATH, HOME, TMPDIR, others?)

**Comment by goreliu** [comment]
@rprichard There are two kind of variables: WSL variables (wslbridge-backend need them) and Windows variables (bash.exe need them).

**Comment by goreliu** [comment]
@mintty 

```
c:\Users\goreliu\AppData\Local\wsltty>bash
[goreliu@my-pc wsltty]$ /init cmd /C set | wc -l
39
[goreliu@my-pc wsltty]$
```

```
c:\Users\goreliu\AppData\Local\wsltty>wsl
c:\Users\goreliu\AppData\Local\wsltty>

In mintty ...

[goreliu@my-pc wsltty]$ /init cmd /C set | wc -l
7
[goreliu@my-pc wsltty]$
```

**Comment by rprichard** [comment]
Oh, I see.  `wslbridge` probably just needs to call to `cygwin_internal(CW_SYNC_WINENV)`, like [winpty does](https://github.com/rprichard/winpty/blob/e60ef0101aebe6955a31e16c143569002f38b9e1/src/unix-adapter/main.cc#L349).

**Comment by mintty** [comment]
Ah, yes, that sounds like a good idea.

**Comment by mintty** [comment]
Updated to wslbridge 0.2.1 with wsltty 0.7.0.
