### ISSUE TITLE
Prompt colouring

### ISSUE THREAD

**Issue by gallwood** [mintty/wsltty#140]
Hi,

Not exactly a problem, but...

Is there a way of having the shell prompt (username@machine) a dirrent colour to the rest of the command line? Much like the standard wsl bash shell prompt?

Regards

Graham

**Comment by Biswa96** [comment]
Use `PS1` environment variable.

**Comment by mintty** [comment]
See `man bash`, section PROMPTING. Don't forget to embed escape sequences in `\[`...`\]`. See also #134.
This is a bash issue, not related to mintty.

**Comment by gallwood** [comment]
Ah, I see. I'm a bit new to wsl :)

Interesting, if I invoke the bash shell from a windows command prompt then the prompt is coloured. If I start the bash shell through wsltty it is not.

I edited the .bashrc file in ~ and uncommented the force_color_prompt=yes variable.

Thanks for your patience.

**Comment by mintty** [comment]
WSL in windows console is not coloured for me. You may have configured something already. Without any information about your environment, not even the WSL distribution, it is not possible to analyse this remotely.

**Comment by LuKePicci** [comment]
I have the same issue, the prompt is coloured as per bash settings, and in fact when I open up a WSL console by either the default terminal emulator or the terminal emulator inside VS Code it works. However it is not when opened from WSLtty. Apart from the prompt, everything else appear coloured as expected.

My WSL distribution is the standard "ubuntu" package from the store, installed before 18.04 release, I never updated from 16 to 18. and it is not one of the available version specific packages currently availabe as "ubuntu 16.04" and "ubuntu 18.04" respectively.

**Comment by Biswa96** [comment]
Which Windows 10 version do you use? Can you do a test? Create a user with `adduser` command, log in that user in wsltty, can you see the prompt colored text?

**Comment by LuKePicci** [comment]
@Biswa96 created a new testcolor user from standard terminal launching ubuntu.exe with:
`sudo adduser testcolor`
then launched wsl.bat, logged into as testcolor with:
`sudo login `
it logged in as testcolor but PS1 still gets set to the uncoloured prompt

I also added an `echo coloring: $color_prompt` in .bashrc of my main user immediately before it performs color support checking, and when I launch wlstty it shows that variable is empty, while it gets set to yes in both wsl default terminal and VS code built-in one. Seems like it gets set from upstream, maybe by the terminal emulator itself.

@mintty probably this will clarify what you were asking for

```
# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi
echo coloring: $color_prompt
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\$
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt
```

**Comment by LuKePicci** [comment]
I think I've found the culprit, seems like $TERM is "xterm" in mintty, and "xterm-256color" in the working ones.

**Comment by LuKePicci** [comment]
So it is just a matter of default mintty settings, it has "xterm" where the default wsl one exposes itself as "xterm-256color". Now works as expected.
