### ISSUE TITLE
Getting a login shell in Ubuntu 18.04 with 1.9.6 and sourcing .bashrc

### ISSUE THREAD

**Issue by rcarmo** [mintty/wsltty#143]
Just what the title says. Am currently going through all of my shortcuts and adding `-l` options, and nothing works, which means I have to source my (extensive) `.bashrc` manually.

**Comment by mintty** [comment]
The property of being a login shell does not mean it sources .bashrc but that it sources .profile in addition. Does it? How does native WSL invocation compare?

**Comment by rcarmo** [comment]
In addition?

Hmmm. I just "fixed" this by sourcing `.bashrc`  in `.bash_profile`, which shouldn't be necessary. Native WSL invocation developed the same issue, apparently, which leads me to believe some update did this.

I suggest the issue is kept open for a few days so that people can find it and (hopefully) provide us with more data points.

**Comment by mintty** [comment]
Added "question" label because it's a WSL configuration issue. Could also be closed.

**Comment by schmic** [comment]
@rcarmo Do you have a ~/.profile and if so whats in there?
My .bashrc gets sourced there (by default) on a fresh Ubuntu 18.04.
