### ISSUE TITLE
bluescreen when starting wsltty

### ISSUE THREAD

**Issue by schlichtanders** [mintty/wsltty#144]
Now I always get bluescreens when I start wsltty. It still worked a couple of weeks ago, don't know what changed, maybe a windows update. 

![20190123_095027](https://user-images.githubusercontent.com/4255480/51594615-1e8eb300-1ef5-11e9-8009-5f8c8689cffa.jpg)

I updated ubuntu subsystem by running `lxrun /uninstall` and `lxrun /install` which installed Ubuntu 16.04.2 LTS
and updated wsltty to current version 1.9.6 but still same blue screen
My windows version: 10.0.15063 Build 15063

EDIT: executing normal bash ubuntu wsl still works

**Comment by schlichtanders** [comment]
Thanks for inspecting further. I guess the McAffee refers to the disk encryption on my laptop.  It only happened so far with wsltty. 

If someone has an idea what might be the important interaction between disk encryption and wsltty, any help is highly welcome!

**Comment by Biswa96** [comment]
@schlichtanders First upgrade your Windows OS. WSL would changed heavily since build 15063 i.e. `lxrun.exe` is history. If you also see this error in latest Windows 10 release contanct McAfee.

**Comment by schlichtanders** [comment]
thank you very much for your support!
I am closing this then
