### ISSUE TITLE
What is -~ mean

### ISSUE THREAD

**Issue by doggy8088** [mintty/wsltty#146]
I saw `%LOCALAPPDATA%\Microsoft\WindowsApps\WSL~.bat` file that has a command below:

```sh
%LOCALAPPDATA%\wsltty\bin\mintty.exe -i "%LOCALAPPDATA%\wsltty\wsl.ico" --WSL= --configdir="%APPDATA%\wsltty" -~  
```

What's the `-~` mean here?

**Comment by Biswa96** [comment]
Detailed explanation in this page: https://mintty.github.io/mintty.1.html
