### ISSUE TITLE
--wsl doesn't works when open wsltty using Windows Shortcuts

### ISSUE THREAD

**Issue by doggy8088** [mintty/wsltty#148]
If I run `%LocalAppData%\wsltty\bin\mintty.exe --WSL --configdir="%AppData%\wsltty" -~ --wsl` under Command Prompt.  The wsltty will open and I can drag a file from explorer to wsltty terminal window, the file path will output.

If I run the same command but using Windows Shortcut, I can't drag & drop file into wsltty terminal.  No file path will output in the terminal.

**Comment by mintty** [comment]
Note: `--WSL` implies `--wsl`, so the latter option is not necessary.
What's the command line in your Windows shortcut; did you modify it?

**Comment by doggy8088** [comment]
After I remove `--wsl` option, problem solved.  I do modified when I study all the command line options.

**Comment by mintty** [comment]
This is a bit weird; `--wsl` should actually be redundant with `--WSL` and not spoil it. I may check this out if I find time, but maybe not, as the problem's gone:)
