### ISSUE TITLE
Clipboard managers aren't able to insert text

### ISSUE THREAD

**Issue by nickjj** [mintty/wsltty#150]
Hey,

Windows 10 has a built in clipboard manager that lets you manage multiple clipboard items. There's also better clipboard managers such as the [Ditto tool](https://ditto-cp.sourceforge.io/). It lets you search, retrieve and paste in clipboard items copied in the past.

In both cases, when you try to insert text into wsltty using them, you wind up with either no output (it's like the terminal absorbs the output) or  you get literally `^V` as output depending on how you decide to insert the text (through a hotkey or clicking the clipboard item with the mouse). I'm guessing it's because these tools send `CTRL + V` in the case where `^V` ends up as the output.

Is there any way this can be worked around without patching the clipboard manager tool? Most of them aren't open source (although Ditto is), so that's not really possible anyways.

**Comment by mintty** [comment]
Duplicate of #139; this has been fixed in 1.9.6 already, at least for the Windows clipboard history.
Which version do you run? Please check whether the fix also works for Ditto.

**Comment by mintty** [comment]
What's the purpose of that crazy tool, actually? It seems to be able to paste into one application only, not the current foreground window.

**Comment by mintty** [comment]
These tools send two keyboard events to the target application: Control and V.
Windows clipboard history sends the V at least in a way that can be distinguished from a true V: it does not send a "scancode" (it's 0 in the message), so a workaround could be applied for it.
If the key messages are indistinguishable from "native" keyboard input, it is impossible for an application to handle this case. It's a Ditto bug.

**Comment by nickjj** [comment]
I am using 1.9.6 according to the About menu. Ditto does not work (it fails with the description supplied in the issue).

The purpose of the tool allows you to save a history of your clipboard and then be able to search through it and paste an item from that history into any window you want. It saves a lot of time.

It works in every other application on Windows except for wsltty (and also the `ubuntu.exe` too).

**Comment by mintty** [comment]
My question about its purpose should address the issue that Ditto, by default, only pastes into the same application that copied text to the clipboard before. That's a restriction I'd normally not expect from a clipboard.

Anyway, about the pasting: I've explained above why it does not work; note that a terminal cannot simply interpret Control+V as Paste because Control+V is a perfectly valid terminal input, a control character, that terminal users expect to be available.

The workaround mintty applies for the Windows clipboard history would apply if Ditto sent its key events in the same way. Please report that as an issue to Ditto.

**Comment by nickjj** [comment]
> My question about its purpose should address the issue that Ditto, by default, only pastes into the same application that copied text to the clipboard before. That's a restriction I'd normally not expect from a clipboard.

Ditto isn't limited like that. If I copy text from this Github issue textarea, it gets placed into Ditto's multi-clipboard manager and then I can paste it into my IRC client, notepad, VSCode, Emacs or anything else.

It works just like the normal clipboard in that regard, except it gives you multiple items that you can search through and pick. It's comparable to the Windows 10 clipboard manager except it's a lot better (searchable history which is essential, allows you to strip formatting, etc.).

Is there no way to allow mintty to accept CTRL + V as a paste action as an option?

Ditto's source code is available at https://sourceforge.net/p/ditto-cp/ditto/ci/master/tree/, but what exactly would you report as a bug?

**Comment by nickjj** [comment]
I figured it out. I set `^+{VKEY86}` as the paste string and now it works. Ditto is successfully pasting to wsltty and it also works in every other Windows app too.

**Comment by mintty** [comment]
> ^+{VKEY86}

How did you find that solution and where do you configure it in Ditto?

**Comment by nickjj** [comment]
I brute forced it. I looked at the keyboard and then thought long and hard on what type of symbols I've seen in the past to identify CTRL, Shift and ALT keys. The first one that came to mind was `+`, and it worked.

It's in the advanced options under general settings. It's the "default paste string".

The only problem is not all apps support that paste code. Fortunately browsers allow ctrl + shift + V to paste. Between the browser and the terminal environment that's where I spend 99% of my time. For apps that don't accept it, the normal Windows ctrl + V would work (bypassing Ditto completely).

**Comment by mintty** [comment]
See also option `CtrlExchangeShift` and issue mintty/mintty#817.

**Comment by nickjj** [comment]
Thanks, but I guess in that case, if you set `CtrlExchangeShift=yes` then `CTRL + C` would copy text instead of killing a foreground process?

**Comment by mintty** [comment]
Yes, that's why I was very hesitant against introducing that option (as seen in the referred and further issues). But using the user-definable keys feature, you could actually setup mintty to keep Control+C and remap Control+V to paste.
Maybe I'll report an issue to Ditto; it's not necessary to check the code and deliver a solution already to do that.

**Comment by samegek** [comment]
[Ditto / Discussion / Help: Change paste key (Ctrl+V) to Shift+Insert](https://sourceforge.net/p/ditto-cp/discussion/287511/thread/4ff4f272/?limit=25)
change regedit 
change paste key to shift+ins
![image](https://user-images.githubusercontent.com/14978256/181445365-1d74bb15-31d0-4354-96c6-c7d054b44c3f.png)

**Comment by mintty** [comment]
Thanks for the hint. To clarify, this is about configuring another application to tweak its paste injection to match mintty default.

**Comment by mintty** [comment]
Did you submit them an issue, following my suggestion above (https://github.com/mintty/wsltty/issues/150#issuecomment-462212774) how to enable pasting without extra configuration?
