### ISSUE TITLE
wsltty-1.9.6 on win10 1809  report  wslbridge segmenation fault

### ISSUE THREAD

**Issue by jeffery9** [mintty/wsltty#152]
wsltty 1.9.6
windows 10 1809 [17763.253]

when run wsl terminal, it report  wslbridge segmenation fault, see 
![image](https://user-images.githubusercontent.com/1404460/52908423-a5df0480-32b0-11e9-97a5-856e36c58875.png)

**Comment by mintty** [comment]
This has not been reported by anyone else. The only suggestion I can make right now, although somewhat helpless, is to reinstall wsltty, maybe also try an older version.

**Comment by mintty** [comment]
Assuming this does not occur with newer versions, and nobody confirmed the issue anyway, I'm closing it.
