### ISSUE TITLE
wslbridge error sending signal 11

### ISSUE THREAD

**Issue by amildahl** [mintty/wsltty#153]
I'm noticing a strange error that's cropped up when I leave a session open.  Though I don't imagine it matters, the session is running a tmux session ssh'd to machines two levels deep.  The errors were occasional after about 6 hours.  After letting it sit, idle, overnight for ~9 hours, it won't stop spewing:

> 1458507086 [sig] wslbridge 10924 sig_send: error sending signal 11, pid 10924, pipe handle 0xE0, nb 0, packsize 176, Win32 error 0

I'm running wsltty 1.9.6, installed through chocolatey, on Windows 10.  It's running in Cmder with the following Task:

> set "PATH=%ConEmuBaseDirShort%\wsl;%PATH%" & %LOCALAPPDATA%\wsltty\bin\mintty.exe --wsl -o ThemeFile="%LOCALAPPDATA%\wsltty\themes\MinttyCampbell" -o Locale=C -o Charset=UTF-8 /bin/wslbridge --distro-guid 7fd07c9d-50e3-414a-9115-ee17cd08367c -C~ -t /bin/bash

I haven't done any additional configuration, as far as I can remember (I only set this up last night).  I had two terminals open and it only happened on the one (the second terminal wasn't in a tmux session and was just ssh'd into a machine)

It's not a huge deal as I can just detach my tmux session and open a new terminal, but I thought I'd throw it out there in case it keeps cropping up.  Thanks!

**Comment by mintty** [comment]
wsltty in cmder‽ Wow...
Please provide a "minimal test case" - a really helpful concept in open source debugging.
I.e., without cmder, without tmux. If it still happens, it sounds like a wsltty issue. Then report there please.

**Comment by mintty** [comment]
Marked invalid for intricate entangled test setup.

**Comment by Biswa96** [comment]
Why do you run the whole wsltty (= wslbridge + mintty) in ComEmu? ComEmu itself has wslbridge.exe.

**Comment by rustyscottweber** [comment]
> 
> 
> Why do you run the whole wsltty (= wslbridge + mintty) in ComEmu? ComEmu itself has wslbridge.exe.

1. Because windows made it and it sucks....
2. Because windows tries to constantly outsmart me, the user, at every turn and it sucks.
3. I wish I could use CentOs, but I need certain libraries that will only run on windows because it sucks.
Shall I continue?

**Comment by mintty** [comment]
It sounds like a wslbridge issue (not wsltty, fixed in my previous comment). Maybe report there?
However, if it still only occurs in ConEmu, it could be some weird interworking effect that probably nobody will feel in charge of...

**Comment by rustyscottweber** [comment]
Filed the issue with what I believe is the wslbridge probject.
https://github.com/rprichard/wslbridge/issues/41

**Comment by mintty** [comment]
Actually, as signal 11 is SIGSEGV, is this related to #152?

**Comment by mintty** [comment]
Released 3.0.5 with changed gateway.
