### ISSUE TITLE
After pressing CTRL-S, terminal window no longer accepts input.

### ISSUE THREAD

**Issue by the-neo-zeed** [mintty/wsltty#155]
After pressing CTRL-S, the terminal no longer accepts input. The application doesn't appear to be frozen because the cursor is still blinking and the options are accessible and can be saved. There doesn't seem to be a way to get the terminal working again once this occurs without shutting it down and restarting it.

- wsltty 1.9.6
- Windows 10 1809

**Comment by the-neo-zeed** [comment]
My mistake... I now see that CTRL-S stops terminal output and CTRL-Q restarts it.

**Comment by the-neo-zeed** [comment]
Closing...

**Comment by the-neo-zeed** [comment]
For anyone wondering how to prevent this, which allows CTRL-S and CTRL-Q to work with terminal applications, run the following (per the mintty docs) from the terminal bash prompt.

```bash
stty -ixon
```

**Comment by mintty** [comment]
> CTRL-S stops terminal output and CTRL-Q restarts it.

And this is handled on the tty interface level. The terminal emulator is not involved in this feature.
