### ISSUE TITLE
nvim 0.4.0 prerelease can not draw vertical split separator

### ISSUE THREAD

**Issue by epheien** [mintty/wsltty#159]
windows 10 1809
wsltty 2.9.6
ubuntu 18.04
NVIM v0.4.0-430-g8698830cb

Reproduction
```
nvim -u NONE
:vsp<CR>
```

but vim works fine

and I use wsl-terminal, nvim works fine.

**Comment by mintty** [comment]
Please provide a reproducible test case, i.e. one that demonstrates the issue independently from nvim. A screen log (not screenshot) will be helpful.

**Comment by epheien** [comment]
How to get screen log

**Comment by mintty** [comment]
'script' is a Linux tool, or use mintty logging feature.

**Comment by Biswa96** [comment]
@epheien Just express what you are doing.

**Comment by mintty** [comment]
In your wsltty config file (`config` in the Windows folder %LOCALAPPDATA%/wsltty or %APPDATA%/wsltty), add option
`Log=C:\Temp\mintty%d.log`
(use an existing directory on your system, Windows path syntax suggested to better find the wsltty log file).
Then, in wsltty, Control+right-mouse-click to open the extended context menu, and select "Log to File".
Produce the issue into the file (stop logging while the effect is visible, for better reproduction) and upload the file here.

**Comment by mintty** [comment]
Also check if it's the same as mintty/mintty#827, an old vim bug, and report it to vim/nvim, too.

**Comment by mintty** [comment]
I'm closing this issue as there is no indication of a bug.
