### ISSUE TITLE
Any ways to set zsh as default shell?

### ISSUE THREAD

**Issue by abcfy2** [mintty/wsltty#16]
I like to use `zsh`. On ubuntu I can use `chsh -s /bin/zsh` to set default shell to `zsh`, but how to set the default shell on `wsltty`?

**Comment by mintty** [comment]
wsltty simply passes /bin/bash to wslbridge in the shortcuts, the wsl*.bat scripts, and the context menu.
@rprichard: I don't know whether wslbridge actually needs a shell specified.
Since I don't have testing capabilities myself right now, please try to remove /bin/bash from your invocation. If that works, we can do without it.

**Comment by abcfy2** [comment]
Oh thanks. Change the shortcuts `/bin/bash` -> `/bin/zsh` works.

**Comment by mintty** [comment]
Thanks, so that would be your workaround.
But actually my question was whether it also works if you simply leave out the /bin/bash or /bin/zsh parameter completely.

**Comment by abcfy2** [comment]
No. Leave out `/bin/bash` or `/bin/zsh` will use `/bin/bash` as default.

**Comment by mintty** [comment]
Even if you change the default shell in WSL as indicated in your original comment?
How does your shell look like in /etc/passwd?

**Comment by abcfy2** [comment]
Seems that WSL doesn's support set default shell. See: https://github.com/Microsoft/BashOnWindows/issues/846

**Comment by antonioyon** [comment]
I've gotten it to work by putting `exec zsh` in my `.bashrc`. It's a bit hacky but you can wrap a test for interactive login around it and it's just as good.

**Comment by mintty** [comment]
Added section "Shell selection" to project page README.

**Comment by mintty** [comment]
Meanwhile it is possible to invoke WSL with the configured default shell, using the wsl.exe wrapper.

**Comment by mintty** [comment]
Released 1.8.0 which does not set a preference to /bin/bash anymore.

**Comment by ForsakenHarmony** [comment]
I'm still getting bash every time?

**Comment by mintty** [comment]
Maybe you'd need to update your shortcuts. If you use the previous shortcuts, you'll get the previous behaviour.
Please try the "WSL Terminal" shortcut (it may be new, you can check the target in the properties first). Remove non-working WSLtty desktop shortcuts and copy fresh ones from the Start Menu or reinstall.

**Comment by ForsakenHarmony** [comment]
I'm pretty sure my initial install was after that update

**Comment by mintty** [comment]
Right, actually 1.8.0 removes explicit invocation of /bin/bash from the WSLtty shortcuts, but support from wslbridge is still needed to make it work, see rprichard/wslbridge#17.

**Comment by mintty** [comment]
Closing for the more generic #86.
