### ISSUE TITLE
Detaching from suspended jobs leaves the terminal windows open

### ISSUE THREAD

**Issue by Po-wei** [mintty/wsltty#160]
I am not sure if it is a mintty or wslbridge bug.

How to reproduce:
1. Run a nonstop app (e.g. htop)
2. hit ^Z  to pause
3. hit ^D twice to leave.
4. you get a non-active shell with wslbridge running.

Compare to native WSL,
it close immediately.

**Comment by mintty** [comment]
Reproduced to stall in Ubuntu, kali-linux, legacy Bash-on-Windows if run from Start menu, but works in openSUSE-42.
Always works if mintty is run from cygwin (with --WSL option).

**Comment by mintty** [comment]
Released 3.0.5. Please recheck.

**Comment by mintty** [comment]
Released 3.0.6.
