### ISSUE TITLE
How do I run the 'WSL Generate Shortcuts' command?

### ISSUE THREAD

**Issue by systemovich** [mintty/wsltty#162]
On Windows 10, in Powershell as administrator, I ran `choco install --force -y wsltty`, and got the following output:

> Chocolatey v0.10.10
> [Pending] Removing incomplete install for 'wsltty'
> Installing the following packages:
> wsltty
> By installing you accept licenses for the packages.
> 
> wsltty v1.9.8 (forced) [Approved]
> wsltty package files install completed. Performing other installation steps.
> C:\ProgramData\chocolatey\lib\wsltty\tools\wslttyinstall\cygwin-console-helper.exe.ignore
> C:\ProgramData\chocolatey\lib\wsltty\tools\wslttyinstall\dash.exe.ignore
> C:\ProgramData\chocolatey\lib\wsltty\tools\wslttyinstall\mintty.exe.ignore
> C:\ProgramData\chocolatey\lib\wsltty\tools\wslttyinstall\regtool.exe.ignore
> C:\ProgramData\chocolatey\lib\wsltty\tools\wslttyinstall\wslbridge.exe.ignore
> C:\ProgramData\chocolatey\lib\wsltty\tools\wslttyinstall\zoo.exe.ignore
> Make sure to run 'WSL Generate Shortcuts' to complete the update for your user account.
>  The install of wsltty was successful.
>   Software install location not explicitly set, could be in package or
>   default install location if installer.
> 
> Chocolatey installed 1/1 packages. 
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

The output includes the statement **"Make sure to run 'WSL Generate Shortcuts' to complete the update for your user account."** How do I run this command? I tried in Powershell `WSL Generate Shortcuts`, but got this output:

> WSL : /bin/bash: Generate: command not found
> At line:1 char:1
> + WSL Generate Shortcuts
> + ~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (/bin/bash: Generate: command not found:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError

**Comment by mintty** [comment]
'WSL Generate Shortcuts' might refer to the Start Menu entry WSLtty → 'configure WSL shortcuts'.
But I do not maintain the choco package.

**Comment by systemovich** [comment]
@mintty, thanks! I was searching "WSLtty" and "terminal" and other things by typing in the Start Menu. Now I scrolled down the alphabetical list of items in the Start Menu, then found "WSL Generate Shortcuts". It worked, thanks!

**Comment by mintty** [comment]
Actually, that must be an item installed by the choco package. In the plain wsltty package, it's the sub-menu shortcut as I described.

**Comment by DavidAntliff** [comment]
@systemovich "It worked" - what exactly does that mean? Is it meant to create new shortcuts somewhere? As per my installation today, it does something (console window pops up briefly) but no new shortcuts appear.

**Comment by DavidAntliff** [comment]
When I run the `install.bat` pointed to by the "WSL Generate Shortcuts" item in my Start Menu, I get the following:

```
C:\ProgramData\chocolatey\lib\wsltty\tools\wslttyinstall>C:\ProgramData\chocolatey\lib\wsltty\tools\wslttyinstall\install.bat
A subdirectory or file C:\Users\david\AppData\Local\wsltty already exists.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
Could Not Find C:\Users\david\AppData\Local\wsltty\bin\*.old
A subdirectory or file C:\Users\david\AppData\Local\wsltty\bin already exists.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file C:\Users\david\AppData\Local\wsltty\usr\share\mintty\lang already exists.
        1 file(s) copied.
A subdirectory or file C:\Users\david\AppData\Local\wsltty\usr\share\mintty\themes already exists.
        1 file(s) copied.
A subdirectory or file C:\Users\david\AppData\Local\wsltty\usr\share\mintty\sounds already exists.
        1 file(s) copied.
A subdirectory or file C:\Users\david\AppData\Local\wsltty\usr\share\mintty\info already exists.
        1 file(s) copied.
A subdirectory or file C:\Users\david\AppData\Local\wsltty\usr\share\mintty\icon already exists.
        1 file(s) copied.
        1 file(s) copied.
The directory or file cannot be created.
Error occurred while processing: Menu\Programs\WSLtty.
The system cannot find the path specified.
The syntax of the command is incorrect.
The syntax of the command is incorrect.
The syntax of the command is incorrect.
The syntax of the command is incorrect.
The syntax of the command is incorrect.
The system cannot find the path specified.
Zoo:  WARNING:  Archive header failed consistency check.
Zoo:  de.po          -- skipped
Zoo:  en.po          -- skipped
Zoo:  en_US.po       -- skipped
Zoo:  es.po          -- skipped
Zoo:  fr.po          -- skipped
Zoo:  ja.po          -- skipped
Zoo:  nb.po          -- skipped
Zoo:  pt_BR.po       -- skipped
Zoo:  ru.po          -- skipped
Zoo:  zh_CN.po       -- skipped
Zoo:  zh_TW.po       -- skipped
Zoo:  WARNING:  Archive header failed consistency check.
Zoo:  dracula        -- skipped
Zoo:  flat-ui        -- skipped
Zoo:  html           -- skipped
Zoo:  mintty         -- skipped
Zoo:  nord           -- skipped
Zoo:  rosipov        -- skipped
Zoo:  vga            -- skipped
Zoo:  windows10      -- skipped
Zoo:  xterm          -- skipped
Zoo:  WARNING:  Archive header failed consistency check.
Zoo:  BOING.WAV      -- skipped
Zoo:  README.md      -- skipped
Zoo:  ambient-drip-lo.wav -- skipped
Zoo:  ambient-drop.wav -- skipped
Zoo:  ambient-glass.wav -- skipped
Zoo:  ambient-splash.wav -- skipped
Zoo:  ambient-swoosh.wav -- skipped
Zoo:  ambient-uncork.wav -- skipped
Zoo:  percussive-bongo-hi.wav -- skipped
Zoo:  percussive-bongo-lo.wav -- skipped
Zoo:  percussive-gong.wav -- skipped
Zoo:  percussive-knock.wav -- skipped
Zoo:  percussive-synthkick-lo.wav -- skipped
Zoo:  resonant-flute.wav -- skipped
Zoo:  resonant-organ.wav -- skipped
Zoo:  resonant-reverb.wav -- skipped
Zoo:  resonant-twang.wav -- skipped
Zoo:  synthetic-bass.wav -- skipped
Zoo:  synthetic-gib.wav -- skipped
Zoo:  synthetic-honk.wav -- skipped
Zoo:  synthetic-intruder.wav -- skipped
Zoo:  synthetic-rave.wav -- skipped
Zoo:  synthetic-select.wav -- skipped
Zoo:  synthetic-spike.wav -- skipped
Zoo:  synthetic-sproing.wav -- skipped
Zoo:  synthetic-square.wav -- skipped
Zoo:  vocal-boo.wav  -- skipped
Zoo:  vocal-hah.wav  -- skipped
Zoo:  vocal-yip.wav  -- skipped
The system cannot find the path specified.
The system cannot find the file specified.
A subdirectory or file C:\Users\david\AppData\Roaming\wsltty\lang already exists.
A subdirectory or file C:\Users\david\AppData\Roaming\wsltty\themes already exists.
A subdirectory or file C:\Users\david\AppData\Roaming\wsltty\sounds already exists.
bin/dash: 0: Can't open C:UsersdavidAppDataLocalwsltty\config-distros.sh
```

Looks like a bunch of errors. The "already exists" ones may be because I've run it a few times since first clicking on it (even after removing and reinstalling wsltty via choco), but there are a couple that concern me, especially the consistency check failures and the final line of output.

**Comment by mintty** [comment]
"It worked" means it worked at the time. Broken in a later release, now duplicate of #232.

**Comment by mintty** [comment]
Released installer 3.1.4.2, please check.

**Comment by DavidAntliff** [comment]
@mintty that worked for me - thank you. I did get a German-language dialog box pop up during the install, but I selected "Ja, alles" and it installed correctly (I am using English/NZ localisation).

**Comment by mintty** [comment]
The strange popup box: what else does it say and when does it appear?

**Comment by DavidAntliff** [comment]
It looks like it appears just after:

```
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y
```

![image](https://user-images.githubusercontent.com/11261038/78424681-a9f3fe80-76cb-11ea-9916-4dfa868ad2d6.png)

However the way I reproduced this is slightly unusual as I already had 3.1.4 installed:

```
$ choco uninstall wsltty
$ choco install --version 3.1.4
$ choco install --force --version 3.1.4.2
```

Looks like if I uninstall wsltty and then directly install 3.1.4.2, the dialog does not appear (well, actually, I see a dialog window very briefly flash up but I can't see what it says - might be the same one).

**Comment by mintty** [comment]
Thanks; so this is part of the choco installation.
