### ISSUE TITLE
No start menu icons installed in win10

### ISSUE THREAD

**Issue by Zhuanghq7** [mintty/wsltty#166]
I'm new user for wsltty, And this the first time I install wsltty 3.0.0. When installer say installed, but there only 4 files named "add to context menu", "add default to context menu", "configure WSL shortcuts" and "remove from context". And I find the only way I can start wsltty is open "add to context menu", and go to desktop and right click then finally choose start wsltty. But this is too complex and waste of time. How can I add a shortcut to my start menu or tast menu or anyway desktop? I think this should be created automaticly by the installer but it did not.

**Comment by Zhuanghq7** [comment]
fine, I run "configure WSL shortcuts" in powershell and then it creat everything I need. Congratulations. But I believe it should run when installer installing or give me a feedback that something error instead of just installed.

**Comment by mintty** [comment]
User preferences differ. Some users do not want shortcuts for all WSL distributions on their desktops. Many users particularly object against Explorer context menu entries installed automatically. So these are optional.
The installer installs shortcuts for all distributions that you have at the time of installing wsltty in your start menu. If you install another distro later, you may want to have a shortcut also. This is another use case for running these configuration scripts explicitly.
I will check how description can be improved to guide through these steps. Suggestions welcome.

**Comment by Zhuanghq7** [comment]
thanks

**Comment by mintty** [comment]
Reading again, apart from context menu entries, there should have been at least one desktop shortcut for the default WSL distribution, plus Start menu shorcuts for all distributions that you had deployed at the time of installing wsltty. Was that not the case?

**Comment by Zhuanghq7** [comment]
Thanks for your attentaion. But actually, the installer didn't create even one shortcut in my desktop. So at that moment I was confused.

**Comment by Zhuanghq7** [comment]
Im sure I already have an default WSL because after I install wsltty, I can open a wsltty window through right click on desktop and choose "start wsltty". Although, there is no any short on my desktop or start menu.

**Comment by mintty** [comment]
It could be that your %USERPROFILE% is configured so that its Desktop is not a subfolder but a Windows shortcut (e.g. pointing to another disk). That might be raising problems, at least that's what I see on one system.
Uploading a patch for `config-distros.sh`.

**Comment by Zhuanghq7** [comment]
OK, this may help the latecomer, thx :>

**Comment by SimonPilkington** [comment]
Your current approach is also not foolproof. Many user profile folders can be moved individually to arbitrary locations. (Including roaming AppData. See [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776911(v=vs.85).aspx).) If this is the case, your shortcut will end up in an unused folder.

Consider using something like [this](https://stackoverflow.com/questions/18629768/path-of-user-desktop-in-batch-files/34706178#34706178) instead.

**Comment by mintty** [comment]
The environment variables (e.g. %APPDATA%) should always point to the proper place, even if relocated.
Which one does not work for you?

**Comment by SimonPilkington** [comment]
My AppData is not relocated, but my Desktop is on a different disk, so there is no way to reach it via the %APPDATA% variable.

**Comment by mintty** [comment]
I had recently replaced "%USERPROFILE%\\Desktop" (which turned out not to work in some situations) by "%APPDATA%\\..\\Desktop\\", now this doesn't seem to work in other situations. Quite bothersome...
How about %Desktop%, actually, is that set properly for you?

**Comment by SimonPilkington** [comment]
%Desktop% is not a system variable unfortunately. The SO answer I linked above loads it from the registry.

**Comment by mintty** [comment]
I think I saw %Desktop% on every Windows system so far, without extra configuration. Is it set properly on your system?

**Comment by mintty** [comment]
Also, I see FOLDERID_Desktop in the same include file where FOLDERID_LocalAppData etc are defined.

**Comment by SimonPilkington** [comment]
I have access to three different Windows systems at the moment and none of them have %Desktop%. The FOLDERID_* variables are only defined in KnownFolders.h for use in code and are unrelated to environment variables. Only %AppData% and %LocalAppData% exist as environment variables to my knowledge.

**Comment by EmberQuill** [comment]
I don't have %DESKTOP% set on my system either (running Windows 10 1809 if that matters). I think the desktop location is only defined in the Registry as one of the values in the User Shell Folders key.

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders`

**Comment by mintty** [comment]
Changed config script.

**Comment by mintty** [comment]
Released 3.0.1.
