### ISSUE TITLE
wsltty 3.0.0 has wrong default directory name

### ISSUE THREAD

**Issue by Po-wei** [mintty/wsltty#167]
before this version, when I opened wsltty, the title bar shows ~
but now it just shows the parameters.
and cd 
![image](https://user-images.githubusercontent.com/17596021/57286815-b735f100-70e8-11e9-8e44-ba8492496b24.png)

**Comment by mintty** [comment]
There was no change. Maybe your WSL distribution has changed, not to set the title?
Please check your "$PS1" prompt setting.

**Comment by mintty** [comment]
It may happen if your .bashrc is not called (reproduced with a previous version). This is a peculiarity of WSL distributions. Change your .profile to make sure .bashrc is also called.

**Comment by mintty** [comment]
Mintty shall initialise the title to the WSL distribution name ("WSL" if default) rather than the command line.
Whether your WSL shell further updates the title to the respective directory name (or anything else) is out of scope of wsltty.

**Comment by mintty** [comment]
Released 3.0.1.
