### ISSUE TITLE
McAfee Virus Scan thinks there's a problem --

### ISSUE THREAD

**Issue by aabatpurdue** [mintty/wsltty#168]
```
5/28/2019	5:09:22 AM	"D:\Users\Public\Downloads\wsltty-3.0.1-install.exe"	"Real Protect-EC!57932D202662"	"1"
```

Log entry from McAfee Small Business Security Suite.  False positive?  Have similar entry for 3.0.0 but missed seeing it until now (:@{).

--  Thanks,
--    aabatpurdue

**Comment by GranoblasticMan** [comment]
I'm assuming it's a false positive; VirusTotal's been showing detections for pretty much all versions of wsltty from what I can tell. Here's the current 3.0.1:

https://www.virustotal.com/#/file/9ed94b1fdbadb7e2c0318f432a33e725a16beb4bae2252445c92888e362cdf09/detection

**Comment by aabatpurdue** [comment]
Actually, the VirusTotal listing is not necessarily complete as it does not include my variant of McAfee Virus Scan.

**Comment by GranoblasticMan** [comment]
A good point to bring up with VirusTotal, as more variety certainly helps! However, in this case, I think wsltty is safe enough, considering the few warnings that pop up are pretty generic.

**Comment by GranoblasticMan** [comment]
That being said, I can't blame anyone for being cautious, of course.

**Comment by aabatpurdue** [comment]
Ah, I had to cheat to get 3.0.1.2 installed - turn off McAfee, download, install, restart McAfee.  Did not find any whitelist but did find an "exclude" so that McAfee keeps its paws off.

Enough breath on this - closing.
