### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by saivert** [mintty/wsltty#17]
I'm trying out some of the themes from here https://github.com/iamthad/base16-mintty

Colors seem off to me for most of these.

![image](https://cloud.githubusercontent.com/assets/63738/21028167/30edc096-bd94-11e6-86f6-26b97165367c.png)

If you check the .pl and .sh files in the colored ls output above they are barely legible against the almost same color background. This is the case for most of the base16 themes.

**Comment by mintty** [comment]
I can only assess your report if you fully describe the "background", especially which colour setting is being used by ls (environment variable...). Also it might be useful to compare with another terminal. I am not aware of any colour deviation of mintty and one similar previous report turned out to be a mistake as well.

**Comment by saivert** [comment]
If you use the shell helper here: https://github.com/chriskempson/base16-shell the colors are ok but it seems to have the same effect as configuring wsltty to not show bold as color.

**Comment by mintty** [comment]
I cannot leave this issue open if you don't provide a test case. How do you set colours (and I mean *how* do you set them, not a link to some homepage), and what's the value of LS_COLORS?

**Comment by saivert** [comment]
Steps to reproduce:
1. Install Bash on Ubuntu on Windows
2. Install Base16 mintty themes
3. Load theme

Expect to see correct ls colors.

Meaning I don't set the LS_COLORS at all. They are default.
For reference they are:

LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:

**Comment by mintty** [comment]
You are still not providing a test case ("base16 mintty themes" - there are dozens of them).
Also please minimize a test case - which of the LS_COLORS settings affects the color you are complaining about?
And then, also describe what you would expect and why.

**Comment by mintty** [comment]
Assuming that colours are displayed as specified (dark blue by LS_COLORS and dark background by Theme), I'm closing the issue now.
