### ISSUE TITLE
System32 must be on PATH

### ISSUE THREAD

**Issue by jonatasmedeiros** [mintty/wsltty#172]
I don't know if this is default on Windows 10 (1903), but on my machine 'C:\Windows\System32' was not on PATH.

It turns out that config-distros.sh assumes that system32 is on PATH (for calling cmd).

If system32 is not on PATH, the installation of wsltty will not create the shortcuts to wsl. (It will also not give any error messages, so it took me a while to figure out what was wrong)

After adding system32 to PATH and running the installation again, it worked.

**Comment by mintty** [comment]
>  'C:\Windows\System32' was not on PATH

Quite unusual. Did you remove it?
Is any of SYSTEMROOT, COMSPEC, WINDIR set?

**Comment by jonatasmedeiros** [comment]
No, I did not remove it (maybe some program did, without my knowledge). Is it supposed to be there by default?

SystemRoot and windir are both set to 'C:\WINDOWS'.
ComSpec is set to 'C:\WINDOWS\system32\cmd.exe'.

The only folders that were in the PATH related to system32 were:
'%SystemRoot%'
'%SystemRoot%\System32\Wbem'
'%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\'
'%SYSTEMROOT%\System32\OpenSSH\'

but not system32 itself. I had to add '%SystemRoot%\System32' to the PATH to make the installation work.

I am really enjoying wsltty, by the way.

**Comment by mintty** [comment]
Does the installer initially start `install.bat` or does it need to be specified in `makewinx.cfg` as
`AppLaunched=%COMSPEC% /c install.bat`
Is %COMSPEC% set?

**Comment by jonatasmedeiros** [comment]
Well, the only file I have for installation is `wsltty-3.0.1.2-install.exe`, so I did not make any changes to `makewinx.cfg` (as I am not compiling from source).

**Comment by mintty** [comment]
Released 3.0.2.
