### ISSUE TITLE
Failed to run '/bin/bash'

### ISSUE THREAD

**Issue by vedantroy** [mintty/wsltty#174]
I used `scoop install wsltty`. When I launch mintty, I get the error
>Failed to run '/bin/bash': No such file or directory.

I don't know what's going on, but I suspect the issue is that my `bash` executable is located in `C:\Windows\system32\bash.exe`.

**Comment by mintty** [comment]
> When I launch mintty

How do you try to launch it? You are not supposed to start the mintty binary directly.

**Comment by mintty** [comment]
See https://github.com/mintty/wsltty#invocation
