### ISSUE TITLE
emacs magit shows black highlighting in wsltty+ssh, while ok in wsltty+mosh

### ISSUE THREAD

**Issue by duyanning** [mintty/wsltty#176]
wsltty+mosh
![a](https://user-images.githubusercontent.com/748776/61193260-f423f280-a6ec-11e9-8ed8-8b1f998a8b0f.jpg)

wsltty+ssh
![b](https://user-images.githubusercontent.com/748776/61193262-f5edb600-a6ec-11e9-9aa3-acafb8f6127c.jpg)

wsltty+local is the same as wsltty+ssh

**Comment by mintty** [comment]
A reproducible test case is needed. For example a screen log, i.e. a file that you can simply output to the terminal with `cat` to produce the effect.

**Comment by mintty** [comment]
This issue can be reopened if a reproducible description is available.

**Comment by mintty** [comment]
Any additional information?
