### ISSUE TITLE
Terminal hangs when closing

### ISSUE THREAD

**Issue by JaimeHolland** [mintty/wsltty#178]
Hi, I've just installed wsltty, and I have an issue whereby when I go to close a terminal, it just hangs.  I have to go into Task Manager and kill the process

**Comment by mintty** [comment]
You cannot close it by clicking on the top-right "×"?

**Comment by JaimeHolland** [comment]
Exactly.  I click the x, and the window becomes unresponsive - the title bar says "(Not Responding)"

**Comment by mintty** [comment]
Works here. Which WSL distribution do you use?

**Comment by JaimeHolland** [comment]
I'm not at my pc at the minute, but I ended up assuming this was an antivirus issue.  I can work around it by invoking wsltty via CMD.exe as inspired by this link https://superuser.com/a/1441900

**Comment by mintty** [comment]
Thanks. Both workarounds mentioned there are not generic solutions. But maybe they can give some Windows experts a hint how a workaround could be integrated in mintty. Marking "Help wanted".

**Comment by Biswa96** [comment]
Never seen this issue. I would suggest to monitor with Process Hacker and/or Process Explorer (as admin) and see if there any spike of CPU and Memory usage of any specific process. Is there any antivirus or anitmalware causing that?

**Comment by mintty** [comment]
Released 3.0.5 with new gateway. Please recheck.

**Comment by mintty** [comment]
Released 3.0.6.
