### ISSUE TITLE
vim background colo compatibility in wsltty

### ISSUE THREAD

**Issue by liwen-xu** [mintty/wsltty#179]
https://imgur.com/a/GJlQtNL
For whatever reason my nontext background seems to be darker. This problem persists with numbers column off. Only encountered this after i switched over to wsl so i'm not certain whether this stems from vim or windows.

**Comment by mintty** [comment]
Not sure what you are reporting here. How would you expect the screen to look like? Also, what's the actual output / how can it be reproduced? And which WSL and vim versions do you run?

**Comment by liwen-xu** [comment]
Sorry, turns out it wasn't anything to do with wsltty.

Did you like to delete the issue due to its irrelevance? @mintty

**Comment by mintty** [comment]
[no need to reopen for additional comments]

Issues cannot be deleted, just closed and marked Invalid.
Thanks.

**Comment by mintty** [comment]
Ah, in fact issues _can_ be deleted. I'll try that.
