### ISSUE TITLE
Custom icons (specified by -i) don't seem to work

### ISSUE THREAD

**Issue by anbenson** [mintty/wsltty#18]
I'm trying to launch wsltty from a cmd.exe window with a custom icon using the -i flag.

When I run
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --wsl -o Locale=C -o Charset=UTF-8 /bin/wslbridge -t /bin/bash`
wsltty seems to work as expected.

When I run
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --wsl -o Locale=C -o Charset=UTF-8 /bin/wslbridge -t /bin/bash -i C:\Users\andrew\home\Downloads\terminal.ico`
a mintty window opens briefly (~1 second) and then disappears, and nothing is printed to the console. The icon in the top-left corner of the window that briefly appears seems to be the default mintty icon, not the custom one I specified or the usual bash.ico that wsltty uses.

I'm on Windows 10 64bit build 14393.576, using wsltty 0.7.3 (mintty 2.7.3).

I have since circumvented the issue by right-clicking on the shortcut wsltty installs, and using Properties->Change Icon to get the icon I want, but I thought this should still work through cmd.exe since this works when I don't pass in all the wsl flags.

**Comment by mintty** [comment]
/bin/wslbridge is the PROGRAM argument of mintty, all further arguments go as parameters to it, and in turn everything after /bin/bash is a parameter for bash, not mintty.
You must place the -i parameter before the PROGRAM argument.

**Comment by anbenson** [comment]
Oops, my bad, sorry. Thanks for the quick reply and explanation.
