### ISSUE TITLE
VirusTotal is showing two engines detected on 3.0.2 installer exe

### ISSUE THREAD

**Issue by CharlesCage** [mintty/wsltty#181]
It's probably a couple of false positives (considering that most sources aren't detecting anything), but maybe if we know why its happening I could go back and add that to the VirusTotal community notes for the next person to come along.

![image](https://user-images.githubusercontent.com/38061259/62241323-8d663080-b39e-11e9-8ea1-5884f23e3cfb.png)

**Comment by Biswa96** [comment]
This was previously discussed at here https://github.com/mintty/wsltty/issues/94. wsltty uses some script files to make shortcut and extract it. So, some AV software may show those false warnings.

**Comment by mintty** [comment]
One suspicion is that vbs scripts trigger such a report. Please test 3.0.2.3 which drops mkshortcut.vbs.

**Comment by Biswa96** [comment]
Now it shows 5 out of 67. [Virustotal Link](https://www.virustotal.com/gui/file/7a3e58caf8962e2b303682c6539e18a7cafc87b96e04748c6fe32db5b92bb378/detection)

**Comment by mintty** [comment]
OK, I'll revert this nonsense, particularly as mkshortcut.exe pulls in 3 additional library dependencies and somehow cannot be built -static.

**Comment by mintty** [comment]
Released 3.0.5. Please recheck.

**Comment by mintty** [comment]
Released 3.0.6.
