### ISSUE TITLE
Options could not be saved when folder in AppData doesn't exists

### ISSUE THREAD

**Issue by xor-gate** [mintty/wsltty#183]
![image](https://user-images.githubusercontent.com/1050166/62603445-38726f00-b8f6-11e9-807b-2be2a5751c2c.png)

The folder doesn't exists, and for some reason this is related to a few very old issyes #4 and #42. I'm running wsltty version 3.0.2. This is a clean installation and I expect it works out of the box or at least tell me where the dotfile is saved or configurable where it is located. 

In the README the following is depicted which feels a bit weird:

> (About deprecated options) By default, %HOME% would refer to the root directory of the cygwin standalone installation hosting wsltty. So %HOME% would mean %LOCALAPPDATA%\wsltty\home\%USERNAME%. If you define HOME at Windows level, this changes accordingly. Note, however, that the WSL HOME is a completely different setting.

For my fix I will try to use the `-c`  commandline option to place it where I like it. 

Thanks for the application!

**Comment by mintty** [comment]
There is a `--configdir` option in the shortcut and the command line .bat files deployed with wsltty which implies a `-c` option. How did you invoke wsltty?

**Comment by xor-gate** [comment]
I did use the `configure WSL shortcuts` and it generates an ink file with the following contents:
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL="Ubuntu-18.04" --configdir="%APPDATA%\wsltty" `

**Comment by mintty** [comment]
Does the actual WSL invocation fail somehow?
Otherwise I can hardly reproduce how this could happen, because `--WSL` enables WSL support, and with that, loading (and later saving) the config file from the quoted location is skipped...

**Comment by xor-gate** [comment]
No WSL invocation works as expected, I have "solved"  this by creating my own invocation of mintty.exe with the `-c` option directly in the WSL home directory of my user. I think it is not very relevant for wsltty as this is related to mintty.

**Comment by mintty** [comment]
Released 3.0.5. Assuming this has been fixed.
