### ISSUE TITLE
Ctrl+click can not open correct directory?

### ISSUE THREAD

**Issue by vinlyx** [mintty/wsltty#19]
When I used ctrl+click to open a folder like /bin, the terminal opened a bin folder in "%LOCALAPPDATA%\wsltty\bin" instead of the real bin folder of WSL ("%LOCALAPPDATA%\lxss\rootfs\bin").
A missing path error would be raised when I tried to open /sbin which doesn't exist in "%LOCALAPPDATA%\wsltty".
It is a bug of wsltty or I need to change some configuration? Thanks!

wsltty version: 0.7.3
Windows version:  14393.576
mintty was launched by "WSL Bash % in Mintty" shortcut.

**Comment by mintty** [comment]
Link-click adaptation for WSL was implemented in mintty 2.7.1 but only for paths outside the WSL root (starting with /mnt). Because the WSL file system is well hidden deep in the user's folders, I assumed the reverse mapping was not desired; also it's slightly more tricky. I'll check.

**Comment by vinlyx** [comment]
@mintty Thanks for the detailed explanation~! I think the Link-click is one of the best feature of mintty. It will be very convenient if we can have this feature on WSL. Thanks~!

**Comment by mintty** [comment]
Released 0.7.4.

**Comment by astonim** [comment]
This is still not working properly in 1.7.9. It can only open files and directories directly under C:\Users\<USERNAME>. And it always assume Ctrl-Click is in this directory.

**Comment by mintty** [comment]
Used to work once...

**Comment by mintty** [comment]
Released 1.8.0.

**Comment by astonim** [comment]
Still not working in the newest release. Only work for files under /mnt/c/Users/<user_name>. It doesn't work for sub directories from there.

**Comment by mintty** [comment]
Actually, for me it works. Mind two things:
* Relative path names work only relative to the start directory as mintty cannot detect the current shell working directory of a WSL shell.
* Path names with spaces make trouble, and there are many of them below /mnt/c/Users/<user_name>.

If you find an issue that does not match one of these two limitations, please describe it in detail.

**Comment by astonim** [comment]
Please see screenshots.
![capture3](https://user-images.githubusercontent.com/32780073/32091919-2a4bfafe-baab-11e7-82c7-58642c85e0da.JPG)
![capture](https://user-images.githubusercontent.com/32780073/32091924-2e38d844-baab-11e7-99b4-0ab4d175e7ed.JPG)
![capture1](https://user-images.githubusercontent.com/32780073/32091929-2f6dc576-baab-11e7-8baa-bd20c1add245.JPG)

**Comment by mintty** [comment]
This matches bullet 1 above. You started in C:\Users\Min and the relative pathname is interpreted from there. Mintty has no way to detect that the WSL shell has meanwhile changed into subdirectory `test`.

This is in fact different from a cygwin shell, for which mintty can detect that because it's running within the same runtime environment.
However, a feature to explicitly set the current working directory for reference is available already (OSC 7 from Mac Terminal); it's currently used with Alt+F2 in cygwin; support for its interaction with WSL can probably be added.

**Comment by astonim** [comment]
I see. Thanks a lot for the explanation. Now I understand why it doesn't work. Looking forward to full support of Ctrl-Click in wsltty in the future.

**Comment by mintty** [comment]
Released 1.8.1. Please recheck.

**Comment by astonim** [comment]
The behavior in the new release 1.8.1 is still the same. But I understand the difficulty of the issue. Thanks a lot for updating this.

**Comment by mintty** [comment]
> However, a feature to explicitly set the current working directory for reference is available already (OSC 7 from Mac Terminal); it's currently used with Alt+F2 in cygwin; support for its interaction with WSL can probably be added.

Done.

**Comment by mintty** [comment]
Released 1.9.0. Ctrl+click considers OSC 7.
