### ISSUE TITLE
Working with the hvbridge project

### ISSUE THREAD

**Issue by fpqc** [mintty/wsltty#190]
Hey there, I know you've been working on implementing the wslbridge2 and hvbridge things into wsltty.  I see that you've gotten it running, and I was wondering what commands I need to pass to mintty to get it to run hvbridge.

**Comment by mintty** [comment]
Simply run `mintty --WSL=Ubuntu` or whatever distro you want. You can do that from cygwin, or from a standalone installation like wsltty, if you have installed the wslbridge2 and hvpty frontends and backends in /bin.

**Comment by Biswa96** [comment]
People have done it already, see here https://github.com/mintty/wsltty/issues/186. BTW, The name's hvpty.

**Comment by mintty** [comment]
I had forgotten to update the mintty documentation (man page, wiki Tips) for the switch from wslbridge to wslbridge2. Updated now.

**Comment by mintty** [comment]
Released 3.0.5.
