### ISSUE TITLE
wsltty won't run after upgrade to version 3.0.5

### ISSUE THREAD

**Issue by cehovski** [mintty/wsltty#192]
Installed WSLtty using chocolatey. Ran the **uninstall.bat** script following with the **install.bat** script and **configure WSL shortcuts**, **add to context menu**,  in %programdata%\chocolatey\lib\wsltty\tools\wslttyinstall.

Getting error when running Debian Terminal. Window closes before I can read the output.

Does WSLtty output to any logs files which I could check?

**Comment by mintty** [comment]
No, but you can add option `-h alw` to the invocation command (in the shortcut) to keep the window open and read the output.

**Comment by althaser** [comment]
I am getting the following error message:

/bin/wslbridge2: Exit 1.
wslbridge error: failed to start backend process
note: backend error output: /bin/sh: 1: wslpath: not found
/bin/sh: 1: : Permission denied

**Comment by mintty** [comment]
Which WSL distribution do you run?
@Biswa96 ?

**Comment by Biswa96** [comment]
I think @althaser is using old Windows 10 release. `wslpath` should be in `/bin` folder. It is available from [Windows 10 version 1803](https://devblogs.microsoft.com/commandline/windows10v1803/).

**Comment by mintty** [comment]
Oh, I should mention that on the project page.
Is 1803 a public release or is it actually still in Insider Previews?

**Comment by althaser** [comment]
yes, I still have windows 10 1709 version :(

I can run wsl inside the cmd. And I don't have wslpath inside /bin/ nor /usr/bin/ 

still waiting for windows 10 update from my department.

thanks

**Comment by Biswa96** [comment]
@althaser You can still use old wsltty.

**Comment by cehovski** [comment]
I get a similar error as althaser.

/bin/wslbridge2: Exit 1.
wslbridge error: failed to start backend process
note: backend error output: /bin/bash: -d: neveljavna možnost

For some reason it's also outputting the error text in my mother tongue. Neveljavna možnost translates to "Invalid option". Does anyone know how I can make it output in english?

So I guess it's being ran with an option that doesnt exits.

Options are:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --rcfile
        --restricted
        --verbose
        --version
Shell options:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP ali možnost -o

**Comment by mintty** [comment]
> note: backend error output: /bin/bash: -d: neveljavna možnost

This is actually a different issue. Did you edit the shortcut and by chance somehow spoil it perhaps?

**Comment by Biswa96** [comment]
The `-d` option is for `wsl.exe` which chooses distribution name. It is only available in [Windows 10 build Build 17763 (1809) or higher](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17763-1809).

**Comment by mintty** [comment]
So maybe an older `wsl` would pass on the option to the invoked shell? That would explain the issue.
So the minimum requirement for wsltty 3.0.5 is raised to Windows 1809.
According to https://en.wikipedia.org/wiki/Windows_10_version_history that's the November 2018 release version.

**Comment by cehovski** [comment]
I'm on Windows 10 Version 1803. Guess it's time to upgrade.

Thank you for your time and effort.

You're doing a great job with this project!
