### ISSUE TITLE
Window closes without error message

### ISSUE THREAD

**Issue by mhayen** [mintty/wsltty#194]
Hi,
I freshly installed 3.0.5 but when I click the shortcuts the window opens and disappaers immediately. Adding -h always to the shortcut just gives me a black empty windows :-(

Can I see logs/errors somewhere?
Mark

**Comment by Biswa96** [comment]
See the README page for the minimum Windows 10 version requirement. If your Windows 10 version is equal or greater then this release will work. Also in this version, there is a bug in wslbridge2. Just wait for next release, 1 day.

**Comment by Biswa96** [comment]
See the README page for the minimum Windows 10 version requirement. If your Windows 10 version is equal or greater then this release will work. Also in this version, there is a bug in wslbridge2. There is a small note in [wslbridge2 release page](https://github.com/Biswa96/wslbridge2/releases) for _temporary_ workaround. Please wait for the next wsltty release which is coming soon.

**Comment by mhayen** [comment]
I am using Windows 10 Version 1809 (OS Build 17763.720)

**Comment by mintty** [comment]
Released 3.0.6. Please recheck.

**Comment by mhayen** [comment]
Sadly same result.
Is there a way to see some errors/output?

**Comment by Biswa96** [comment]
If you are opening from a shortcut then append `-h always` in shortcut's properties target.

**Comment by mhayen** [comment]
Still the same I'm afraid, no errors no other output, just an empty box

**Comment by mintty** [comment]
Sure that's with 3.0.6? After you made it stay open, please check in Options - About.

**Comment by mhayen** [comment]
yes
![afbeelding](https://user-images.githubusercontent.com/16207818/66275984-79ebb000-e88e-11e9-98ec-8e316a283177.png)

**Comment by mintty** [comment]
Test case:
Please open a `cmd` window.
`cd %LOCALAPPDATA%\wsltty\bin`
`wsl ls -l`
`mintty --WSL`

**Comment by mhayen** [comment]
![afbeelding](https://user-images.githubusercontent.com/16207818/66277234-e0c39600-e89b-11e9-9d6f-7547ee571315.png)

**Comment by mintty** [comment]
You obscured the essential part of the `ls -l` output; do the backends have the x bit set?
And WSL doesn't start perhaps after a while (initial start may take a minute)?

**Comment by mhayen** [comment]
Yes they all have the executable bit set.
And WSL starts immediately





Op ma 7 okt. 2019 om 00:50 schreef mintty <notifications@github.com>:

**Comment by mhayen** [comment]
![afbeelding](https://user-images.githubusercontent.com/16207818/66277453-259cfc00-e89f-11e9-85a5-944bdab0e941.png)

**Comment by mintty** [comment]
> And WSL starts immediately

Misunderstood. The window starts, but not the WSL shell. But perhaps after some time?

**Comment by codeman38** [comment]
Seeing this as well. I added `-h always` to the shortcut, and that makes it possible to see the error:

`note: backend error output: /bin/bash: -d: invalid option`

Looks like the issue is that the updated launch script is incompatible with the version of bash in Ubuntu 16.04.

**Comment by Biswa96** [comment]
@codeman38 Is your Windows 10 version equal or greater than the minimal requirement? See README.

**Comment by codeman38** [comment]
Ah, yeah, I totally missed that. I am indeed on 1803 due to corporate IT not having rolled out a newer version. Sorry!

**Comment by Biswa96** [comment]
With old Windows 10 versions, anyone can use old wsltty release.

**Comment by mintty** [comment]
Maybe wslbridge2 could check the version first and print a warning if too small.
Unfortunately, MS does not give us a proper API to retrieve the version. I think GetVersion does at least report the 5-digit build number, so that has to be mapped from 1809 manually.

**Comment by Biswa96** [comment]
> MS does not give us a proper API to retrieve the version.

Internet is full of those 😄 See [RtlGetVersion][1]. BTW, I am somewhat confused, should I check the Build number (18362) or the version number (1903).


[1]: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlgetversion

**Comment by mintty** [comment]
According to https://en.wikipedia.org/wiki/Windows_10_version_history that would be 17763.

**Comment by Biswa96** [comment]
Added. Check please.

**Comment by mintty** [comment]
As checked above, I guess 17763 is the first build that works.
So it should be
    if (GetWindowsBuild() < 17763)
Also missing in hvpty.
Functionally, it works.

**Comment by Biswa96** [comment]
hvpty already checks that with by checking if the distribution is WSL2 or not. When I will combine those frontends this check will be done every time.
