### ISSUE TITLE
'wslbridge2.backend' arg list lacking the '-l' option ????

### ISSUE THREAD

**Issue by aabatpurdue** [mintty/wsltty#196]
This is sort of an extension of the "login_shell=off" problem.

Attachment contains results from two **pslist -ap** runs plus the command lines for **wslbridge2.backend**, one for 3.0.2.3 and one for 3.0.6.

The **wslbridge2.backend** command line lacks specification of the '-l' option.  Is this a feature?

A second thing I noticed is an extraneous **sh** process.  If my assumption is correct that its primary purpose is to instantiate **wslbridge2.backend**, it is not necessary to keep the process in the tree.  You could run " **init -> sh { (backend&)& exit }**" to remove it.

[backend.txt](https://github.com/mintty/wsltty/files/3699922/backend.txt)

**Comment by mintty** [comment]
Both backends and hvpty frontend have a "-l" option. The wslbridge2 frontend does not seem to have it.
Anyway, all 4 also support login mode via argv[0][0]. It's just a matter of the wsltty integration, which shall add the mintty "-" parameter in the shortcuts.

**Comment by mintty** [comment]
Previous comment was wrong. Backends support "-l" and both frontends support *argv[0].

**Comment by mintty** [comment]
Released 3.1.0.
