### ISSUE TITLE
Windows 1803: Run mintty with --WSL="Ubuntu" results in an error, but Ubuntu on Windows is installed

### ISSUE THREAD

**Issue by jdhao** [mintty/wsltty#198]
I have installed wsltty (version 3.0.6). The invocation used by WSL Terminal is the default:

```
%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~
```

I can open Ubuntu terminal with the above command.

According to doc [here](https://mintty.github.io/mintty.1.html), `--WSL` can also be followed by an explicit distribution name. We can show distribution name via `wslconfig /l`. On my system, the output is like:

> Windows Subsystem for Linux Distributions:
Ubuntu (Default)

 if I change the invocation to 

```
 %LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL="Ubuntu" --configdir="%APPDATA%\wsltty" -~
```

Then the terminal window disappears. I add the `-h always` option to capture the error message:

```
/bin/wslbridge2: Exit 1.
wslbridge error: failed to start backend process
note: backend error output: /bin/bash: -d: invalid option
Usage:  /bin/bash [GNU long option] [option] ...
        /bin/bash [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --rcfile
        --restricted
        --verbose
        --version
Shell options:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP or -o option
```

It seems strange.

**Comment by Biswa96** [comment]
See minimum requirement of Windows 10 version.

**Comment by jdhao** [comment]
> See minimum requirement of Windows 10 version.

Minimum requirement for what?  wslbridge? @Biswa96

**Comment by Biswa96** [comment]
minimum requirement of wsltty in README.

**Comment by mintty** [comment]
Minimum requirement for Windows. Alt+R `winver` command.

**Comment by jdhao** [comment]
Thanks for your hint, I wasn't aware that it is caused by the version mismatch. IIRC, my Windows version is 1803. But it seems that I can still use wsltty without apparent errors...

**Comment by mintty** [comment]
@Biswa96, it seems quite a few people still run older Windows versions.
What if you reactivate the option to pass a {guid} to wslbridge2?

**Comment by Biswa96** [comment]
> my Windows version is 1803. 

The minimum requirement is 1809 version aka. 17763 build.

> What if you reactivate the option to pass a {guid} to wslbridge2?

Sorry, I can't. That is one of the reason I switch to making wslbridge2. Also the registry is not documented and subject to change. After all, users should use latest Windows 10 if possible.

**Comment by oyvindstegard** [comment]
Not everyone is able to run the latest Windows 10 build, even if they wanted to. Enterprise managed machines under control of employer upgrade policy is one such example. I am no longer able to run the latest wsltty-release, which is a shame, since I really like the software, and it worked well. (Windows 1803 17134.1009.)

**Comment by mintty** [comment]
In theory, wsltty could check the Windows version and use old wslbridge or new wslbridge2 respectively.

**Comment by Biswa96** [comment]
@oyvindstegard Yes you can use old wsltty release. There is nothing extra in this new wsltty.

**Comment by mintty** [comment]
Closing this issue as the respective Windows version is now out of service,
see https://github.com/mintty/wsltty/issues/206#issuecomment-716128278.
