### ISSUE TITLE
Not Responding when configuring

### ISSUE THREAD

**Issue by goffinf** [mintty/wsltty#199]
wsltty version : 3.0.2.3
Windows version: 10 Enterprise - 1803
WSL : Ubuntu 18.04

I cant use the latest version of wsltty because I am using a company laptop and at present ony Windows 1803 is available, so I went for the latest pre 3.0.5.x version.

Installation was fine but as soon as I attempt to configure any of the properties, that dialogue just hangs and emits the common 'Not Responding' message. The only course of action is to End Program.

The regualr WSL terminal works fine and I have been using it for some time. I also have tmux installed (but that wasn't running when I was trying to configure wsltty).

I have uninstalled wsltty for now (using the provided uninstall script) but I would like to use it if possible.

Any suggestions ?

Regards

Fraser.

**Comment by Biswa96** [comment]
If you are using old Windows 10 version you can also use old wsltty release. There will be no issue. The new release is supported from Windows 10 version 1809.

**Comment by goffinf** [comment]
I *am* using an older version as you can see above. The docs clearly state that Windows 1809 is a requirement for version 3.0.5+ which is why I selected the one prior to that.

Which one do you suggest ?

**Comment by mintty** [comment]
> configure any of the properties

What exactly do you mean? Right click on a WSL Terminal desktop shortcut in the Start Menu?

**Comment by goffinf** [comment]
Ok, ... 

1. wsltty installation was successful.
2. Launch wsltty from the desktop shortcut - successfully runs wsltty and terminal works as expected.
3. Right-click on the terminal window and bring up the configuration dialogue.
4. Click any of the items

No response and after a short time the standard Windows message ‘The Program is Not Responding’

**Comment by mintty** [comment]
Do you have any desktop tool installed that might capture or generate mouse clicks (like AutoHotkey, StrokeIt, ...)?

**Comment by mintty** [comment]
Can you install cygwin and run `mintty --WSL` from there? Does it happen then? We could try some debugging in this environment.
