### ISSUE TITLE
how to invoke wsltty in my own .bat to open mintty it in a given dir?

### ISSUE THREAD

**Issue by jmlucjav** [mintty/wsltty#2]
I am trying to create a .bat to basically do the same as going to a given dir in Explorer and running 'WSL in mintty here'.

But no dice, I should be able to find out by looking at what command are inserted in the registry but I'm missing something.

Could you give an example please?

**Comment by mintty** [comment]
In the .bat, enter the desired directory.

Check the "Target" command in the Desktop Shortcut and invoke that but leave out the final `-l`.

**Comment by jmlucjav** [comment]
worked, thanks!
