### ISSUE TITLE
Changing title with escape sequences?

### ISSUE THREAD

**Issue by SwissFrank** [mintty/wsltty#200]
You seem to use the Putty code, which supports the Xterm escape sequences.  For instance in tcsh the following work fine:

alias precmd 'echo -n "\033]0;$title - $cwd\007"'

However this doesn't work in Mobaxterm v12.2 Build 4204, on 64-bit Windows 10.

I see elsewhere you mention that changing the title programmatically is supported, though.  What's up?

**Comment by mintty** [comment]
Depending on your shell, the notation \033 may not be supported, or only with an additional -e parameter.
