### ISSUE TITLE
wsltty closes immediately after login

### ISSUE THREAD

**Issue by xXBeekeyXx** [mintty/wsltty#201]
wsltty closes immediately after login. I can sidestep this issue by first starting cmd.exe, then starting wsl.exe and then logging in. When doing that, wsltty will NOT crash. It only crashes if I login immediately after launching it.

Distro: Arch Linux
WSL version 1

**Comment by mintty** [comment]
wsltty version?

**Comment by Biswa96** [comment]
Also the windows version? Any error code shown with `-h always` option?

**Comment by mintty** [comment]
Duplicate of #220? Maximized or full-screen configured?
