### ISSUE TITLE
Show progress of WSL commands in taskbar

### ISSUE THREAD

**Issue by sarangjo** [mintty/wsltty#202]
I'm not sure if this should be an issue in this repo or mintty or wslbridge, but I recently tried using ConEmu and discovered that it actually shows the progress of some commands being run in WSL bash in the taskbar.

On running `sudo apt update`, you'll see the command progress below is at 48%, and that progress is reflected in the taskbar icon. I'd have to do some research on:

- how the `apt` command advertises its progress to the shell
- how the shell provides access to this progress to the terminal

But I think this could be a valuable enhancement to WSLtty.

![image](https://user-images.githubusercontent.com/1961007/68992805-849e4b00-0825-11ea-8ef2-c046cedf7f57.png)

**Comment by mintty** [comment]
I doubt the shell is involved. I'd guess the application notifies the terminal directly, with certain escape sequences. This could be monitored with some screen logger (script/tmux/...).
Or the terminal magically recognizes specific pattern in the terminal output ("Reading ... %").
On the terminal side, taking escape sequences is quite easy. Implementing a modified task bar icon via the Windows API would be a challenge, again.

**Comment by Biswa96** [comment]
@sarangjo Which shell are you using in WSL side? Are you sure the progress data come from WSL side? Is it possible to make a shell script to emulate the progress behaviour? cc. @Maximus5

**Comment by mintty** [comment]
Actually, ConEmu has the feature (enabled by default) to scan the current cursor line for a final "%" implicitly to derive progress information. It could be an optional feature but someone would have to implement it...

**Comment by mintty** [comment]
Released 3.4.2.

**Comment by Biswa96** [comment]
Where is the option to enable it?

**Comment by mintty** [comment]
You can control the progress bar interactively, sequences described in https://github.com/mintty/mintty/wiki/CtrlSeqs#progress-bar, or enable implicit progress detection intially with option `ProgressBar`.

**Comment by Biswa96** [comment]
It works. Why is it experimental? If `ProgressBar` option is added in Options menu then users may enable it and report any issue quickly.

**Comment by mintty** [comment]
There has been some discussion in https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/29 about the sequence and functionality. Depending on adoption of control sequences by other terminals, they might still get changed.
I have been very hesitant to include new features in the Options menu, especially exotic options, in the tradition of mintty to provide clean and tiny interactive configuration. I've been wondering all the time whether people might request additional interactive options but that was almost never the case...

**Comment by Biswa96** [comment]
1. Does this progress bar work with pure Win32 programs? I have tried with [aria], it does not show the progress bar.
2. Sometimes, let say the percentage goes to ~50% then if I minimize the mintty window, the progress bar stuck in that position even though the download completes.

[aria]: https://aria2.github.io/

**Comment by Biswa96** [comment]
1. Does this progress bar work with pure Win32 programs? I have tried with [aria], it does not show the progress bar.
2. Sometimes, let say the percentage goes to ~50% then if I minimize the mintty window, the progress bar stuck in that position even though the download completes.
3. Is the `ITaskbarList4` object created each time when `taskbar_progress()` is called? Can't it be created once and used multiple time i.e. global variable?

[aria]: https://aria2.github.io/

**Comment by mintty** [comment]
1. In implicit progress detection mode, mintty simply scans output in the line of the current cursor position. What does the output of that program look like? Maybe the cursor position is somewhere else, possibly due to ConPTY handling.
2. Progress bar when minimized works for me: `sleep 2; echo -e "\e[3;50%q"` then minimize
3. it's ITaskbarList3 now, and I don't see a problem. Other Windows objects are also acquired and released frequently.

**Comment by mintty** [comment]
I have tried that program but it does not show me any progress indication.

**Comment by mintty** [comment]
OK, the previous download was too fast (few MB...). With a larger file, aria progress indication looks like this:
`[#a26855 196MiB/1.9GiB(10%) CN:1 DL:19MiB ETA:1m31s]`
so the percentage is hidden inmidst the output. Currently, only percentage near the end is considered, i.e. only a ')' character may follow. I'll add ']' to it but scanning a percentage anywhere in the line would trigger progress indication also in other cases which is not desirable. So by what criteria should progress be scanned from the line?

**Comment by mintty** [comment]
Released 3.4.4.
