### ISSUE TITLE
Modify the thickness of underscore cursor

### ISSUE THREAD

**Issue by tejasvi** [mintty/wsltty#203]
How to modify the underscore cursor appearance? (particularly thickness)

**Comment by mintty** [comment]
Such feature is not available.

**Comment by Biswa96** [comment]
This can be done in `wintext.c` in `CUR_UNDERSCORE` case. But the logic was written in kind of cryptic way. x, dx, ff, yy, cc ??

**Comment by mintty** [comment]
It can be done easily but it's not a feature in the VT100/xterm tradition that mintty largely refers to. I saw this feature is supported somewhere (was it a VGA "ANSI driver"?) but I'd need a reference to escape sequences and additional supporters to add such a "3rd-party" feature.

**Comment by mintty** [comment]
Implemented a respective control sequence from Linux console, as found in https://linuxgazette.net/137/anonymous.html

**Comment by mintty** [comment]
Released 3.1.4.
