### ISSUE TITLE
Make the block cursor translucent

### ISSUE THREAD

**Issue by tejasvi** [mintty/wsltty#204]
How to modify the block cursor appearance? (particularly transparency)

**Comment by mintty** [comment]
Such feature is not available.

**Comment by Biswa96** [comment]
@tejasvi Did you mean like Empty Box cursor in Command Prompt?

**Comment by testsite8874** [comment]
@Biswa96 I was hoping for semi transparent though empty would be good enough too.

**Comment by mintty** [comment]
Released 3.4.2.
