### ISSUE TITLE
ARM64 Build

### ISSUE THREAD

**Issue by mebaran** [mintty/wsltty#209]
Would it be possible to publish builds for ARM64?  Even a 32bit build would be convenient for those of us running the new Windows on ARM laptops.  The software is amazing for me on my x86 laptops, and I would definitely appreciate the ability to run it on these newer platforms.

**Comment by Biswa96** [comment]
It is possible to run wsltty in ARM64 machine. But I have no ARM Windows machine where I can test it. You only need to add ARM64 in the preprocessor in `findSystemProgram` function in [Helper.cpp][1] file.

[1]: https://github.com/Biswa96/wslbridge2/blob/master/src/Helpers.cpp

**Comment by Biswa96** [comment]
It is possible to run wsltty in ARM64 machine. But I have no ARM Windows machine where I can test it. To build native ARM64 binaries, you only need to add ARM64 in the preprocessor in `findSystemProgram` function in [Helper.cpp][1] file.

[1]: https://github.com/Biswa96/wslbridge2/blob/master/src/Helpers.cpp

**Comment by mintty** [comment]
This involves a processor emulation, right? I wouldn't expect mintty to run at acceptable speed. Can you install cygwin and try it please?

**Comment by Biswa96** [comment]
Though the X86 emulation isn't too slow as advertised. X86 wsltty package can be added in release.

**Comment by mintty** [comment]
But isn't WSL available for 64 Bit only?

**Comment by Biswa96** [comment]
WSL is available in ARM64 (aarch64) Windows 10. Also ARM64 Windows 10 has an [emulation layer to emulate X86 binary][1]. So I think (**not sure**) OP may run X86 wsltty binary in ARM64 Windows.

[1]: https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm-x86-emulation

**Comment by mintty** [comment]
So is there *only* a 32-bit emulation, no 64-bit one?

**Comment by mintty** [comment]
Also, even on Windows, running WSL from 32-bit cygwin does not seem to run anymore (Exit 127)...

**Comment by Biswa96** [comment]
Yes, there is only X86 emulation in ARM64. Though there are [some news about X86_64 emulation in ARM64][1].

[1]: https://www.neowin.net/news/exclusive-microsoft-is-working-to-bring-64-bit-intel-app-emulation-to-windows-on-arm

**Comment by Biswa96** [comment]
> So is there only a 32-bit emulation, no 64-bit one?

Yes, there is only X86 emulation in ARM64. Though there are [some news about X86_64 emulation in ARM64][1].

> running WSL from 32-bit cygwin does not seem to run anymore (Exit 127)...

No issue on my side. You have to specify the WSL distribution version (`-V` option) as 32bit wslbridge2 can not load 64bit wslapi.dll.

[1]: https://www.neowin.net/news/exclusive-microsoft-is-working-to-bring-64-bit-intel-app-emulation-to-windows-on-arm

**Comment by mintty** [comment]
> running WSL from 32-bit cygwin

works with latest wslbridge2. Sorry, I had switched around a bit when facing those compilation issues...

**Comment by mintty** [comment]
So I'll put together a new wsltty release tomorrow. Also adding a 32-bit binary package.
Can you make a wslbridge2 release reflecting the latest changes?

**Comment by mintty** [comment]
Oh, forgot you'll have to add something to support ARM. I'll wait until that's sorted out with @mebaran and tested, maybe.

**Comment by mebaran** [comment]
I am happy to help with testing or building.  To confirm, launching wsl.exe from an C:\Windows\Sysnative works for emulated processes.  I think that's what your Helper.cpp is looking for.  Performance of WSL is excellent (as it runs Linux ARM64 native packages!).  I am running WSL2 on my Surface Pro X at the moment.

Is it possible to build wsltty without cygwin (potentially maybe within WSL itself)?  I do not believe cygwin has a native Windows ARM release yet, so it wouldn't be helpful for marking ARM64 binaries yet.

**Comment by mintty** [comment]
> Performance of WSL is excellent (as it runs Linux ARM64 native packages!).

No doubt. My concern was about mintty which would run inside the emulation because there is no ARM cygwin.
Mintty uses a mix of POSIX and Win32 APIs, so as long as WSL does not support Win32 access, there can be no WSL-native mintty build.

**Comment by mebaran** [comment]
Would the normal x86-32 build work with mingw inside WSL?  I was thinking of trying something like using mingw and clang to produce windows arm64 binaries (maybe trying to leverage something like this: https://github.com/mstorsjo/llvm-mingw).  Let me know if this idea is terribly misguided.  I'm around to help as much as needed.

**Comment by mintty** [comment]
Not sure what "mingw inside WSL" or llvm-mingw would be. If there are both POSIX and Windows headers in the same environment, there is a chance to look further.

**Comment by Biswa96** [comment]
How about cross compiling from X86_64 to AARCH64? Also one has to compile cygwin also.

**Comment by mebaran** [comment]
On further research, I don't believe there are cygwin libraries for ARM64 yet.  Would you be able to generate an i686 32bit build for me test and see if that would simply work?  Looking at the source I don't think you'd have to change anything (as Windows will happily report itself to be a 32bit machine and the path you have configured in Helper.cpp seems like it points to the right place).  If you link me an image I'd be happy to be the tester!

**Comment by mintty** [comment]
I've made a 32-bit build but it does not run yet. As @Biswa96 said, a patch for wslbridge2 is still missing.

**Comment by mintty** [comment]
> To build native ARM64 binaries, you only need to add ARM64 in the preprocessor in findSystemProgram function in Helper.cpp file.

You mean the `#elif defined(__i386__)`? Wouldn't that be taken if you build the package on Windows/Cygwin-32?

**Comment by Biswa96** [comment]
I have not test whole wsltty package. Wait for some time to add ARM64 in wsltty.

I build a test package for @mebaran. See the release page of wslbridge2. I have added a `wslbridge2_cygwin_x86_aarch64.7z` file. In that package, wslbridge2.exe (frontend) is X86 but wslbridge2-backend is AARCH64 because the X86 emulation happens in Windows side not in WSL. Extract those files in a folder and place cygwin1.dll for X86 in it. You can get it from here http://cygwin.mirror.constant.com/x86/release/cygwin/ (/usr/bin/cygwin1.dll).

**Comment by mebaran** [comment]
Thanks @Biswa96 

I followed your instructions and I get an exception: 

assertion "hMod != NULL" failed: file "WinHelper.cpp", line 130, function: bool IsWslTwo(std::wstring)
    125 [main] wslbridge2 1311 cygwin_exception::open_stackdumpfile: Dumping stack trace to wslbridge2.exe.stackdump

Anything else I can do to help?

**Comment by Biswa96** [comment]
For the first error, try with `wslbridge2.exe --d Ubuntu -V 2` for Ubuntu in WSL2.

**Comment by mebaran** [comment]
Running that command I got no errors.  It immediately returned and I see a the bridge process running inside my instance now.  Was that what you expected?

**Comment by Biswa96** [comment]
Can you email me, I've some test program for arm?

**Comment by mintty** [comment]
Released 3.1.0 with 32-bit installer.

**Comment by Biswa96** [comment]
Now cygwin has conpty support. @mebaran you can try to use `wsl.exe` directly from cygwin X86 installation.

**Comment by mintty** [comment]
I'd like to update this issue. 32-bit x86 installer is now available. Any success on ARM?

**Comment by Biswa96** [comment]
As I have no Windows ARM devices 💰 I am trying to use Windows 10 ARM in my Raspberry Pi 4B. At the time of writing, it is only possible to boot Windows 10 ARM PE in RPi 4B with [Rpi4][1] repository. So, the progress of this issue depends on development of [RPi4][1] UEFI firmware.

[1]: https://github.com/pftf/RPi4

**Comment by anetsuk** [comment]
> I'd like to update this issue. 32-bit x86 installer is now available. Any success on ARM?

I have "surface pro X (ARM)" device, and tried to install 32-bit installer.
The installer worked fine in emulation, but execution failed "wsltty.exe".

Cause of failure, win32 binary well work on windows10, but Linux binary wslbrige2-backend can't exec on ARM64 linux(that is, included linux binaries are compiled as x86-64).

So, I re-compiled wslbridge2-backend binary on WSL2(Ubuntu) environment, and completely work!

**Comment by mintty** [comment]
Is this still an issue or can we close it?

**Comment by Biswa96** [comment]
Yes, this can be closed. Recompiling wslbridge2-backend to AArch64 is the only solution as of now. As GCC/Binutils does not support AArch64 target for Windows, cygwin can not be compiled for that architecture.

**Comment by mintty** [comment]
According to https://learn.microsoft.com/en-us/windows/arm/overview
> Windows 11 adds the ability to run unmodified x64 Windows apps on Arm devices!"

Can the 32-bit builds in wsltty releases be dropped in the near future?
