### ISSUE TITLE
Copy console text in tmux

### ISSUE THREAD

**Issue by whitecolor** [mintty/wsltty#21]
In tmux I do:
`Ctrl+B`, then `Ctrl + Space` I can make a selection (shown on screenshot). 

![image](https://cloud.githubusercontent.com/assets/736697/21839312/e50d29bc-d7f8-11e6-9898-54c17704b7cf.png)

But I don't get how to copy it into a clipboard. Any advice?

**Comment by mintty** [comment]
The terminal has access to the Windows clipboard, tmux does not.
Option AllowSetSelection can enable OSC control sequence 52 which can set the clipboard.
I don't know, though, whether tmux makes use of this sequence. Please try.

**Comment by whitecolor** [comment]
> Option AllowSetSelection can enable OSC control sequence 52

How exactly should I set this option?

**Comment by mintty** [comment]
Edit (or create) the config file %LOCALAPPDATA%/wsltty/home/%USERNAME%/.minttyrc
and add
`AllowSetSelection=true`

**Comment by whitecolor** [comment]
`%LOCALAPPDATA%/wsltty/home/%USERNAME%/` was empty
I created `.minttyrc` and added there `AllowSetSelection=true`.

Nothing changed, at least 

- How to check that the setting is in effect? 

- Don't you use tmux, maybe I just use wrong key combination (maybe it should be not just `enter`) to copy?

**Comment by mintty** [comment]
> How to check that the setting is in effect?

`echo -en '\033]52;;cmlnaHQgZ3JlZW4gb24gYmxhY2sg\007'`
then paste (middle-click)

> Don't you use tmux, maybe I just use wrong key combination (maybe it should be not just enter) to copy?

I cannot support on tmux, sorry. I couldn't even reproduce the highlighting from your description. If you tell me how tmux is supposed to copy, I could test myself.

**Comment by mintty** [comment]
A quick look into tmux sources reveals that it does support the clipboard sequence, feature `terminal-overrides` and option `set-clipboard`, and it even seems to be enabled by default, but I'm not sure.
Please provide a reproducible test case.

**Comment by whitecolor** [comment]
@mintty ok it seem [I found out](http://superuser.com/questions/1165829/windows10-ubuntu-bash-shell-mintty-tmux-copy-selection/1165850#1165850) correct combination for copy/past, inside tmux, but it doesn't interact with windows clipboard.

So to get tmux selection and copy:
- press `ctrl+B` - to enter tmux operatons mode
- press`[` - to enter copy mode
- then you may use arrow keys to navigate active pane
- at any place press `ctlr + space` to start the selection you make it using arrow keys
- to copy selection press `alt + w`
- you may use `ctl+B` then `]` to paste copied text int tmux 

but for me I can not paste selected text outside the console.

**Comment by mintty** [comment]
I can now copy from tmux inside mintty to the clipboard and paste into another mintty.
Not tested with WSL yet.

**Comment by whitecolor** [comment]
Probably should be done via some plugin: https://github.com/tmux-plugins/tmux-yank
though can not make it work yet.

**Comment by mintty** [comment]
No, I have verified that
* the clipboard copy function works from WSL (so this is not a mintty or wsltty issue)
* the clipboard copy function works from cygwin tmux

Finding out why it does not work from WSL tmux is really beyond my ambition.

**Comment by whitecolor** [comment]
Ok thank, I will close an issue then.

**Comment by mintty** [comment]
Thanks; yet I would appreciate your feedback if you solve the issue.

**Comment by whitecolor** [comment]
The solution:

- install `tmux-yank` plugin
- install xcopy until: `apt-get install xcopy` 
- add `export DISPLAY=:0` to `~/.bashrc`
- install [Xming X Server for Windows](https://sourceforge.net/projects/xming/)

After this copying using `y` key in `copy` mode of `tmux` should work.

**Comment by mintty** [comment]
Thanks, but this isn't really a solution as it takes a weird diversion via an X server, which in turn synchronises its clipboard with the Windows clipboard.
Since the proper escape sequence appears in the tmux code (at least in tmux 2.3 while WSL has 2.1), there must be a way that works without the overkill of an X server in between.

**Comment by whitecolor** [comment]
Well this is still working solution though.

Other solutions without X Server and even tmux plugin are discussed there: https://github.com/Microsoft/BashOnWindows/issues/1586 and https://github.com/tmux-plugins/tmux-yank/issues/75

**Comment by mintty** [comment]
One solution discussed there uses `/mnt/c/Windows/System32/clip.exe` which is one level less indirect but does not involve mintty either. Instead of `/...clip.exe` one could configure something like `echo -en '\033]52;;...\007'` where `...` is the base64-encoded copy text, but the fact that I saw this code in the tmux sources suggests that an easier way should be existing and just needs to be enabled.

**Comment by mintty** [comment]
On the other hand, if you successfully configure tmux to copy via `/...clip.exe` that should work in either of Windows console or mintty, so it's probably the more useful solution for WSL.

**Comment by aspyrx** [comment]
Hello, thanks for a great terminal emulator!

Just wanted to add:
On Windows 10 build 14986.1001, WSL Ubuntu 16.04.1, adding `AllowSetSelection=true` to my `.minttyrc` enables `tmux 2.3` to set the clipboard correctly (no extra steps required).

**Comment by lbergnehr** [comment]
> On Windows 10 build 14986.1001, WSL Ubuntu 16.04.1, adding AllowSetSelection=true to my .minttyrc enables tmux 2.3 to set the clipboard correctly (no extra steps required).

This works with tmux 2.1 as well!
