### ISSUE TITLE
 Cannot run in  windows 10 of ARM

### ISSUE THREAD

**Issue by xinmodao** [mintty/wsltty#211]
![image](https://user-images.githubusercontent.com/12230820/70045190-a279f700-15fe-11ea-9963-0987cb3c27ab.png)
Error reporting in windows 10 of ARM
After wsltty-3.1.0-install-i686.exe is installed, the system reports this error and cannot run it.

**Comment by mintty** [comment]
This is not a fatal error. You should click on the button. What happens?
ARM porting is work in progress, see #209.

**Comment by mintty** [comment]
What's the status of this issue with wsltty 3.1.4 with the following change:
* Fixed some cases of icon access.

**Comment by mintty** [comment]
Is this still an issue or can we close it?

**Comment by mintty** [comment]
Assumedly fixed by #209.
