### ISSUE TITLE
right click context menu gone in tmux

### ISSUE THREAD

**Issue by mreister** [mintty/wsltty#212]
When using wlstty with tmux the right click context menu is gone.

I haven't seen anyone else report this.. so i thought it might be related to my tmux conf.

I removed any reference to mouse mode in my config... just in case this may have been conflicting.

**Comment by Biswa96** [comment]
* Please add the Windows 10 version and build number.
* Was it available in older wsltty release (version 3.0.2.3 or older)?
* Did you add any config to tmux? i.e. What steps are needed to reproduce your issue after installing tmux?

**Comment by mintty** [comment]
In cygwin tmux, right+click still works. However, if an application activates application mouse mode, the mouse menu does not work anymore of course. What's your WSL distro?

**Comment by mreister** [comment]
Edition : Windows 10 Enterprise
Version : 1809
OS Build: 17763.805

I haven't tried this on older releases.

It doesn't work on wsl launched from cmd.exe

Here is my tmux config:

set -g prefix C-a
unbind C-b
bind C-a send-prefix
set -g default-terminal "screen-256color"
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
set -g pane-border-fg yellow
set -g pane-active-border-fg green
set-option -g status-position top
set -g status-fg white
set -g status-bg blue
set -g status-left ''
set -g status-right-length 60
#set-option -g mouse on

I turned of mouse mode thinking that this is interfering.. but it has the same behavior.

**Comment by mreister** [comment]
> In cygwin tmux, right+click still works. However, if an application activates application mouse mode, the mouse menu does not work anymore of course. What's your WSL distro?

My distro is debian.

**Comment by mintty** [comment]
I've installed the tmux package in Debian. Running tmux, the mintty context menu still works. Must be related to your config, please debug.

**Comment by mreister** [comment]
fixed it.
It was the `set-option -g mouse on` that was causing it. I just wasn't reloading my config correctly after i made this change the first time.

**Comment by mintty** [comment]
Shift+right-click overrides application mouse mode, by the way.
