### ISSUE TITLE
Truecolor not enabled?

### ISSUE THREAD

**Issue by jason404** [mintty/wsltty#214]
How do I enable truecolor support?  I have tried various terminal emulation modes, but I cannot get truecolour, which I believe mintty/wsltty supports?  I'm not sure what relevant further information I could provide at this point.  v3.1.0

**Comment by mintty** [comment]
Yes, it is supported unconditionally. No need to enable it.
However, some applications may reduce their feature usage based on TERM environment variable settings (via a terminal library).

**Comment by jason404** [comment]
Thanks, but I'm not running anything (no tmux).  I start wsltty and without running anything I type `pastel pick` or any other script that can show how many colours I have in the terminal, and I have only 256.  I have TERM=xterm256-color.
