### ISSUE TITLE
Blank row at bottom of screen in full screen mode

### ISSUE THREAD

**Issue by jason404** [mintty/wsltty#215]
At the bottom of the terminal in full screen mode there is a blank unused row a few pixels high, around the same height as a character row or tmux statusbar.  I noticed it before, but after a few months of not using wsltty (Windows Insider Build broke it) where I have not had this problem with other terminal emulators, it is annoying me.

Is there any way of reclaiming this blank unused row?

**Comment by mintty** [comment]
It's not a full row, so it cannot be used.
See mintty/mintty#323.
