### ISSUE TITLE
3.1.0.2 broke input for radare2

### ISSUE THREAD

**Issue by GustavoLCR** [mintty/wsltty#216]
You can test with:
```
r2 -
[0x00000000]>
```
You should be able to write in commands then, but nothing happens

It works fine with 3.1.0

**Comment by Biswa96** [comment]
Can you do this test with the newer one? Download cygwin from this link[1]. Extract `cygwin1.dll` from it using `tar -xf` command. Place it in `C:\Users\X\AppData\Local\wsltty\bin` folder (assume `X` is your user name).

**Comment by Biswa96** [comment]
Can you do this test with the newer one? Download [cygwin-3.0.7-1.tar.xz][1]. Extract `cygwin1.dll` from it using `tar -xf` command. Place it in `C:\Users\X\AppData\Local\wsltty\bin` folder (assume `X` is your user name).

[1]: http://cygwin.mirror.constant.com/x86_64/release/cygwin/cygwin-3.0.7-1.tar.xz

**Comment by GustavoLCR** [comment]
> Can you do this test with the newer one? Download [cygwin-3.0.7-1.tar.xz](http://cygwin.mirror.constant.com/x86_64/release/cygwin/cygwin-3.0.7-1.tar.xz). Extract `cygwin1.dll` from it using `tar -xf` command. Place it in `C:\Users\X\AppData\Local\wsltty\bin` folder (assume `X` is your user name).

That fixed it, thanks!

**Comment by mintty** [comment]
So what kind of program is radare? Windows program, Linux program? Some basic information is necessary to assess the situation because reverting to cygwin 3.0.7 is a workaround, not a fix.

**Comment by GustavoLCR** [comment]
> So what kind of program is radare? Windows program, Linux program? Some basic information is necessary to assess the situation because reverting to cygwin 3.0.7 is a workaround, not a fix.

Its a linux program

**Comment by mintty** [comment]
Please provide a reproducible test case:
What WSL distro? How to install radare2?

**Comment by mintty** [comment]
Closing due to missing demonstration of an issue.
