### ISSUE TITLE
Cannot remove shortcuts to removed distros/installs

### ISSUE THREAD

**Issue by cslycord** [mintty/wsltty#218]
I installed VoidMusl (from https://github.com/am11/VoidMuslWSL ) into WSL. After I installed it it, I ran the 'configure WSL shortcuts' script from the start menu.

This added entries for "VoidMusl Terminal" and "VoidMusl Terminal %" to the start menu, as expected.

I have since removed Void. I can't find a way to remove its shortcuts.
I can only find a script for removing entries from the context menu, but not the start menu.
'configure WSL shortcuts' merely creates new shortcuts for all of the currently installed distros and does not remove the invalid/old entries.

In the start menu, one can right-click and select "Uninstall" but all that does is bring up Windows' "Add/Remove Programs" settings, which doesn't help with wsltty shortcuts.

**Comment by cslycord** [comment]
Err... I installed VoidMusl from https://github.com/am11/VoidMuslWSL

**Comment by Biswa96** [comment]
Those shortcuts can be found in `%AppData%\Microsoft\Windows\Start Menu\Programs\WSLtty` folder. Try to delete those manually.

**Comment by cslycord** [comment]
Thanks.

Still, it would be preferable for the shortcut generation script to handle that.

**Comment by cslycord** [comment]
It's of note that that's not the only directory that the script installs shortcuts to. 

"VoidMusl Terminal" was installed to `%AppData%\Roaming\Microsoft\Windows\Start Menu\Programs`
"VoidMusl Terminal %" was installed to `%AppData%\Microsoft\Windows\Start Menu\Programs\WSLtty`

**Comment by mintty** [comment]
Released 3.1.4.

**Comment by cslycord** [comment]
Unless I'm missing something, this seems to remain the same.

When I click on "configure wsl shortcuts" in the start menu, the wsltty-generated shortcuts for no-longer-installed WSL installations remain. It looks like from the changed code, that what was changed applies to adding to the context menu rather than configuring the shortcuts.

**Comment by mintty** [comment]
The intent is that only such shortcuts are removed that have an identical copy as saved in the wsltty home folder (%LOCALAPPDATA%/wsltty), in order not to remove anything touched by the user.
