### ISSUE TITLE
Display graphical symbols in terminal

### ISSUE THREAD

**Issue by whitecolor** [mintty/wsltty#22]
I believe it is not wsltty specific and kins of basic windows terminal issue, but still will ask for it:

This is neovim UI:

Is it possible to have instead of this (questions in squares):
![image](https://cloud.githubusercontent.com/assets/736697/21933798/a1fbf6f4-d9c8-11e6-97cc-0b870fd259a6.png)

Normal graphical characters as it in mac/linux:
![image](https://cloud.githubusercontent.com/assets/736697/21933806/b056e2ea-d9c8-11e6-8013-6d458ce1144f.png)

**Comment by mintty** [comment]
How do you start the terminal? What font is configured? And:
What neovim do you run? I don't see any on WSL and apt-get doesn't find one.

**Comment by whitecolor** [comment]
The screen shows https://github.com/vim-airline/vim-airline plugin for vim/neovim, so my flow to get it:

- I start terminal from icon on deskop
![image](https://cloud.githubusercontent.com/assets/736697/21943296/76163052-d9f2-11e6-99d9-9fab1171a6a4.png)
- text options:
![image](https://cloud.githubusercontent.com/assets/736697/21943309/82f95fb0-d9f2-11e6-9c52-f4c210a33b56.png)
- to install neovim
  $ sudo add-apt-repository ppa:neovim-ppa/unstable  
  $ sudo apt-get update
  $ sudo apt-get install neovim
- then I install [dein.vim plugin manager](https://github.com/Shougo/dein.vim):
  $ curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
  $ sh ./installer.sh /dein.vim
- after this create `~/.config/nvim/init.vim` and insert shown script after dein.vim install, and add plugins:
```
   call dein#add('vim-airline/vim-airline')
   call dein#add('vim-airline/vim-airline-themes')
```
(as show on first screen)
- save file
- restart nvim, run inside nvim `:call dein#install()` to install plugins.

**Comment by mintty** [comment]
Doesn't work here, please quote the complete init.vim file as needed.

**Comment by whitecolor** [comment]
```
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/dein.vim/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/dein.vim')
  call dein#begin('/dein.vim')

  " Let dein manage dein
  " Required:
  call dein#add('/dein.vim/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('Shougo/neosnippet.vim')
  call dein#add('Shougo/neosnippet-snippets')

  call dein#add('vim-airline/vim-airline')
  call dein#add('vim-airline/vim-airline-themes')

  " You can specify revision/branch/tag.
  call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts-------------------------
```

**Comment by mintty** [comment]
Here the status line looks like this (with normal less/greater characters):
` NORMAL >> [No Name]                                        <<< 100% :   0:  1 <`

`:call dein#install()` fails:
[dein] You may have used the wrong plugin name, or all of the plugins are already installed.
Press ENTER or type command to continue

**Comment by whitecolor** [comment]
It is ok plugin is installed and enabled. `:call dein#install()` fails because you have plugins installed due to

```
" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
```

So can you post a screenshot? I have this "squared question marks" symbols (near Normal, and on the right too):
![image](https://cloud.githubusercontent.com/assets/736697/21946683/569dfd98-da03-11e6-8cde-342c281ff014.png)

**Comment by mintty** [comment]
Apparently nvim isn't configured here as to output those symbols, yet.
It will be more useful if you post a screen copy (not screen shot) of that line; mark with Shift+mouse-drag, paste into a file to upload here, or directly in here. So I check which characters are actually being output and whether I can reproduce their rendering, without needing to get nvim run alike.

**Comment by whitecolor** [comment]
You see here:
http://vi.stackexchange.com/questions/3359/how-to-fix-status-bar-symbols-in-airline-plugin

it is proposed to add symbols manually:

```
" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''
```

When I insert those symbols in the terminal, I got:
![image](https://cloud.githubusercontent.com/assets/736697/21947196/b523d48a-da05-11e6-8357-31e4fcc434e1.png)

**Comment by mintty** [comment]
Add the following option (config file or command line in your desktop shortcut):
`FontRender=uniscribe`

**Comment by whitecolor** [comment]
![image](https://cloud.githubusercontent.com/assets/736697/21955837/af36d196-da94-11e6-886b-c7f029cd9716.png)

No effect. Does it wok for you?

**Comment by mintty** [comment]
Yes, it makes the `" unicode symbols` section render well, but not the `" airline symbols` section because those characters use unassigned Unicode code points which can only render if you use a special font with proprietary mappings in those code points.
![image](https://cloud.githubusercontent.com/assets/12740416/21956189/8c571ec4-da7b-11e6-8bc8-080961222d13.png)

**Comment by whitecolor** [comment]
hm, I still don't have unicode symbols:

![image](https://cloud.githubusercontent.com/assets/736697/21956250/583839d4-da9e-11e6-8364-696e5a147603.png)

**Comment by mintty** [comment]
Maybe the font fallback mechanism does not find a suitable font that would contain the characters?
Please install DejaVu fonts and try again.

**Comment by whitecolor** [comment]
Should I install them in Windows or in ubuntu?

**Comment by whitecolor** [comment]
Ah ok, I changed the font in the options. to use DejaVu.

**Comment by whitecolor** [comment]
Ah ok, I changed the font in the options. to use DejaVu. Ok just need to use fonts from here https://github.com/powerline/fonts. Thanks.

The question: is it possible somehow to use different fonts inside the console?

**Comment by mintty** [comment]
* Fonts for mintty need to be installed in Windows (mintty is a cygwin program).
* You had DejaVu already installed? Or have it installed and using a *different* font does not show the characters? That was actually my question, about font fallback tweaking.
* Different fonts: you mean in mintty, at the same time? This had been requested before (#418) and is not a feature.

**Comment by whitecolor** [comment]
Now it is all workingthis ok, I have patched `consola` font using https://github.com/ryanoasis/nerd-fonts

![image](https://cloud.githubusercontent.com/assets/736697/21962236/b2804176-db42-11e6-924f-d6e93faff965.png)

**Comment by mintty** [comment]
Thanks for the nerd link, I suppose that would enable the "airline symbols".
Yet it would be useful to find out why the "unicode symbols" didn't work for you while they work here without any patching (with `-o FontRender=uniscribe`; I guess I should make that the default).

**Comment by whitecolor** [comment]
Yes nerd-font patcher has a lot of glymps that can be injected in the font including `airline symbols`. Indeed `fontRender=uniscribe` not needed. Think issue may be closed now.

**Comment by daviecar21** [comment]
Sorry for starting up this thread again but can you just please post a step by step instruction manual? I can't seem to follow what you guys are doing... Thanks!

**Comment by whitecolor** [comment]
@daviecar21 you just need to make (get) a font that contains glyphs, install and set it in the mintty Text options.

You can get ready to use Consolas font here: https://github.com/whitecolor/my-nerd-fonts

**Comment by mahoney-lgn** [comment]
@whitecolor Hey I just made my first github account to say thanks for posting your solution. You helped me out!

**Comment by roachsinai** [comment]
Sorry for starting up this thread again, too. @whitecolor did you try win 1809 update? After the 1809 update the symbols not work for me (1803 works well), I have tried the font you paste the link.

**Comment by mintty** [comment]
Please check whether, after the update, your special fonts are still installed.
For me, the "unicode symbols" are still displayed fine, Windows 1809.

**Comment by mintty** [comment]
This looks quite different from the problem initially described in this issue, and confusing.
Please describe completely and precisely what does not work for you and how it can be reproduced.

**Comment by roachsinai** [comment]
You mean a new issue?

**Comment by mintty** [comment]
That's not the point, as you like. I mean a clear description of your problem.

**Comment by roachsinai** [comment]
Sorry I'll try to make a clear description.

My sitiution: Nerd font shows well before I update win10, means symbols shows on 1803 version, and doesn't show on 1809 version.

**Comment by Erog38** [comment]
@mintty I started having this issue after the update as well. To reproduce:

1 Use Windows 10 1809
2. Fresh install of wsltty
3. Download Go Mono for Powerline from https://github.com/powerline/fonts/blob/master/GoMono/Go%20Mono%20for%20Powerline.ttf  

4. %APPDATA%/wsltty/config:
BoldAsFont=yes
Font=Go Mono for Powerline
FontWeight=200
FontHeight=11
FontSmoothing=full
Transparency=medium
Locale=en_US
AllowBlinking=yes
ClipShortcuts=yes
Rows=25
Language=en_US
CtrlShiftShortcuts=yes
OpaqueWhenFocused=no
Scrollbar=none
PgUpDnScroll=yes
FontIsBold=no
ShowHiddenFonts=yes
FontRender=uniscribe
OldFontMenu=yes

Everything was dandy before the 1809 update. Some symbols show properly, but others do not. If I can provide any more information please let me know.

**Comment by mintty** [comment]
I'm not sure that the current issue is the same as originally reported here.
However, I think it's the same as #130.

**Comment by Memphizzz** [comment]
I experience the same Issue after upgrading to 1809 just a few minutes ago. I've been using IBM Plex Mono Text on Medium 12pt. The symbols are either missing or way too big and get cut off. I've tried reinstalling all *.otf files of that font, but no luck.

**Comment by mintty** [comment]
> I experience the same Issue

This issue has become quite long and it is not clear whether all commenters are having the same problem.
So please describe your issue, including a reproducible test case, i.e. text being output, link to font being used.

**Comment by gartnera** [comment]
Today I upgraded to 1809. I experienced the same issue. I tried a couple a bunch of different fonts. Of those, only this one worked: https://github.com/powerline/fonts/tree/master/DejaVuSansMono

**Comment by roachsinai** [comment]
Thanks @gartnera though I prefer mononoki. https://github.com/powerline/fonts/tree/master/DejaVuSansMono works.

**Comment by zot** [comment]
Hmm, the nerd fonts that work with the new windows terminal aren't working for me (not showing the git branch symbol) but the Source Code Pro font is.

**Comment by mintty** [comment]
See my previous comment.
