### ISSUE TITLE
Question: Key remaps possible in config

### ISSUE THREAD

**Issue by eL0ck** [mintty/wsltty#222]
How reasonable would it be to provide a config option to remap certain keys?

I'm new to windows and really want/need to remap CAPS to ESC.  Any other proposed solutions would be graciously accepted but just want to test the waters here to estimate effort required to implement this within wsltty itself.

**Comment by mintty** [comment]
This would be a feature of mintty, the terminal part of wsltty.
Have you checked whether this could easily be achieved with some desktop tool (e.g. AutoHotKey) or even with Windows native means (you _can_ create your own keyboard mapping)?
If you think those don't work or are not suitable, we can look for a mintty config solution.

**Comment by mintty** [comment]
Actually, remapping CAPS to ESC is already possible, just not the other way round.
`KeyFunctions=CapsLock:""`
where the character inside the double quotes needs to be a verbatim ESC in the mintty config file.

**Comment by eL0ck** [comment]
Thanks @mintty .  Much appreciated
