### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by jefferai** [mintty/wsltty#223]
I wanted to uninstall because reinstalling/upgrading this after adding a distro caused some failures (icons couldn't be found on launch, etc.)

So I cloned the repo and run uninstall.bat, but it doesn't work -- I get `config-distros.sh: 1: cd: can't cd to "C:\Users\Jeff\AppData\Local\wsltty"` even though that directory is valid and I can do it myself just fine.

How can I clean this up? I like it, I just want to clean it up to reinstall.

**Comment by Biswa96** [comment]
This issue may be similar with your situation https://github.com/mintty/wsltty/issues/218.

**Comment by mintty** [comment]
Hadn't noticed this issue before, sorry.
Analysing, the `cd` did not work at all - bummer!
Rethinking, I had overlooked that `cd` in `cmd` cannot change drive without an additional `/D` parameter. That is missing...

**Comment by mintty** [comment]
Released 3.1.4.
