### ISSUE TITLE
How to enable encoding charset GB18030?

### ISSUE THREAD

**Issue by nobk** [mintty/wsltty#224]
WSL ubuntu support GB18030 encoding(Microsoft windows code page 54936), in wsltty settings there is only GBK(Chinese), but in source code https://github.com/mintty/mintty/blob/master/src/charset.c defined GB18030, is there any way to make it work?

**Comment by mintty** [comment]
Cygwin does not support a GB18030 locale and it would not make much sense if the terminal adds such support while all tools, including the shell, do not know how to interpret it.
You may ask on the cygwin mailing list.

**Comment by mintty** [comment]
How would you actually set up GB18030 for Ubuntu?

**Comment by nobk** [comment]
> 
> 
> How would you actually set up GB18030 for Ubuntu?
1. `sudo vi /var/lib/locales/supported.d/local`
 add a line
`zh_CN.GB18030 GB18030`

2. `sudo locale-gen`

3. `sudo vi /etc/vim/vimrc `
add
```
let &termencoding=&encoding
set fileencodings=utf-8,gb18030
```
4. `sudo vi /etc/environment`
add
```
LANGUAGE="zh_CN:zh:en_US:en"
GST_ID3_TAG_ENCODING=GB18030
LANG=zh_CN.GB18030
LC_CTYLE=zh_CN.GB18030
```
quit wsl and relogin

I want try GB18030 because it full support all Unicode code point like UTF-8, and more friendly to Asia CJK character users.

**Comment by mintty** [comment]
Following your instructions, I did not get Ubuntu (in Windows console) to run in GB18030, it still has a UTF-8 locale. Maybe it works only within a respective Windows language configuration?

**Comment by nobk** [comment]
/etc/environment only work for GUI, CLI need modify $HOME/.bashrc or $HOME/.zshrc
add line
```
export LANGUAGE="zh_CN:zh:en_US:en"
export LANG=zh_CN.GB18030
export LC_CTYLE=zh_CN.GB18030
```
Set wsltty settings encoding to GBK(Chinese), save and quit wsltty and restart.
This will have partial GB18030 support.

**Comment by mintty** [comment]
I cannot reproduce your result, the console window is not set to run GB18030:
$ chcp.com 54936
$ LC_ALL=zh_CN.gb18030 bash
$ locale charmap
GB18030
$ echo ö | od -t x1
0000000 c3 b6 0a

That is still UTF-8.

**Comment by nobk** [comment]
I am not using console window, I use wsltty and set GBK as encoding, it partial work with GB18030.
The test case is failed, because GBK not support 4 bytes mbchar of GB18030.

**Comment by mintty** [comment]
OK. Actually, mintty has some built-in handling of GB18030 already (https://sourceware.org/ml/cygwin/2010-03/msg00929.html), activated with an explicit option Charset=GB18030 (not available interactively). It does not seem to work, however.
Also, GB18030 support for cygwin was discussed in the past:
https://sourceware.org/ml/cygwin-developers/2010-03/msg00040.html
https://sourceware.org/ml/cygwin-developers/2010-02/msg00026.html
but not pursued further due to API design problems:
https://sourceware.org/ml/cygwin-developers/2010-02/msg00027.html
https://sourceware.org/ml/cygwin-developers/2010-02/msg00028.html

**Comment by mintty** [comment]
Don't know what affected my previous test case. On another machine this works fine:
`mintty -o Locale=C -o Charset=GB18030`

**Comment by mintty** [comment]
Previous test report was with cygwin. Repeated with Ubuntu, invoked from mintty via wslbridge2 (like in wsltty).
It works.

**Comment by nobk** [comment]
Well that's good news.
I am using wsltty by file explorer popup menuitem 'WSL Terminal', which registry entry should I change by using regedit?

**Comment by mintty** [comment]
I could dig out the reg keys but if it is your general preference, I'd say it's better to add it to your %APPDATA%/wsltty/config file.

**Comment by mintty** [comment]
For cygwin, I have enhanced GB18030 support to set up the client locale as GBK at least (as GB18030 is not supported in cygwin).
Documented GB18030 support, also for WSL, in the mintty wiki Tips.

**Comment by mintty** [comment]
There is a caveat still: you'd have to give parameter `--WSL` first, then `Charset` on the command line (and not just via config file) as --WSL implies Charset=UTF-8, on the previous assumption WSL would always run in UTF-8.

**Comment by nobk** [comment]
I can not compile wsltty because no cygwin installed. I use mintty with WSL and MSYS2.
When wsltty have new release with this patch I will try. Thank you!

**Comment by nobk** [comment]
When I install wsltty 3.1.4 and edit %APPDATA%/Roaming/wsltty/config change `Charset=RG18030` , test case pass!

**Comment by mintty** [comment]
Thanks for feedback.
I guess there may still be a problem lurking: width handling of "ambiguous width" characters, like "ü", Greek or Cyrillic letters.

**Comment by mintty** [comment]
Thanks; forgot to close it after the release.
