### ISSUE TITLE
message on startup: ioctl(SIOCGIFADDR): No such device

### ISSUE THREAD

**Issue by sullyj3** [mintty/wsltty#225]
Is printed above the shell prompt. Apologies if this isn't specifically a wsltty issue, I'm not sure where the message comes from or how to go about tracking it down.

**Comment by Biswa96** [comment]
Could you provide some information about the issue? Like Windows 10 version? WSL1 or WSL2? What are the network interfaces in WSL? Did you add any network settings in WSL?

**Comment by sullyj3** [comment]
Windows 10 build 19041.21
```
PS C:\Users\James> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         1
```

```
james at SurfaceLaptop in ~
❯ ip link show                                                             00:27
1: lo: <LOOPBACK,UP> mtu 1500 group default qlen 1
    link/loopback 00:00:00:00:00:00
19: wifi0: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    link/ieee802.11 c4:9d:ed:9a:26:3f
10: wifi1: <> mtu 1500 group default qlen 1
    link/ieee802.11 c6:9d:ed:9a:27:3e
16: wifi2: <> mtu 1500 group default qlen 1
    link/ieee802.11 c6:9d:ed:9a:22:3e
```

I haven't changed anything network related in WSL, as far as I can recall.

**Comment by Biswa96** [comment]
Ohh... It's my fault. wsltty uses [wslbridge2][1]. I added an environment variable `WSL_GUEST_IP` in wslbridge2 backend with which users can access `eth0` IP address. But that virtual network interface is available for WSL2 only. I forgot to add the check. 

Workaround: Open the [wslbridge2][1] repository, open the Appveyor build badge, download the artifact in Ubuntu build, place it in `C:\Users\UserName\AppData\Local\wsltty\bin` path.

[1]: https://github.com/Biswa96/wslbridge2.git

**Comment by Biswa96** [comment]
Here is a direct link https://ci.appveyor.com/project/Biswa96/wslbridge2/build/job/5nf74gvc6i8ai9mn/artifacts. Valid for 6 months only.

**Comment by sullyj3** [comment]
Cool, seems like it worked!

**Comment by mintty** [comment]
Is this still an issue or can we close it?

**Comment by Biswa96** [comment]
Yes, this can be closed.
