### ISSUE TITLE
Doesn't seem to work with imported distros

### ISSUE THREAD

**Issue by rhaglennydd** [mintty/wsltty#226]
I recently migrated a WSL Ubuntu 18.04 distro from another machine by running `wsl --export` to a tar and `wsl --import` from that tar. I verified it was installed with `wsl -l` and then ran `bash`, no problems. I then ran the WSLtty installer, but none of the generated shortcuts work. A terminal window pops up then quickly disappears. I noticed that they all call mintty.exe with the argument `--wsl=`. I tried adding `Ubuntu-18.04` to the parameter value, but that made no difference. I ran the "configure WSL shortcuts" shortcut, but that didn't do anything. Then I copied the command from that shortcut and ran it in cmd.exe and got this output:

    C:\Users\[MY_USERNAME]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WSLtty>C:\Users\[MY_USERNAME]\AppData\Local\wsltty\bin\dash.exe /config-distros.sh %bridgeargs%
    Active code page: 65001
    distro 'Ubuntu-18.04'
    - name 'Ubuntu-18.04'
    - guid {3cedf58d-9f63-4f6c-b1cf-6fa4c2ef6f04}
    - (launcher C:\Users\[MY_USERNAME]\AppData\Local/Microsoft/WindowsApps/Ubuntu-18.04.exe)
    - icon C:\Users\[MY_USERNAME]\AppData\Local/lxss/bash.ico
    - root \\?\C:\Users\[MY_USERNAME]\Ubuntu-18.04
    Setting +x wslbridge2 backends for distro 'Ubuntu-18.04'
    Input Error: Can not find script file "C:\Users\[MY_USERNAME]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WSLtty\mkshortcut.vbs".
    The file cannot be copied onto itself.
            0 file(s) copied.
    Creating Ubuntu-18.04.bat
            1 file(s) copied.
            1 file(s) copied.
    Input Error: Can not find script file "C:\Users\[MY_USERNAME]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WSLtty\mkshortcut.vbs".
    The system cannot find the file specified.
    Creating Ubuntu-18.04~.bat
            1 file(s) copied.
            1 file(s) copied.
    distro ''
    - name 'WSL'
    - guid DefaultDistribution
    - (launcher C:\Users\[MY_USERNAME]\AppData\Local/Microsoft/WindowsApps/Ubuntu-18.04.exe)
    - icon C:\Users\[MY_USERNAME]\AppData\Local\wsltty\wsl.ico
    - root \\?\C:\Users\[MY_USERNAME]\Ubuntu-18.04
    Input Error: Can not find script file "C:\Users\[MY_USERNAME]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WSLtty\mkshortcut.vbs".
    The file cannot be copied onto itself.
            0 file(s) copied.
    Creating WSL.bat
            1 file(s) copied.
            1 file(s) copied.
    Input Error: Can not find script file "C:\Users\[MY_USERNAME]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WSLtty\mkshortcut.vbs".
    The system cannot find the file specified.
    The system cannot find the file specified.
    Creating WSL~.bat
            1 file(s) copied.
            1 file(s) copied.

Some comments on this:

- There is no file `C:\Users\[MY_USERNAME]\AppData\Local/Microsoft/WindowsApps/Ubuntu-18.04.exe`
- There is no file `C:\Users\[MY_USERNAME]\AppData\Local/lxss/bash.ico`. Matter of fact there's no directory `C:\Users\[MY_USERNAME]\AppData\Local/lxss`
- The contents of `C:\Users\[MY_USERNAME]\AppData\Local\Microsoft\WindowsApps\Ubuntu-18.04.bat` include the command `%LOCALAPPDATA%\wsltty\bin\mintty.exe -i "%LOCALAPPDATA%/lxss/bash.ico" --WSL="Ubuntu-18.04" --configdir="%APPDATA%\wsltty"  - %*`. When I run this from cmd.exe, a window pops up with an error message but closes before I can read it. How do I get it to stay open?

If WSLtty does not support imported distros you should say so. Any advice on what I can do?

**Comment by mintty** [comment]
Thanks for the debugging attempt and diagnostic information with your report.
To replay the "configure WSL shortcuts" shortcut manually, you should go into the directory that's intended for it (in the shortcut):
`cd %LOCALAPPDATA%/wsltty`
in order to avoid this error:
> Input Error: Can not find script file "C:\Users\[MY_USERNAME]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WSLtty\mkshortcut.vbs".

I'll look into the issue with imported distros, need to set one up first. (Is an exported distro tar available somewhere for download?)

**Comment by rhaglennydd** [comment]
Thank you, that fixed 99% of the problem. The one thing it didn't fix is the "Ubuntu-18.04 Terminal" shortcuts (with and without % at the end) are still missing icons (because the script expects the icon to be in that lxss directory, but there is no such directory if the only distro has been imported).

Do you have Dropbox or Google Drive? I can privately share my exported tar file with you. Otherwise, just install a distro from the Windows Store and export it with `wsl --export`.

**Comment by mintty** [comment]
> Thank you, that fixed 99% of the problem.

Great. Which doesn't expect, though, why it did not work when you ran the script by clicking its shortcut.
I've exported kali-linux. The tar file does not include any icon. In that case, the wsltty config should use the default icon (the penguin) from %LOCALAPPDATA%/wsltty/wsl.ico.

**Comment by mintty** [comment]
Is this fixed with 3.1.4?

**Comment by Conduitry** [comment]
This is not working for me with 3.1.4. The main `WSL Terminal.lnk` and `WSL Terminal %.lnk` shortcuts use `%LOCALAPPDATA%\wsltty\wsl.ico` as their icon, which works - but the other shortcuts that are created by the 'configure WSL shortcuts' start menu command for `--import`ed distros are created with `%LOCALAPPDATA%/lxss/bash.ico`, which does not exist, and which causes the 'Could not load icon ...' error from mintty upon startup. (After clicking 'I see', it appears to run normally.) If I manually change the icon on the shortcuts to `%LOCALAPPDATA%\wsltty\wsl.ico` (or any other existing icon), all seems well.

**Comment by Conduitry** [comment]
Editing the fallback [here](https://github.com/mintty/wsltty/blob/00c4c2f20b2fa69660c6127ddb7daedb3942cbf0/config-distros.sh#L228) to instead be `icon="$installdir"'\wsl.ico'` like it is [a few lines higher](https://github.com/mintty/wsltty/blob/00c4c2f20b2fa69660c6127ddb7daedb3942cbf0/config-distros.sh#L220) seems to work for me.

**Comment by mintty** [comment]
Thanks. The else branch should actually catch initial legacy WSL ("Bash on Windows") for which both that icon would exist and the deviating setting
    	root="$basepath"
would match. The latter wouldn't fit your imported distro, I suppose; on the other hand, it seems to be obsolete anyway as mintty checks some stuff itself now when started. To be checked.

**Comment by mintty** [comment]
Released installer 3.1.4.2, please check.

**Comment by Conduitry** [comment]
Thanks for the release! Yup your adjustment on top of my PR looks good and seems to be working.
