### ISSUE TITLE
Font issue and theme question

### ISSUE THREAD

**Issue by dylanpjx** [mintty/wsltty#227]
Encountering this issue when I launch WSLtty from start menu. I'm trying to use Fira Code bold, I have installed the font both on WSL and on Windows and it's somehow not working on launch.

![image](https://user-images.githubusercontent.com/42106466/75649105-13c45700-5c8d-11ea-954b-6c08cd25228e.png)

I can however select the font in the options menu and the terminal will update accordingly, it somehow gives me the error on launch though
![image](https://user-images.githubusercontent.com/42106466/75649154-3c4c5100-5c8d-11ea-81cd-f0d01e4da65b.png)

I'm currently using 3.1.0.2 WSLtty, and I'm running Ubuntu for WSL.

Also, side question, is there a way to theme the terminal using itermcolors? Or do I have to convert from itermcolors to js and then add it to themes?

**Comment by dylanpjx** [comment]
After I raised the issue, I went to change the font a bunch from Consolas to some other powerline font and the font issue somehow fixed by itself.

**Comment by mintty** [comment]
Fonts need to be installed in Windows.
The overly complex iterm theme format is not directly supported (as e.g. via drag-and-drop).
I don't know itermcolors, is it a tool? If it loads a theme directly into a terminal, it could work. Please provide a link to the tool.

**Comment by mintty** [comment]
About the .itermcolors theme format: the iTerm2 Color Schemes project offers a bunch of ports; the mobaxterm format could be used as mintty theme files: https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/mobaxterm
Also considering to support import of that format directly, e.g. by drag-and-drop.

**Comment by mintty** [comment]
> Also considering to support import of that format directly, e.g. by drag-and-drop.

Done.

**Comment by mintty** [comment]
Released 3.2.0 with drag-and-drop iTerm2 color scheme import.
