### ISSUE TITLE
.bash_history gets truncated to 2000 lines on startup

### ISSUE THREAD

**Issue by inoue-katsumi** [mintty/wsltty#233]
I set 2 lines below in all places.
export HISTFILESIZE=4000
export HISTSIZE=4000

But whenever  wsltty is started, ~/.bash_history file got truncated to 2000 lines.
This doesn't happen with Windows Terminal.

**Comment by Biswa96** [comment]
Check `.bashrc` and `.bash_profile` file if those variables are set.

**Comment by Biswa96** [comment]
This does not look like wsltty issue. Check `.bashrc` and `.bash_profile` file if those variables are set.

**Comment by mintty** [comment]
It's not wsltty history, so not an issue here.
