### ISSUE TITLE
Disable bold fonts?

### ISSUE THREAD

**Issue by flocc** [mintty/wsltty#235]
How do i disable bold fonts? I think i tried everything ("Show bold" in options, config file).

**Comment by mintty** [comment]
I've occasionally wondered why people would want to disable bold.
However, there's option `SuppressSGR=1`.

**Comment by flocc** [comment]
I've tried that already (SuppressSGR=1 in AppData\Roaming\wsltty\config), didn't work. 
I'm on Windows 10 Pro (2004 build) if that matters.

I think it's OCD. Text just looks better for me without mixing font weights. 
I always disable bold in vim themes etc. 

It's much nicer if i can do it globally in wsltty (SuppressSGR=1), but it doesn't work for me.

**Comment by mintty** [comment]
> AppData\Roaming\wsltty\config

That's a relative path. What's the full location of your config file? What's the setting of %APPDATA%?

**Comment by flocc** [comment]
C:\Users\flocc\AppData\Roaming\wsltty is full location
SuppressSGR=1 should override everything terminal renders right? I mean vim themes, htop, ls --color=auto, etc.

**Comment by mintty** [comment]
Please check whether you have a final space appended to SuppressSGR=1.
I've just checked that this spoils the setting...

**Comment by flocc** [comment]
It works now, thanks!

**Comment by mintty** [comment]
Fixed option parsing to tolerate space.

**Comment by mintty** [comment]
Released 3.2.0.

**Comment by kohane27** [comment]
@mintty thank you for the option `SuppressSGR=1`.
My use case is a bit different. I'm using [LSD (LSDeluxe)](https://github.com/Peltoche/lsd).
I need to set `SuppressSGR=1` or else the bold will get 2x the normal bold:

![2021-03-21_blur(1)](https://user-images.githubusercontent.com/57322459/111900246-60cbc480-8a6c-11eb-8e90-387cfd0c4d5a.png)

**Comment by mintty** [comment]
What is "normal bold" and what do you get? This description is very fuzzy. Note that mintty has the option to display bold as both colour and font, maybe that's what you see.
