### ISSUE TITLE
Installation Failure, No Shortcuts

### ISSUE THREAD

**Issue by matthew-nm** [mintty/wsltty#237]
I'm running Windows 10 19041 and Ubuntu WSL 2.

When I install via the installer 'wsltty-3.1.4-install-x86_64.exe', I see a terminal window that pops up, scrolls through a bunch of text very quickly, and then disappears. I then see a popup stating that the install has completed successfully. 

However, no shortcuts of any kind have been created, and I can't seem to find a way to launch wsltty.

I noticed that some users were having the same issue because of issues with their username having spaces, but mine is only lowercase letters.

Is there a log of the terminal output so I can see what the issue is? In either case, I would like some help creating these shortcuts for my Ubuntu installation.

Thanks.

**Comment by mintty** [comment]
An installer update is under preparation. This issue got unnoticed after the previous release until a few days ago, sorry.

**Comment by matthew-nm** [comment]
Glad it's being worked, thanks!

**Comment by mintty** [comment]
Released installer 3.1.4.2, please check.

**Comment by matthew-nm** [comment]
Works, thanks!
