### ISSUE TITLE
Custom opacity value

### ISSUE THREAD

**Issue by whitecolor** [mintty/wsltty#24]
Think would be useful to have ability to set distinct custom opacity value.

**Comment by mintty** [comment]
See https://github.com/mintty/mintty/issues/140#issuecomment-108888689
and the manual page http://mintty.github.io/mintty.1.html
about numeric values for option `Transparency`.
(I'll add a direct link to the manual page to the wsltty project page.)

**Comment by mintty** [comment]
Closing this issue (link to manual page available);
if someone wants interactive configuration (Transparency slider, mintty/mintty#140),
someone will have to demonstrate how this is done on the Windows API.
