### ISSUE TITLE
Transparency glass mode doesn't work correctly

### ISSUE THREAD

**Issue by ProximaB** [mintty/wsltty#241]
## Changing to full screen and back to window mode change the background color to blue.
[<img width=400 src="https://user-images.githubusercontent.com/15923605/79577787-9716fc00-80c5-11ea-9987-2beb4deaf07a.png"
/>](https://user-images.githubusercontent.com/15923605/79577787-9716fc00-80c5-11ea-9987-2beb4deaf07a.png)

**Comment by mintty** [comment]
Not reproduced. Must be related to some weird local configuration on your side, please test while minimizing your setup, also running without tmux etc.

**Comment by ProximaB** [comment]
I can reproduce it without tmux and the same problem occurs when enabling `Opaque when focused.`
Yes, probably my configuration. If I find answer I'll post it here.

**Comment by mintty** [comment]
When responding before I was distracted by you mentioning "full screen mode" but there is no full screen in your screen movie. Also I overlooked you mentioned glass mode in the title. Glass is not really supported anymore in Windows 10, that's been discussed in other issues already. The white background is a symptom of this limitation.

**Comment by ProximaB** [comment]
I found that issue about glass and saw you mention that you're thinking about removing that option from the menu.
When can we expect that will be done? :) Would it be possible to smoothly change transparency with a slider?

**Comment by mintty** [comment]
If you found a related issue, please quoted it here.
As you're asking, I think I'll remove the glass option for the next release.

About a slider, as you found the issue, you probably also saw the answer; it's in https://github.com/mintty/mintty/issues/728#issuecomment-357204019.

**Comment by mintty** [comment]
Released 3.2.0.
