### ISSUE TITLE
Cannot select text in terminal using keyboard.

### ISSUE THREAD

**Issue by pontakornth** [mintty/wsltty#242]
It's pretty stupid but when I tried to select text using Shift+Arrow key, it just insert a character A,B,C, or D base on my input. Mouse seems to work fine. It's affect all of the program including Vim and Tmux. 

I would like to select I  the command I type.

# Steps:
1. Open the terminal
2. Type any command.
3. Attempt to select with command with Shift+Left Arrow.
4. D letter should be here.

I never use any previous version before so I couldn't say about that.

# Expectation:
1. Text should be highlighted.

# Other info.
1. Selecting works in normal WSL terminal but I can't use Tmux because font will change. 
2. Selecting doesn't work in any application like Vim (insert mode) and Tmux.

I use ZSH as a shell with xterm-256colors. I also set the scroll key to PgUp/PgDown.

Edit: Add better report.

**Comment by mintty** [comment]
If you think it's motivating to care about a bug report by threatening the software would otherwise be useless, you should at least provide a decent report. What's the context, in which program do you wish to select by keyboard? Did it work before and in which version? What exactly do you expect? Why do you think it should work? Does it work with any other terminal and which? Etc.

**Comment by mintty** [comment]
You may want to disable Shift as the "Modifier for scrolling" on the Window tab of the Options dialog.

**Comment by pontakornth** [comment]
> If you think it's motivating to care about a bug report by threatening the software would otherwise be useless, you should at least provide a decent report. What's the context, in which program do you wish to select by keyboard? Did it work before and in which version? What exactly do you expect? Why do you think it should work? Does it work with any other terminal and which? Etc.

Sorry, I guess that is too harsh. I mean it's not reallt usuable now. Sorry.
