### ISSUE TITLE
wsltty tabbed?

### ISSUE THREAD

**Issue by gostalj** [mintty/wsltty#245]
Any chance of replacing mintty with fatty so as to be able to tab the sessions?

Nice to get a more linux-like wsl experience BTW, e.g. middle mouse pastes as expected. :-)

/gostalj

**Comment by gostalj** [comment]
Fatty not an option. Good to know! Tabs work in progress. Sounds promising!

Middle mouse button paste is as old as the hills, nearly. It was very frustrating to try and get used to right button paste in the windows wsl shell. Good riddance of that!

**Comment by mintty** [comment]
Released 3.4.1.
