### ISSUE TITLE
WSLtty closes immediately with backend error

### ISSUE THREAD

**Issue by nyuszika7h** [mintty/wsltty#246]
I'm on Windows 10 2004 (19041.264) with an Ubuntu 20.04 distro converted from WSL1. It's been working fine across multiple reboots, but today after I shut down my computer and booted it again, trying to start wsltty results in this error and it immediately closes:

```
note: backend error output: /bin/sh: 1: exec: /mnt/c/Users/nyuszika7h/AppData/Local/wsltty/bin/wslbridge2-backend: Input/output error
```

The WSL distro itself works fine from the normal Windows terminal.

```
C:\Users\nyuszika7h>wsl --list -v
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

I've tried reinstalling the latest version of WSLtty but that didn't fix the issue.

**Comment by Biswa96** [comment]
Did you try with WSL1?

I can't test the latest release in my system as here Ethernet is damanged due to cyclone.

**Comment by nyuszika7h** [comment]
Looks like this is not a WSLtty issue, I cannot access drvfs at all from WSL now...

```
ls: cannot access '/mnt/c': Input/output error
```
