### ISSUE TITLE
Releases kept in sync with mintty?

### ISSUE THREAD

**Issue by pagerc** [mintty/wsltty#249]
Just an observation, but I'm wondering why there's a couple month lag between mintty and wsltty releases.

I'm excited for wsltty getting the fixes through mintty 3.1.8, especially the font glyph rendering issues being resolved.

**Comment by mintty** [comment]
Case 2: wsl launching mintty, is not possible. wsl enters WSL and mintty starts from the Windows environment.
Case 1: this is the default. With wsltty, you start mintty ("directly") which then runs wslbridge2.
Case 3: mintty running wsl directly, without wslbridge2. This would be possible but is not desirable from the terminal point of view. There would be little benefit over running only wsl, without mintty.
