### ISSUE TITLE
Error: Could not fork child process

### ISSUE THREAD

**Issue by gaia** [mintty/wsltty#25]
Always worked fine, but this started happening today:

**1st Window:**
`453785 [main] mintty 15304 fork: child -1 - forked process 23852 died unexpectedly, retry 0, exit code 0xC0000142, errno 11`

**2nd Window:**
`Error: Could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required; see 'rebaseall / rebase --help'.`

uninstalled via uninstall.bat, re-installed, problem persists.

**Comment by Alanaktion** [comment]
This seems like a duplicate of #6. I also had this issue recently, it persisted for a few weeks across multiple re-installs (even with different versions), and then randomly stopped happening for me.

**Comment by gaia** [comment]
you are right. closing.
