### ISSUE TITLE
Release 3.3.0 flagged as malicious

### ISSUE THREAD

**Issue by bgiard** [mintty/wsltty#252]
Released file [wsltty-3.3.0-install-x86_64.exe](https://github.com/mintty/wsltty/releases/download/3.3.0/wsltty-3.3.0-install-x86_64.exe) is flagged as malicious by some anti-virus software. See the [VirusTotal report](https://www.virustotal.com/gui/file/ff81442cffa8a44b0c7118be86a369c401a89c82b8cc64c71f65361dee1ac2db/detection) for instance. What's happening here?

Edit, same goes [for 3.2.0](https://www.virustotal.com/gui/file/543c3891db54cd06a55c760d18da66b88299f18e2a17001a9b3aa8688ebedfaa/detection).

**Comment by mintty** [comment]
The installer was produced the same way as for previous releases.
This is something that happens now and then for uncertified installers, see #168, #94, #74, #32, #31, #28.
I see no generic way to handle this problem.
You are welcome to install from sources as mentioned in https://github.com/mintty/wsltty/#installation-from-source-repository.

**Comment by bgiard** [comment]
Thanks, will try to do that. Just realized the Cygwin setup gets flagged as well. Probably for the same reasons.

**Comment by mintty** [comment]
I have added details about a minimal cygwin installation for that purpose to the project page.
