### ISSUE TITLE
Long command causes visual overlap

### ISSUE THREAD

**Issue by plautz** [mintty/wsltty#26]
Just downloaded the mintty terminal for WSL and I like it over the built in one that Windows offers. However, I ran into this little visual bug while typing a long command today. Not sure if it's something on my end or what, just thought this would be the place to put it.

When I type a command longer than say 85% of the window width, the command's text begins to wrap back to the prompt (on the same line) and then proceed to overwrite the letters it runs into. Take a look at the gif below.

Thanks in advance!

![mintty-wsl-overlap](https://cloud.githubusercontent.com/assets/16789181/23002967/92ddce38-f3bb-11e6-8b43-db067109759f.gif)

**Comment by Alanaktion** [comment]
This is most likely a problem with your custom `PS1` prompt. If you don't implement the ANSI color codes just right, bash can get confused about the line lengths. The default WSL prompt doesn't have this issue.

**Comment by plautz** [comment]
Yes that was it, I changed from escape sequences to `tput` and my problem was solved! Thank you!

**Comment by mintty** [comment]
In bash, you can also embed non-printing characters into escaped brackets, like `\[`**[**`[44m\]` (where the bold [ in between is a literal ESC character).

Which tool is useful to produce an animated gif screenshot?

**Comment by plautz** [comment]
@mintty Yeah that was also my issue as well, thanks!

The gif screenshot tool is here, [Screen To Gif](https://github.com/NickeManarin/ScreenToGif). I use it all the time.
