### ISSUE TITLE
WSL terminal startup in blank and freeze

### ISSUE THREAD

**Issue by alxchoy** [mintty/wsltty#261]
Hi everybody,

I have a problem when open WSL terminal, this keeps in blank  when start.

![image](https://user-images.githubusercontent.com/6879696/97842556-c5e96e00-1cb5-11eb-9aea-c75ca2a98e6f.png)

Windows version is 20H2, system compilation 19042.610 and wsltty latest release (3.4.1).
I installed Ubuntu 18.0 and set wsl 2.

**Comment by mintty** [comment]
Cannot reproduce.
To separate testing, please open (Win+R) a Windows cmd:
cd %LOCALAPPDATA%\wsltty\bin
wslbridge2

**Comment by alxchoy** [comment]
Thanks for reply.

I get same issue
![image](https://user-images.githubusercontent.com/6879696/97883541-fb607c80-1cf2-11eb-8f24-c4f92989212c.png)

**Comment by Biswa96** [comment]
Weird issue! Can you provide the output from `wslbridge2.exe -x` command? The `-x` option will show another wsl.exe window with some output.

**Comment by Biswa96** [comment]
Weird issue! Can you provide the output from `wslbridge2.exe -x` command? The `-x` option will show another wsl.exe window with some output. Does this issue happen with WSL1 distros?

**Comment by alxchoy** [comment]
I get this
![image](https://user-images.githubusercontent.com/6879696/97884701-68c0dd00-1cf4-11eb-82e1-acecd3ac5b46.png)
but doesn't open a new window.

I use WSL2 with Ubuntu-1804
![image](https://user-images.githubusercontent.com/6879696/97885266-2350df80-1cf5-11eb-9106-2413abdbcdc0.png)

**Comment by Biswa96** [comment]
I am clueless about the issue. After seeing [multiple issues about WSL2/Docker][1], I am suspecting about it. One last test.
1. Download both the binaries (wslbridge2.exe and wslbridge2-backend) from here https://github.com/Biswa96/wslbridge2/releases/tag/test
2. Backup the two files of same name in `%LOCALAPPDATA%\wsltty\bin` folder.
3. Place the new two downloaded files there. Does it work?

[1]: https://github.com/microsoft/WSL/search?q=docker&type=issues

**Comment by alxchoy** [comment]
Sorry, this isn't wsltty issue.
I has to set Ubuntu like default distro for linux:  wsl --setdefault Ubuntu
because I have many linux distro and docker was set by default

Thank you very much for your time and sorry for lost your time.

**Comment by Biswa96** [comment]
No, no. I love bugs and issues with which I learn more. I am curious what the issue it with docker-desktop and wslbridge2.

**Comment by Biswa96** [comment]
No, no. I love bugs and issues with which I learn more. I am interested in the issue with docker-desktop and wslbridge2.

**Comment by alxchoy** [comment]
Pleas close this issue, thank you.

**Comment by Biswa96** [comment]
No. This is an issue of wslbridge2 (or it seems to be). I will discuss with Docker developers about this.

Disclaimer: I don't know how Docker works with WSL2 because it's not fully open source and I don't know Go programming language 👼

**Comment by Biswa96** [comment]
@simonferquel May I ask for your help?

**Comment by simonferquel** [comment]
Yes, this happens when Docker Desktop is installed and run in WSL2 mode before any other WSL distro is installed. Unfortunately, there is no way for us to register the distro without it getting the "default" tag if no other one already exists :/
The docker-desktop-data is very minimalist and does not contain any shell. It is designed to run a single executable using `wsl -e` that bind mounts stuff into /mnt/wsl to handle docker desktop data persistence.

**Comment by Biswa96** [comment]
Thank you. I understand it. I will add this in wslbrigde2 docs.

**Comment by mintty** [comment]
Could wslbridge2 detect whether the selected distribution is actually a WSL (or other) shell and return a warning then?

**Comment by Biswa96** [comment]
docker-desktop is actually a distribution (Alpine based) like thing in WSL realm. So, ¯\_(ツ)_/¯

**Comment by Biswa96** [comment]
BTW, any idea is welcomed!

**Comment by mintty** [comment]
Do they leave any non-WSL like pattern in the registry?

**Comment by Biswa96** [comment]
> non-WSL like pattern

We could just sit back while Microsoft's WSL devs do the hard work here https://github.com/microsoft/WSL/issues/6176

**Comment by Biswa96** [comment]
Another similar issue in WSL https://github.com/microsoft/WSL/issues/6274. Also similar workaround, setting Ubuntu as default distribution works in that case.

**Comment by pangyuteng** [comment]
finally was able to run `wsltty`.
+ i reinstalled wsl2, reinstalled wsltty 3.5.1 (launching wsltty resulted in a blank/haning terminal)
+ ran `wsl --shutdown` per https://github.com/mintty/wsltty#wsl-v2
+ restarted docker-desktop (gotta have it)
+ was able to run `wsltty` and run docker commands in the terminal 
👍!!! Thank you mintty!
send beer money here https://github.com/mintty/wsltty/issues/158#issuecomment-490750834
