### ISSUE TITLE
Starting wsltty with elevated privilege

### ISSUE THREAD

**Issue by suntong** [mintty/wsltty#262]
How to start `wsltty` with elevated privilege?

I cannot rename '/home' under wsl:

    cd /
    
    $ sudo mv /home home-old
    mv: cannot move '/home' to 'home-old': Permission denied

I thought about why I cannot rename '/home' under wsl and the workarounds, and I believe that the reason is, WSL is installed with elevated privilege, while my wsl bash is started with normal privilege. There are just many things that cannot be done because of that, not just moving /home, any files/folders that need elevated privilege to access cannot be altered within wsl bash.

Hence, how to start `wsltty` with elevated privilege?

**Comment by Biswa96** [comment]
Starting wsl.exe or wsltty.exe or wslbridge.exe would not gain root privilege in WSL distribution. Why on earth do you want to rename `/home` directory?

**Comment by mintty** [comment]
You could modify the invocation (e.g. in the desktop shortcut) to invoke `sudo` implicitly, but then you'll have to enter your password initially, unless your distribution would allow to configure sudo to work without password (?).
Replace `--WSL=`_distro_ with `--wsl /bin/wslbridge2 -d` _distro_. (wslbridge2 following any mintty parameters)
Replace `-~` with wslbridge2 parameter `--wsldir ~`.
Append invocation of sudo with shell.
Example:
`C:\Users\towo\AppData\Local\wsltty\bin\mintty.exe --wsl --configdir="C:\Users\towo\AppData\Roaming\wsltty"  /bin/wslbridge2 --wsldir ~ /usr/bin/sudo bash -`

**Comment by suntong** [comment]
> You could modify the invocation (e.g. in the desktop shortcut) to invoke `sudo` implicitly, but then you'll have to enter your password initially, unless your distribution would allow to configure sudo to work without password (?).

Oh thanks for your reply @mintty, I guess I wasn't very clear in my OP that, 

There are many things that I cannot do _**even**_ with `sudo` within wsltty.

What I meant by starting wsltty with elevated privilege is a very Windows-thing, For e.g., 

For opening the Command Prompt as Administrator, i.e., to open the Command Prompt with Administrative Privileges

1. Click the Start icon and click in the Search box.
1. Type cmd into the search box. You will see the cmd (Command Prompt) in the search window.
1. Hover the mouse over the cmd program and right-click.
1. Select "Run as administrator".

This is what I can't do with `wsltty` icon so far.

**Comment by mintty** [comment]
Sure you can. Windows offers a generic "Run as administrator" item in the context menu. But why would you want to run the terminal elevated? It doesn't give you anything.

**Comment by suntong** [comment]
Ah, indeed, there is "Run as administrator" item in the context menu, but not in the pined icon. 

![image](https://user-images.githubusercontent.com/422244/99116397-f2f52500-25c1-11eb-8c04-df09e0980541.png)

> why would you want to run the terminal elevated? It doesn't give you anything.

It does:

![image](https://user-images.githubusercontent.com/422244/99116673-6dbe4000-25c2-11eb-8fb8-c511226e129d.png)

I.e., I cannot do even with sudo within _normal_ wsltty, but starting wsltty with elevated privilege is OK.

**Comment by mintty** [comment]
Not reproduced. Running an un-elevated terminal, then sudo in WSL, gives me all access rights, also in /mnt/c folders.

**Comment by suntong** [comment]
You machine must have disabled UAC.
Here is how to check:

1. Open powershell or cmd.
1. Check if it says Administrator in the title
