### ISSUE TITLE
Terminal color change when tmux is running

### ISSUE THREAD

**Issue by dmbfm** [mintty/wsltty#266]
Without tmux:
![image](https://user-images.githubusercontent.com/8743306/103014872-3fffdb80-451e-11eb-8b11-8668a565402e.png)
![image](https://user-images.githubusercontent.com/8743306/103014907-4f7f2480-451e-11eb-931e-13705499ea2a.png)

with tmux:

![image](https://user-images.githubusercontent.com/8743306/103014951-5e65d700-451e-11eb-8975-834e66659e27.png)
![image](https://user-images.githubusercontent.com/8743306/103014974-66257b80-451e-11eb-8cc0-fa01037f9a88.png)

It seems like the colors get tinted by the green bar?

I'm using this version: 

![image](https://user-images.githubusercontent.com/8743306/103015019-7a697880-451e-11eb-9fb3-f2dc4578166e.png)

**Comment by mintty** [comment]
[General remark for reporters: no need to upload tons of screenshots for trivia like version...]

tmux likely intercepts colour control sequences and emits its own in turn, also it may be configured to transform attributes. Please look there first. You could analyse the sequences that mintty finally *receives* in each case to check the difference (by making an output log).
Not a terminal issue as sequences are certainly revealed to be different, so closing.

**Comment by dmbfm** [comment]
Ok, don't se a what the big deal is about screenshots. It's better than leave some detail out which could be useful

**Comment by mintty** [comment]
Yes, OK, sorry you got hit with this comment after I got flooded with screenshots in some other recent issues...
