### ISSUE TITLE
Opening links randomly switches to the browser

### ISSUE THREAD

**Issue by pcroland** [mintty/wsltty#269]
When I open a link wsltty sometimes it focuses to the browser but sometimes it does not. It seems random.
Is there something I can do so it doesn't focus to the browser?

**Comment by mintty** [comment]
You mean the link would be opened but the browser stays in the background?
I am not aware of such behaviour but even if I can reproduce it; I would wonder how to tweak it. The link is opened with a Windows function, without any explicit foreground/background manipulation.

**Comment by mintty** [comment]
Closing as out of scope of mintty.
