### ISSUE TITLE
WSL session starts as root

### ISSUE THREAD

**Issue by tnguyen14** [mintty/wsltty#270]
When I opened wsltty, it starts a session as `root`.

I don't see this behavior when I open the default Ubuntu terminal, or Windows Terminal.

I have tried uninstalling and reinstalling wsltty, but the problem is still there.

What can I do to further debug this issue?

**Comment by mintty** [comment]
It works here. No idea.

**Comment by Biswa96** [comment]
Hi @tnguyen14

* Did you change _default_ WSL user by any means, that is either with registry or with `/etc/wsl.conf` file?
* If you just type `wsl.exe` in Command Prompt what will be the user?

Also if wslbridge2 is **not** executed with `-u` or `--user` option, it will **never** change WSL user.

**Comment by tnguyen14** [comment]
Thanks @Biswa96. I tried all that you suggested, but nothing seemed odd.

Though I think I've sort of figured it out. wsltty created a bunch of different icons. I clicked `WSL Terminal`, which I think opened a different VM. If I clicked on `Ubuntu 20.04 Terminal`, it works fine.

I'm guessing the `WSL Terminal` is opening to `docker-desktop`

```
wsl.exe --list                                                                                       
Windows Subsystem for Linux Distributions:                                                                              
docker-desktop (Default)                                                                                                
docker-desktop-data                                                                                                     
Ubuntu-20.04        
```

**Comment by mintty** [comment]
Interesting resolution of this issue. There had been reports about this scenario before, however, it's curious why in your case a WSL shell starts at all when running a Docker instance. Maybe Docker has changed to provide a shell?
