### ISSUE TITLE
Behave strangely for showing sequential '=' or '-'

### ISSUE THREAD

**Issue by mingsxs** [mintty/wsltty#274]
Hi, 

sorry for raising this issue, because I found that in my wsltty terminal, all the sequential equals or dashes are concatenated to lines.
and I have tried other window terminals, like the Windows terminal, ConEmu, they all behave normally, only my wsltty will show sequential equals and dashes strangely.
I also attached some screenshots for demonstration, please have a look and it will be appreciated if there is a fix to this.Thanks
![Screenshot 2021-03-05 005324](https://user-images.githubusercontent.com/46848431/109999662-6aa3b700-7d4d-11eb-99ff-5cea5b35fa75.png)
![equals](https://user-images.githubusercontent.com/46848431/109999678-6d9ea780-7d4d-11eb-8221-1cf8c791d89a.png)
![dashes1](https://user-images.githubusercontent.com/46848431/109999692-71cac500-7d4d-11eb-8d7d-43de457751e1.png)
![dashes2](https://user-images.githubusercontent.com/46848431/109999700-742d1f00-7d4d-11eb-9f6b-c46325d46963.png)

**Comment by mingsxs** [comment]
BTW, I am using the latest x64 build, which is 3.4.5(x86_64-pc-cygwin).

**Comment by Biswa96** [comment]
Please provide some deatils about your terminal setup like font name, font size, zsh theme, any extra .zshrc file, any extra settings in .minttyrc file etc.

**Comment by mintty** [comment]
A few fonts support automatic ligatures, especially for coding symbols, and some people particularly like that (see mintty/mintty#601 and mintty/mintty#754 for some discussion). If you don't, use another font or set option `FontRender=textout`.

**Comment by mingsxs** [comment]
Yeah, the font information you mentioned is the key problem, it's because of the Microsoft font cascadia code, after changed to another font, the behavior becomes normal.
Thanks for providing this info, I am closing this question now.
