### ISSUE TITLE
Set '\r\n' for windows to '\n'

### ISSUE THREAD

**Issue by mingsxs** [mintty/wsltty#275]
Hi,

I have to say wsltty is an amazing terminal tool in windows, but I am seeing annoying trouble regarding the newline character.

I am forced to use WSL since I have to use windows desktop but I only know how to develop with Linux, when I use vim for coding, I found there are always ^M on my edited lines, as well known, this means the line feed is abnormal which is '\r\n' and I hate them.
Can I switch back to '\r' like a real normal linux? Thanks.

**Comment by mingsxs** [comment]
Hi, I am sorry, after some testing, I find out this probably is related to git instead of the terminal, sorry for causing confusion here, I am closing this issue ticket now.

**Comment by Biswa96** [comment]
> I am forced to use WSL 

Never seen this awkward situation 😨
