### ISSUE TITLE
<ffffffff> instead of russian text

### ISSUE THREAD

**Issue by habamax** [mintty/wsltty#279]
Sorry if the issue is not `wsltty` related...

When I try to input Russian text I get `<ffffffff>` instead of russian letters:

`echo привет` becomes this:
![image](https://user-images.githubusercontent.com/234774/114021788-bfb97800-9879-11eb-90bf-f19cf94f6d44.png)

On the other hand if I try wsl in `cmd.exe`:

![image](https://user-images.githubusercontent.com/234774/114021663-9ac50500-9879-11eb-9c06-88ff18f77629.png)

And if you paste it into wsltty:
![image](https://user-images.githubusercontent.com/234774/114022012-ff805f80-9879-11eb-9f09-c521272caa30.png)

**Comment by habamax** [comment]
Windows terminal is ok too:
![image](https://user-images.githubusercontent.com/234774/114022451-73bb0300-987a-11eb-875e-cd03e402592d.png)

**Comment by habamax** [comment]
Locale:
![image](https://user-images.githubusercontent.com/234774/114023075-1b383580-987b-11eb-9b49-e08d7d9b6256.png)


PS, I "remember" I had no issues entering russian text in some of the previous versions, but I am not sure :)

**Comment by habamax** [comment]
well :)

```
Locale=en_EN
Charset=UTF-8
```
in config file fixes the issue.

**Comment by Biswa96** [comment]
Looks like we need some documentation about locale.

**Comment by mintty** [comment]
Works here, also with Locale=ru_RU. Could be a zsh issue, have you tried another shell or simply cat?

**Comment by habamax** [comment]
bash was partially ok: some letters were "unprintable" and I could backspace the whole prompt for some reason.

**Comment by habamax** [comment]
And I have just checked `locale -a`: there is no `ru_RU` in my debian so this was the issue.

**Comment by mintty** [comment]
OK, thanks for feedback. You can create a locale. I noted somewhere how it works, it's tricky and poorly documented.

**Comment by grousk** [comment]
> well :)
> 
> ```
> Locale=en_EN
> Charset=UTF-8
> ```
> 
> in config file fixes the issue.

which config file?
