### ISSUE TITLE
wsltty installer 0.7.4 is detected as malware

### ISSUE THREAD

**Issue by jjamor** [mintty/wsltty#28]
wsltty installer 0.7.4 is detected as mailicious tool by Symantec.

Risk: WS.Reputation.1

Virus Total report detect a generic malware:

https://www.virustotal.com/es/file/d5facea222e89aa5d240128bcd13cd4fb91c80af78d9890fe3cbc24b49fd6124/analysis/1485994148/

May be a problem with used compiler for mintty/cygwin libraries?

**Comment by mintty** [comment]
The installer is created with a Microsoft tool.
I wouldn't expect Symantec to be looking into the files packed within the installer, but who knows.
I am not aware (on the cygwin mailing list) with such problem with the gcc compiler.
Feel free to investigate...

**Comment by jjamor** [comment]
Hi,

Symantec has done a research on the installer, and they conclude it is a false positive. They are going to classify this and similar installers on their white list.

As soon as white list reach to my system, I will close this issue.

**Comment by mintty** [comment]
Thanks very much for taking this issue to Symantec.

**Comment by jjamor** [comment]
Just verified Symantec no longer blocks this installer. Closing this issue. Thanks!
