### ISSUE TITLE
get/read theme name from terminal

### ISSUE THREAD

**Issue by habamax** [mintty/wsltty#280]
Is there a way (some environment variable?) to get current theme wsltty uses?

![image](https://user-images.githubusercontent.com/234774/114177521-2bb4e280-9945-11eb-8390-ac72d92dd662.png)

(I want my vim to apply colorscheme depending on what wsltty has)

PS, I could probably read and parse config file, but there might be already smth in place?

**Comment by mintty** [comment]
I could add an OSC sequence to set and query the theme but I think what you really want is to adjust colour usage to the actual current setting. This is only pre-determined by a theme and can be adjusted by individual OSC dynamic colour settings for which corresponding queries already exist. That might be better for the use case.

**Comment by habamax** [comment]
Not sure I understand :) what queries and how to use them. To avoid XY problem:

1. I have 2 colorschemes for vim dark and light and 2 matched themes for wsltty.
2. Colorschemes and themes have the same name (doesn't matter actually)
3. When I start vim I would like to check what theme wsltty has and apply colorscheme of my preference.


I have tried your script that does the 'opposite' -- changing wsltty theme from the shell but it doesn't work for me -- hangs and does nothing.

**Comment by mintty** [comment]
> what queries

OSC 4;n;?, OSC 10;?, OSC 11;?, see https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands

I'm not sure in what way you'd like to adjust colour usage to the terminal theme. If it's just about determining the colours of your choice you could simply do that by using true colour.

**Comment by habamax** [comment]
> I'm not sure in what way you'd like to adjust colour usage to the terminal theme. If it's just about determining the colours of your choice you could simply do that by using true colour.

I do manually change theme of the wsltty -- that is ok -- depending on the mood or environment I would like to have either light or dark background (and corresponding colors) of the terminal.

So my vimrc has `colorscheme mydarkcolors` which I would like to change to smth like:

```
if expand("$WSLTTY_THEME") == 'arbitrary_theme_name_which_I_know_is_dark'
    colorscheme mydarkcolors
else
   colorscheme mylightcolors
endif
```

**Comment by habamax** [comment]
I could have used `background` option of vim

```
if &background == 'dark'
    colorscheme mydarkcolors
else
    colorscheme mylightcolors
endif
```

But with wsltty it is always 'light' no matter what theme I apply.
Ppl suggest that terminal is not properly setup, whatever it means.

Also vim help explains that `background` detection depends on:
![image](https://user-images.githubusercontent.com/234774/114232038-f1b70100-9983-11eb-8095-30046b43e79a.png)

**Comment by habamax** [comment]
Aannnd I am really sorry -- wsltty correctly does all the things and background is set up as `dark` or `light` for vim.

The issue is when I am in tmux :(

**Comment by habamax** [comment]
Both in tmux and plain wsltty vim's `background` is always `'light'`

**Comment by mintty** [comment]
You commented just before (apparently deleted) that tmux would make the difference. Please confirm.
And if possible please find out how vim determined its &background flag. I guess that's OSC 11 so I don't see why it should fail in plain wsltty.

**Comment by habamax** [comment]
> You commented just before (apparently deleted) that tmux would make the difference. Please confirm.
> And if possible please find out how vim determined its &background flag. I guess that's OSC 11 so I don't see why it should fail in plain wsltty.

Hmm, I have double checked again with `vim -Nu NONE` and `:echo &background`:

* without tmux I get proper `dark` and `light` background values depending on dark or light themes
* with tmux I get always `light`

So my deleted message was actually correct :)

**Comment by habamax** [comment]
Ok, I end up reading the config file :)

![vim-wsltty-theme](https://user-images.githubusercontent.com/234774/114237692-1ca55300-998c-11eb-8760-54451eacbfff.gif)

Sorry for inconvenience :)

**Comment by mintty** [comment]
Actually pass-through for certain sequences was just an issue with tmux. Maybe you should just upgrade or look out for its next release.
