### ISSUE TITLE
Windows update broke wsltty

### ISSUE THREAD

**Issue by f-a-a** [mintty/wsltty#281]
Recent Windows 10 update to version 21364.1000 (Build 21364.co_release.210416-1504) throws this error when running wslbridge2.exe:

```sh
assertion "hRes == 0" failed: file "GetVmId.cpp", line 47, function: HRESULT GetVmId(GUID*, const wstring&, int*)
      0 [main] wslbridge2 49 cygwin_exception::open_stackdumpfile: Dumping stack trace to wslbridge2.exe.stackdump
```

Not sure if this is the correct place to file this issue but I hope to get some leads on this

**Comment by jraffa** [comment]
I got something similar with the same release:

`assertion "hRes == 0" failed: file "GetVmId.cpp", line 43, function: HRESULT GetVmId(GUID*,const wstring&, int*)`

**Comment by Biswa96** [comment]
OK, I'm waiting for this bug 😈 I've already fix the issue in wslbridge2. If mintty needs I can tag a point release.

**Comment by mintty** [comment]
My version is 19041; I guess 21364 is in the "fast" release cycle, right?

@Biswa96, I've updated my patch set once but I'd prefer if we can integrate the inband-resize handling on this occasion, so I can simply catch-up with the latest wslbridge2 release in the future.

**Comment by Biswa96** [comment]
> I guess 21364 is in the "fast" release cycle, right?

Yes. It's in Insider release cycle. I have added v0.8 in wslbridge2 with the fix https://github.com/Biswa96/wslbridge2/releases/tag/v0.8

Speaking of the resize handling, I have not thought about it. I was exploring some Win32 console APIs then 2020 happened. Can you please edit the patch here at wsltty just last time? There will not be any monumental change 🤞

**Comment by mintty** [comment]
Released 3.5.0.2, marked as pre-release for now.
Please test.

**Comment by Biswa96** [comment]
Insiders, any test report?

**Comment by f-a-a** [comment]
@mintty @Biswa96 I can confirm version `3.5.0.2` now works without the reported error above. Thank you for the fix!

**Comment by jraffa** [comment]
works for me too.  thx!

**Comment by Biswa96** [comment]
So, will now the wsltty release be out of test? @mintty

**Comment by mintty** [comment]
Oh, yes. Thanks for reminding.
