### ISSUE TITLE
Installer not silent when using custom destination

### ISSUE THREAD

**Issue by AeliusSaionji** [mintty/wsltty#285]
Hello! When updating the chocolatey package, the following is run:
```powershell
Start-Process -FilePath "$filePath" -ArgumentList "/T:$toolsDir\wslttyinstall /C /Q" -WorkingDirectory "$toolsdir" -Wait
```

Despite the /Q, the user is presented a popup about overwriting existing files.

I am still maintaining the chocolatey package- I could adjust the install script to clear the directory beforehand, but it has been some time since I looked at the install logic and I'm not certain how wise that would be.

Let me know if this is something you can tackle from your end!

Thanks.

**Comment by mintty** [comment]
I assume the chocolatey install directory is not the same as the standalone install directory would be.
There is nothing that wsltty would remember in it, so if you don't expect users to make changes or add files to the install directory, feel free to clear it.
