### ISSUE TITLE
Set/detect Terminal Name, Resolution, DE, WM

### ISSUE THREAD

**Issue by rescenic** [mintty/wsltty#286]
Instead of "wslbridged2-back", can we get "wsltty (or mintty)" in Terminal Name. Also, can you please add feature to add Resolution, DE, WM, Terminal Font from wsltty/mintty Options in Windows (which is fine by me).
![wsltty-msys2](https://i.ibb.co/r2MyQtd/17-05-2021-1609-05-45-33.png)
Compare with Windows Terminal:
![wsltty-wt](https://i.ibb.co/f87MNkn/17-05-2021-1610-05-45-52.png)

**Comment by Biswa96** [comment]
What is that thing? What variables does it check to determine terminal emulator name?

**Comment by rescenic** [comment]
It's called neofetch.
https://github.com/dylanaraps/neofetch

We can configure it from ~/.config/neofetch/config.conf
![1](https://i.ibb.co/6DxG6wq/17-05-2021-1618-10-56-03.png)

Examples:
![2](https://i.ibb.co/XJxrVc3/17-05-2021-1614-09-43-18.png)
![3](https://i.ibb.co/Pjdm6Gz/17-05-2021-1615-10-09-42.png)
![4](https://i.ibb.co/4mG6Pnw/17-05-2021-1616-10-20-49.png)
![5](https://i.ibb.co/km8XkGM/17-05-2021-1619-10-59-52.png)


Windows have that package too from scoop. `scoop install neofetch`

**Comment by mintty** [comment]
The tool seems to determine some information about its runtime environment but most of it is not terminal-related. About dimensions, there are escape seqences to retrieve terminal size and resolution but apparently the tool does not use them. Likewise there are sequences (device attribute reports) to retrieve terminal type information but the tool does not use them.
Rather it seems to determine the program name of its parent process, which could as well be something like "ssh" in case you've logged in remotely from another terminal, so reporting wslbridge2-backend where the name of the terminal would be desired is a bug of the tool.

**Comment by rescenic** [comment]
Thank you very much for your explanation. I'll set them up manually, then. Hehe.

**Comment by mintty** [comment]
Well, you could submit them an issue and mention the `terminal` tool from the mintty utils repository for detection of the terminal type: https://github.com/mintty/utils/blob/master/terminal
