### ISSUE TITLE
Upgrade from 3.3 to to 3.5 font render issue

### ISSUE THREAD

**Issue by offero** [mintty/wsltty#289]
3.3 used to display my fonts just fine. An upgrade to 3.5 causes it to not do so. I'm not sure why. You can see how it's supposed to look in the picture.

![image](https://user-images.githubusercontent.com/4681330/126785361-7e6631d5-a339-4484-a4a8-0783273f3671.png)

![image](https://user-images.githubusercontent.com/4681330/126785427-9783616e-1a62-4aed-a346-13804506b256.png)

![image](https://user-images.githubusercontent.com/4681330/126785463-4068e290-cc3b-49b2-86cd-fc87e3a246ee.png)

**Comment by Biswa96** [comment]
How can I reproduce this issue?

**Comment by mintty** [comment]
Lambda displays fine here. There must be something else in your environment that affects this. Information insufficient.
Your locale settings (in mintty and in the Linux shell) etc.
There were some fixes about locale handling in 3.4.3 and in 3.4.1. Can you narrow down the change to one of these versions?

**Comment by offero** [comment]
Ahha, that was the hint I needed, the locale... the setting was unset/blank after the upgrade. When I selected UTF-8 again, it's back to normal.

![image](https://user-images.githubusercontent.com/4681330/126797761-2d35b787-987f-4e58-9ade-36b734a4b102.png)

**Comment by mintty** [comment]
I guess you had accidentally cleared the Charset setting but left a Locale setting in place.
This may yield the unexpected result of the implicit character encoding by the locale (without suffix), which is not UTF-8 in most cases.
I have added notes about it in the manual and the wiki Tips page.
