### ISSUE TITLE
Add New Fonts

### ISSUE THREAD

**Issue by bisraelsen** [mintty/wsltty#29]
I am trying to figure out how to add new fonts to the font configuration screen. I have installed some new fonts to both windows and lxss but can't see them in the configuration screen. Am I missing something?

**Comment by bisraelsen** [comment]
I'm not sure if there is a better way to do this but I found my `.minttyrc` file and replaced `Font=XXX` field with the font name that I want and it worked. Not sure why the installed fonts don't show up in the GUI menu, but that's OK.

**Comment by mintty** [comment]
Which font? Note that only monospace fonts appear in the menu.

**Comment by bisraelsen** [comment]
It is `Roboto Mono`. I am actually using `Roboto Mono for Powerline`, but neither show up. There are several mono fonts that don't show up in my list.

**Comment by mintty** [comment]
That's because some mono fonts are either not completely mono, or they are not recognised as mono by Windows, missing the respective flag. The latter is a problem of either the person who created the font file or the tool that was used.

**Comment by bisraelsen** [comment]
OK, my workaround is good for me. Thanks!

**Comment by mintty** [comment]
2.7.5 manual page includes a hint.
