### ISSUE TITLE
cygwin error

### ISSUE THREAD

**Issue by RoumaissaNl** [mintty/wsltty#292]
Hello everybody
I have this problem in Cygwin 
![Capture](https://user-images.githubusercontent.com/71291705/129666394-693bde5b-2d22-4871-8e0a-3ec5c26225c2.PNG)
And i dont know how to handle with it
Any solutions please

**Comment by Biswa96** [comment]
Please explain how you installed wsltty.

**Comment by RoumaissaNl** [comment]
I just downloaded it from https://www.cygwin.com/install.html

**Comment by mintty** [comment]
You are providing very sparse information. And it does not seem related to wsltty.
Anyway, that resource issue is more likely to occur in a 32-bit installation; what's yours?
Reboot may in fact help in this case, or running the quoted command from a cygwin console (which is a bit tricky for beginners, so let's postpone details). You may also ask on the cygwin mailing list.

**Comment by RoumaissaNl** [comment]
I have 64-bit
This is my first time of using Cygwin, I also reboot it but it doesn’t work 
I can’t write instructions in Cygwin console because of this problem
This is how the messege look like:
Error: could not fork child process: Resource temporarily unavailable.  
DLL rebasing may be required. See 'rebaseall / rebase --help'.

**Comment by Biswa96** [comment]
cygwin is not required to use wsltty. Download the installer from the release page of this project https://github.com/mintty/wsltty/releases. Also read the README page for further information.

**Comment by RoumaissaNl** [comment]
Why should i install wsltty ?

**Comment by Biswa96** [comment]
Why did you create this issue in wsltty?

**Comment by RoumaissaNl** [comment]
I'm sorry I'm new here in Github

**Comment by mintty** [comment]
Cygwin mailing list, see cygwin.com. Sorry for late response.
