### ISSUE TITLE
Suggestion: CTRL + N for new window

### ISSUE THREAD

**Issue by Kihltech** [mintty/wsltty#294]
mintty/wsltty is great! Can we please have an additional keyboard shortcut for a new window? CTRL + N feels natural for me.

**Comment by Biswa96** [comment]
It's Ctrl + Shift + N

**Comment by Kihltech** [comment]
> 
> 
> It's Ctrl + Shift + N

My bad! I had not seen the setting to enable ctrl+shift shortcuts.

This issue can be closed and forgotten :)
