### ISSUE TITLE
Smart Screen triggered when downloading/installing in Edge

### ISSUE THREAD

**Issue by roblogic** [mintty/wsltty#299]
Similar to [several other issues](https://github.com/mintty/wsltty/issues?q=is%3Aissue+virus). Latest release was flagged and Windows really didn't want me to download or run the installer (wsltty-3.5.1-x86_64-install.exe) for version 3.5.1. 

Submitted a report to Microsoft that it's not malware. Might be more effective if the devs submit a similar report.

Possibly helpful for avoiding this in future:
https://www.ctrl.blog/entry/how-to-false-smartscreen-positive.html

Cheers & thanks for a cool app

**Comment by mintty** [comment]
Also the project to establish wsltty as an "app" for the app store is kind of staled. Someone familiar with app store processes might help out.
