### ISSUE TITLE
Suggestion: Add wsltty to Microsoft's new `winget` package repo

### ISSUE THREAD

**Issue by roblogic** [mintty/wsltty#300]
As an alternative to [packaging up the app for the Windows Store](https://github.com/mintty/wsltty/issues/63), please consider submitting a manifest to the [new `winget` repository](https://docs.microsoft.com/en-us/windows/package-manager/) that is currently in beta/preview mode from Microsoft.

The manifest is just a few lines of YAML and the [Microsoft docs](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example) give an example from the Windows Terminal (!), a relative upstart compared to wsltty.

**Comment by mintty** [comment]
Thanks for the hint; quickly browsing that gives me the impression, however, that you'd still need to deal with "Windows Package Manager" formats for the installer, so you can't simply submit a manifest.

**Comment by mintty** [comment]
This is now accomplished, thanks to a volunteer contributor.
