### ISSUE TITLE
Ctrl + Shift + R for history search

### ISSUE THREAD

**Issue by pizzot** [mintty/wsltty#301]
Hey, 
I found wsltty because I was annoyed by the fact that windows' Ubuntu terminal doesn't support any kind of clipboard pasting other than a mouse click! I was so happy I did until I pressed Ctrl + Shift + R to search for a command in history :) Unfortunately, this shortcut doesn't work here. Would it be possible to add support for this?

**Comment by Biswa96** [comment]
Is not that Ctrl + R to search history in bash?

**Comment by mintty** [comment]
As Biswa indicates, this is a shell feature, not a terminal feature. However, the shortcut might get captured by mintty if Options - Keys - Ctrl+Shift+letter shortcuts is enabled. Disable that.
