### ISSUE TITLE
[feature request] portable version

### ISSUE THREAD

**Issue by eugenov** [mintty/wsltty#306]
Hello!
Wsltty right now has some portability, but it is not too convenient to edit install scripts every new version. Could you add portable binaries to releases? Thank you for your hard work!

**Comment by eugenov** [comment]
Nevermind, it's not that hard to write script to launch script. Closing.

**Comment by mintty** [comment]
Well, I could add a zip archive to the release which can be unpacked locally.
Please also upload your script here.

**Comment by eugenov** [comment]
My script is dumb oneliner, that only pass %1 and %2 to install.bat (just to not edit install.bat each version update)
`.\install.bat "%USERPROFILE%\apps\wsltty" "%USERPROFILE%\apps\wsltty"`

**Comment by mintty** [comment]
There's a bit more to it, e.g. a portable installation should not create local shortcuts but should create a generic shortcut for the portable. I've added a portable installer to the 3.5.3 release, please test.

**Comment by eugenov** [comment]
Perfect! imao you could publish only this version )

**Comment by mintty** [comment]
Released 3.6.0.
