### ISSUE TITLE
wsltty 3.5.3 keeps fading out

### ISSUE THREAD

**Issue by mrinmoyg** [mintty/wsltty#307]
Recently moved to 3.5.3 from 3.4.3, however I am this issue in the new version, which is quite a showstopper

config:
<pre>
ForegroundColour=232,232,232
BackgroundColour=89,89,89
Font=Courier
FontHeight=8
BoldAsFont=yes
ZoomShortcuts=no
RightClickAction=paste
ClickTargetMod=off
CopyAsRTF=no
Rows=65
Term=xterm-256color
CursorType=block
BellType=0
ThemeFile=mintty
CursorBlinks=no
ClipShortcuts=yes
Transparency=off
</pre>

The fading out recovers whenever I open "Options" from wsltty or when I move the focus to another application and focus back to wsl

Thanks in advance for the help

**Comment by mintty** [comment]
Cannot detect any issue. Please describe what you mean by "fading out".

**Comment by mrinmoyg** [comment]
I meant its dimming (majorly the background) when the window is focussed, but it happens a bit randomly and there seems to be some timer event, as the diming is slow. I am trying to capture the sequence, not sure how much legible it will be.

**Comment by mintty** [comment]
Sounds like an effect of a window manager or other desktop "tool". Please check your installed software.

**Comment by mrinmoyg** [comment]
Yes, it was an Intel driver problem. Power saving display setting etc.
