### ISSUE TITLE
[feature request] mouse moving in alternate buffer

### ISSUE THREAD

**Issue by eugenov** [mintty/wsltty#308]
Hello!
Right now mintty can place cursor with left-mouse in any place of command line. Is there any chance to see such placing, but inside alternate buffer (i.e. vim). With modifier key, for example. As I know this is rare feature, but not undoable.
Thank you!

**Comment by mintty** [comment]
With the "Clicks place command line cursor" setting, mintty simulates cursor movement by sending fake cursor left/right events. This is a very specific workaround for command-line interaction.
For full screen applications like editors, it is hardly possible to predict how they would react to cursor movement, also considering that they often have different modes of operation, so a reliable generic workaround is not possible.
Full screen programs typically handle the mouse themselves to get this work as suitable for them. Some old-fashioned applications do not support the mouse, or not by default, that's their problem.

**Comment by eugenov** [comment]
Ok, thanks for clarification.
