### ISSUE TITLE
Avast is reporting virus infection

### ISSUE THREAD

**Issue by thk4711** [mintty/wsltty#31]
Today I installed the version 0.75 and when I started the shell AVAST anti virus software ist reporting: 
IDP Generic Infection

**Comment by mintty** [comment]
Please check this out with Avast.

**Comment by mintty** [comment]
Note that the installer is created with a Microsoft tool.
See also #28.

**Comment by noinkling** [comment]
Just tried downloading the 0.7.7 installer, Windows Defender detects it as [Trojan:Win32/Spursint.F!cl](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3AWin32%2FSpursint.F!cl&threatid=2147717281&enterprise=0) (and Chrome reports "Failed, Virus detected" on the download).

**Comment by willpower232** [comment]
I managed to download and install it with firefox but chrome detected the virus and set windows defender on a cleanup rampage

**Comment by PokaLXIV** [comment]
Didn't get the virus alert yesterday but I can't download the file today because chrome detects virus

**Comment by willpower232** [comment]
having installed it via firefox and had the installer files deleted by windows defender, windows defender did not find any virus on the system so is it a hilarious signature collision in the installer alone I wonder?

**Comment by mintty** [comment]
I'm getting the same message as previously discussed in #32, that Defender SmartScreen prevented an unknown App from starting and talks about an unknown publisher. This does not call it a virus.

Chrome mentions a "threat" in a generic way, simply be referring to Windows Defender. When I click on the popup, Defender opens and does not report a threat.

**Comment by willpower232** [comment]
I have updated Windows Defender and I'm on the latest Chrome 58.0.3029.110 and get a system notification about Defender removing some malware and this message is in Chrome

![capture](https://cloud.githubusercontent.com/assets/1619102/26287328/1999bdc4-3e71-11e7-93b8-d6371ca5b0a8.PNG)

I don't know if Defender is somehow tipped off by Chrome but I can no longer download it in either browser, very odd indeed.

VirusTotal show some interesting results, obviously its a false positive and the dates on the definitions listed are old https://www.virustotal.com/en/file/6d227ca3c6014aec840452401faf35f8e2916def09cd28e2508d6c7edf1c2e4c/analysis/1495348251/

**Comment by PhilipDaniels** [comment]
I just tried installing the latest version and got a warning box from Windows Defender Smart Screen (I think, it doesn't pop up again if I run it again). Anyway, it was moaning about lack of a publisher.

**Comment by mintty** [comment]
See also discussion in #32.

**Comment by mintty** [comment]
Please recheck with 0.7.7.1.

**Comment by willpower232** [comment]
no virus warning with this download

**Comment by noinkling** [comment]
0.7.7.1 installer:

![](http://i.imgur.com/xsw63Fu.png)

Windows Defender detecting the same thing.

**Comment by noinkling** [comment]
Update: none of the 0.7.7 installers are being detected as viruses by Windows Defender any longer, guess they fixed their definitions 👍

**Comment by mintty** [comment]
Thanks for reporting back.
So if nobody objects, I will close this issue.
