### ISSUE TITLE
Terminal stops updating when using SSH

### ISSUE THREAD

**Issue by stirlingTR** [mintty/wsltty#313]
Tried to see if there were any similar issues before and it might be linked to #169.

Whenever I open an SSH connection there's a high chance the window will immediately stop responding. This is most notable when running stuff like vim, htop, and sometimes ls. The WSL install continues running fine and I can open additional windows and I can see the SSH connection is still active on the host until I close that frozen window. Rarely will the window recover on it's own. 

Since first having this issue I've reinstalled both WSL and windows, currently have tried both Debian and Ubuntu, with no success in troubleshooting it.

Edit: Forgot to mention, SSH functions normally when done via powershell or WSL run through the powershell window.

**Comment by Biswa96** [comment]
Can you please provide the steps to reproduce the issue?

**Comment by stirlingTR** [comment]
It can be pretty reliably reproduced with just the following.
Step 1: Open wsltty
Step 2: ssh example@123.456.78.90
Step 3: htop

However, despite me checking beforehand, I think this may be an issue with how I have my network setup as I just managed to reproduce this in powershell after a couple more tries. My apologies.
Likely culprit is https://github.com/microsoft/WSL/issues/4690

**Comment by mintty** [comment]
So this issue should be closed?
