### ISSUE TITLE
Issue running wsltty on Windows Server 2022 with WSL

### ISSUE THREAD

**Issue by lsantagostini** [mintty/wsltty#319]
Hello all, im running wsl2 on windows server 2022.
Today, wsltty has stopped working.

I tried reinstalling wsltty to las version without lucky.

Version: Mintty 3.6.1 [x86_64-pc-cygwin] -- wsltty 3.6.1.2

Command: C:\Users\XXXX>C:\Users\XXXX\AppData\Local\wsltty\bin\mintty.exe -h always -l --WSL= --configdir="C:\UsersXXXX\AppData\Roaming\wsltty" -~  - 

![image](https://user-images.githubusercontent.com/71609784/205743648-a430a9df-bc52-48ed-ba68-4ce4c22157f5.png)

Windows Version:
![image](https://user-images.githubusercontent.com/71609784/205743765-0e4e8595-f7ec-49f1-9f32-1336f348ca87.png)

And /bin/bash, exists
![image](https://user-images.githubusercontent.com/71609784/205744324-f5869560-ee5f-4d10-93c5-55223ca95300.png)

Any clue?
Thank you!

**Comment by Biswa96** [comment]
Can you execute the `"%LocalAppData%\wsltty\bin\wslbridge2.exe"` file in command prompt and see if it opens up any WSL prompt?

**Comment by lsantagostini** [comment]
Ok, i ran the command, but nothing happens. 

![image](https://user-images.githubusercontent.com/71609784/205816530-78a859b8-af20-45bc-b34b-d685ac355a19.png)

Thanks!

**Comment by Biswa96** [comment]
I think this need some deep inspection. This is my first time dealing with Windows Server. I have found the SERVER_EVAL_x64FRE_en-us.iso from Microsoft website. Is it same as your installation?

**Comment by lsantagostini** [comment]
Yeap, but you will need to "[Quickly convert Windows Server Evaluation edition to the retail one](https://msguides.com/convert-windows-server-evaluation)" for being able to install wsl.

And, no, WSL wasnt installed using store. Store works on "desktop" windows editions, not Server editions.

I followed [this article](https://learn.microsoft.com/en-us/windows/wsl/install-on-server) to install wsl

HTH, thanks

**Comment by Biswa96** [comment]
I have installed Windows Server 2022 DataCenter in my pc and wsltty works just fine. This is my first time ever touching a Windows Server installation, so I am not sure if things are done right way. I can provide any information you want.

I can not run WSL2 in the installation, only WSL1. It seems that WSL2 is prohibited somehow. The `--version 2` option only outputs the usage of wsl.exe.

**Comment by Biswa96** [comment]
I have no idea what that "June 2022 patch Tuesday release" even means :smile: I have installed the ISO from this page https://www.microsoft.com/en-us/evalcenter/download-windows-server-2022

> So weird to listen that you have no issues =(

WSL1 and WSL2 works totally in different way, maybe I have not reproduce your situation exactly. If required I can try to poke into system binaries to find which thing prevent WSL2.

**Comment by lsantagostini** [comment]
Thanks for your clarification. Let me know if i can provide more information.

Thank you !

**Comment by Biswa96** [comment]
After looking your given screenshot, I found that the Windows version is different. The ISO file is Windows server 2022 version 10.0.20348.587. I have installed KB5020032 manually to upgrade to 10.0.20348.1311 version. With that, I can reproduce the issue. I shall let you know if there is any fix.

**Comment by lsantagostini** [comment]
Hello, morning. just remembering the very first post, where, after an update, wsltty has stopped working.
So i was working before an update. Is not about on how to install wsl on server 2022 its about an OS update.

Any help i can provide, just let me know.

**Comment by Biswa96** [comment]
Before the update, I had Windows version 10.0.20348.587 which can not run WSL2. In that version, wsltty worked with WSL1 as usual in my setup.

**Comment by lsantagostini** [comment]
Well, maybe someday this issue will be solved.

In the maenwhile i have to search another terminal. So sad.

**Comment by Biswa96** [comment]
You can use wsl.exe directly in mintty. Though some terminal features may not work due to some conhost or conpty issues. Those same issues apply in any terminal emulator in Windows, AFAIK.

**Comment by lsantagostini** [comment]
Can you please point me on how to:
1) Which project/s i must download
2) Which are the file/s i must modify
3) how to compile the entire project for getting wsltty working again?

Thank you!

**Comment by Biswa96** [comment]
For which Windows Server version do you want to run wsltty? I can share the binary from GitHub Actions CI. I would assume you trust to run random binaries from Internet in Windows Server 😇

**Comment by lsantagostini** [comment]
For this version.

![image](https://user-images.githubusercontent.com/71609784/207700028-6bfbeaea-7965-41dc-8b3e-71b1174d9a79.png)


I absolutely trust on wsltty

**Comment by Biswa96** [comment]
I have added the required executable file in this release page https://github.com/Biswa96/wslbridge2/releases/tag/v0.10. See the notes there. The source can be found in server-2022 branch with same change as mentioned above.

**Comment by lsantagostini** [comment]
YEY !!!! love you <3

**Comment by lsantagostini** [comment]
Thanks for this version. Its working like a charm.

**Comment by mintty** [comment]
Thanks to both for working this out, but I'm reopening the issue because a specific "version" to be patched in for a specific Windows version is not a solution in the context of the wsltty project. A common deployment for any Windows version is desirable.

**Comment by mintty** [comment]
Released 3.6.5; is this still an issue?
