### ISSUE TITLE
RFC: Difference between vanilla WSLtty and MinTTY

### ISSUE THREAD

**Issue by sskras** [mintty/wsltty#320]
I tried to install MinTTY as a windows package (used `winget` for that) and noticed that it contains WSLtty instead.

1. What are differences between these two ?

2. Would it be possible to deploy / split WSLtty into / as two MSI packages instead:
  \
2a. the universal MinTTY;
2b. the WSL-bridging files ?

Reason for that is that it would be really nice to have one MinTTY installation that serves all the other environments:

- Cygwin
- MSYS2
- WSL
- midipix

**Comment by Biswa96** [comment]
You can use the programs from here https://github.com/Biswa96/wslbridge2/releases with existing cygwin/msys2 installation.

**Comment by sskras** [comment]
Thanks for the tip regarding the 2nd question. 

However this only shifts the install location of the `mintty.exe` from the WSLtty to the other program (eg Cygwin). 
This probably means that MinTTY could not be installed on it's own.

Yeah, found the answer after a while:
https://github.com/mintty/mintty/issues/659

OK, so I guess it has no sense to ask about splitting the installer into two parts – the MinTTY itself + the WSL bridging files – until it gets packaged as a shared dependency:
https://github.com/mintty/mintty/issues/1194

Closing until then.

**Comment by mintty** [comment]
Whether split or not, there is not way to get an MSI installer for mintty as there is no seamless and free tooling to produce that.
