### ISSUE TITLE
22H2 update broke mintty? closes immediately

### ISSUE THREAD

**Issue by adipose** [mintty/wsltty#323]
I cannot get wsltty to start after a recent windows update.  I'm on 22H2 Version 10.0.19045.2486.

Running from cmd.exe gives this error:

```
C:\Users\me\AppData\Local\wsltty\bin>wslbridge2.exe -d Ubuntu
note: backend error output: Assertion failed: connectRet == 0 (nix-sock.c: nix_vsock_connect: 134)

```
I've seen this error mentioned for conemu but I cannot find a fix for wsl.

**Comment by Biswa96** [comment]
* Which WSL are you using?
* The system one or from Windows Store?
* What is the version from `wslbridge2.exe --help`?
* Can you run wsl.exe?

**Comment by adipose** [comment]
After updating, everything broke, and I updated wsltty.  However, I must have selected x86 version.  Now that I installed x64 version, it's working. I noticed this when I tried to update wslbridge2 manually and saw the cygwin dll was a different size.

**Comment by Biswa96** [comment]
Thanks for the verification. I should have used proper error handling instead of asserting everything.

![image](https://media.tenor.com/jNXwTFt0PFMAAAAd/spongebob-squarepants.gif)
