### ISSUE TITLE
Extraneous % in shortcuts

### ISSUE THREAD

**Issue by rasa** [mintty/wsltty#325]
After installing
https://github.com/mintty/wsltty/releases/download/3.6.1.2/wsltty-3.6.1.2-x86_64-install-quiet.exe
via winget:
<img width="147" alt="2023-01-26_18-23-16-chrome-minttywsltty_Mintty_as_a_terminal_for_Bash_on_Ubun" src="https://user-images.githubusercontent.com/220772/214996956-79f70067-ef1a-409c-8c03-c090cadc5fba.png">

**Comment by mintty** [comment]
The % sign is there explicitly and on purpose to indicate that this version of the shortcut starts the terminal in the Windows home directory (%USERPROFILE%), as opposed to the other set of shortcuts which start in the WSL home directory.
The "%" variants should actually only be installed in the Start Menu subfolder WSLtty, to be checked.
The "%" refers to the naming scheme of Windows environment variables, maybe not the best choice...
