### ISSUE TITLE
double click text selection not selecting the entire path

### ISSUE THREAD

**Issue by lyuwen** [mintty/wsltty#330]
When the path contains `../` or `~/`, double click won't select that part of the text.
For example, for the path `../../usr/local/bin/`, double click on the text will only select `/usr/local/bin`.
And for that path `~/git-projects/myproject/src/`, double click on the text will only select `/git-projects/myproject/src`.

I'm fine with not including the trailing foreward slash. But not including the '..' or '~' is very inconvenient. It worked fine in a previous version of wsltty (v3.6.1), and I'm currently using v3.6.4. Shouldn't it behave like a linux terminal and select the entire path on double-click?

Thanks.

**Comment by lyuwen** [comment]
BTW, I've tried adding '~' and '.' into the config flag "WordChars" but it didn't work.

**Comment by Biswa96** [comment]
This is mintty version 3.6.4 issue. It is possible to use older wsltty version which includes mintty 3.6.3 version.

**Comment by mintty** [comment]
This is fixed already, for next release 3.6.5.

**Comment by mintty** [comment]
Released 3.6.5.
