### ISSUE TITLE
Why the alacritty doesn't need wslbridge? How does it work with WSL?

### ISSUE THREAD

**Issue by netjune** [mintty/wsltty#339]
I tried to start WSL with alacritty. It works well. It doesn't need wslbridge or else. How does it work?

**Comment by mintty** [comment]
The same works with mintty. Just the wsl.exe gateway imposes a bunch of restrictions and witty assumptions on terminal operation. You won't be able to use extended attributes (like curly underlined) for instance, or dynamic colour configuration etc.

**Comment by netjune** [comment]
OK. Thanks for your explaination.

**Comment by mintty** [comment]
See also mintty/mintty#1235 for an example how plain wsl does _not_ work properly.
