### ISSUE TITLE
Ctrl+Shift+c/v shortcuts to copy and paste don't worked.

### ISSUE THREAD

**Issue by kanonji** [mintty/wsltty#34]
Ctrl/Shift+Ins works but Ctrl+Shift+c/v don't.

## Environments

&nbsp;|version
---|---
Windows 10 Home|1607
os build| 14393.953
wsltty|0.7.5

My .minttyrc: https://github.com/kanonji/dotfile/commit/b8116f4dc7c1d6b35d90d2fe6441e1d8b60506b5
This is placed to `%LOCALAPPDATA%\wsltty\home\%USERNAME%\.minttyrc`

## Notes

I had installed wsltty 0.7.1 at first and have upgraded to 0.7.5 by overwriting install with the installer.
I am not sure wsltty is upgraded or not.

I don't know how to get the version installed. Please tell me how to get that.

**Comment by mintty** [comment]
You need to activate Ctrl+Shift+letter shortcuts in the Keys section of the Options menu,
or .minttyrc entry CtrlShiftShortcuts=yes (default is no).

**Comment by kanonji** [comment]
Thanks. I missed that option. The shortcuts work now.
