### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fengyichui** [mintty/wsltty#340]
Hi，

I noticed that a recent version of wsltty had a memory leak issue, RAM usage will continue to increase:

![wsltty_memlack](https://github.com/mintty/wsltty/assets/17896291/0d678c36-4629-48df-a296-355b3e2cabb1)

**Comment by Biswa96** [comment]
What does it show after you click on the leftmost arrow key?

**Comment by mintty** [comment]
Are you using any special features of the terminal when this happens? (Like graphic output, exotic terminal features, ...)

**Comment by Biswa96** [comment]
I meant to ask what are the memory usage of individual programs. In the first screenshot, it seems Task Manager shows total memory usage.

**Comment by fengyichui** [comment]
@Biswa96 All RAM is occupied by mintty/wsltty. The config `mojis=google` lead this issue.

**Comment by mintty** [comment]
So you have configure `emojis=google` and output a lot of emojis, right?
Emojis use memory of course.
They are supposed to be freed in memory when they are no longer needed, however note the scrollback buffer which still holds emojis and blocks them from getting freed. You may test again, considering this, e.g. you might disable the scrollback buffer (ScrollbackLines=0).

**Comment by fengyichui** [comment]
No, I don't output any emojis. Just enter the `ls` command in the terminal, the memory starts leaking at 4.5M per minute.
After wsltty v3.6.4(include this version), this issue arises.

**Comment by fengyichui** [comment]
`ScrollbackLines=0` has no effect.

**Comment by mintty** [comment]
The problem was caused by commit "dynamic support for flags emojis" in 3.6.4. It occurs independently of actual usage of emojis.
Fixed.

**Comment by mintty** [comment]
Released 3.7.0.

**Comment by mintty** [comment]
Released 3.7.0.
