### ISSUE TITLE
About-box shows mintty-version, but not wsltty-version

### ISSUE THREAD

**Issue by mobluse** [mintty/wsltty#35]
I can't see which version of WSLTTY I'm using because the About-box in Options only shows the version of MINTTY. I can see the version on the downloaded install package, but I would like to delete that. Now I'm using wsltty-0.7.5-install.exe.

(BTW thanks for making WSLTTY. I'm using it because of Sixel-graphics and better XTerm emulation.)

**Comment by mintty** [comment]
The plan is to keep release in sync, using similar version names.
I could further sync the names exactly, to reduce confusion.
True dedicated version checking would be somewhat more fiddly, not done yet.

**Comment by mintty** [comment]
Released 0.7.8.3, showing wsltty version in About info. The update availability notification in the Options dialog, however, still refers to the mintty version.
