### ISSUE TITLE
Box drawing shows gaps with some fonts

### ISSUE THREAD

**Issue by tig** [mintty/wsltty#353]
The vertical spacing is too tall. This is with Cascadia Code, but it reproduces with the default Lucida Console as well.

![image](https://github.com/user-attachments/assets/3a48f446-8c3e-4352-a224-a05f01bfb2d2)

Note the gaps between the vertical bars.

Other terminals have better defaults and/or make this configurable. E.g. WT:

![image](https://github.com/user-attachments/assets/8b9b410b-52b9-4c18-89b6-1d472db256e6)

**Comment by mintty** [comment]
Click on the upper-left icon, Options - About - Whats' the version?

**Comment by mintty** [comment]
What are you actually running here? The title bar text does not sound like related to mintty at all.

**Comment by tig** [comment]
> What are you actually running here? The title bar text does not sound like related to mintty at all.

A test app from https://github.com/gui-cs/Terminal.gui

![image](https://github.com/user-attachments/assets/be1db69a-da40-421c-ab9d-f4d1aafad049)

**Comment by mintty** [comment]
An equivalent of that "Line height" setting is available in mintty: option RowSpacing. You can use negative values for it.
And it's not the best idea to use ASCII pipe for border drawing. VT100 graphics or Unicode block graphics are a better choice, and they get special handling in mintty to avoid gaps. However, particularly Lucida Console has some broken design in the Box Drawing glyph range, which cannot be repaired by line spacing.

**Comment by mintty** [comment]
Checking text output, by the way, I do not agree that Lucida Console line height would be too tall. Changing the issue title accordingly.

**Comment by tig** [comment]
> An equivalent of that "Line height" setting is available in mintty: option RowSpacing. You can use negative values for it. And it's not the best idea to use ASCII pipe for border drawing. VT100 graphics or Unicode block graphics are a better choice, and they get special handling in mintty to avoid gaps. However, particularly Lucida Console has some broken design in the Box Drawing glyph range, which cannot be repaired by line spacing.

Those glyphs in the screenshot are not ASCII pipe.

Here's with Lucida Console. Note corner rendinging issue (which may be a different issue).

![image](https://github.com/user-attachments/assets/ed24daf7-f0c4-4ade-86f7-6d1e17c77b52)

**Comment by mintty** [comment]
I took a deeper look into the issue. (It appeared a bit strange to me at first because I do not have this experience - all is fine with my daily font DejaVuSans Mono.)
It seems to be a font issue. I speculate Windows Terminal has a workaround, maybe it draws Unicode box graphics itself (I'll check their issues about it).
In mintty, you can configure a workaround:
`FontChoice=PictoSymbols:2`
`Font2=Consolas` (or any font you have with proper box graphics)

I could make mintty apply such a workaround automatically, but it would then override box graphics also with fonts that have a proper set of them...

**Comment by mintty** [comment]
Windows Terminal also used to have its problems with box graphics (https://github.com/microsoft/terminal/issues/14654) and even deliberately accepted that (https://github.com/microsoft/terminal/issues/5894#issuecomment-628292563) after considering options (https://github.com/microsoft/terminal/issues/5897) and it seems that they are now self-drawing them (https://github.com/microsoft/terminal/issues/5897#issuecomment-1947619243) but I don't see any related option in their complex settings menu.

**Comment by mintty** [comment]
A more specific workaround is:
`FontChoice=|Box Drawing:2`
`Font2=Consolas` (or DejaVu Sans Mono if you have it)

This was discussed before: mintty/mintty#935, mintty/mintty#1119.

**Comment by mintty** [comment]
Released 3.7.6.
