### ISSUE TITLE
wsltty launch fail with the latest windows

### ISSUE THREAD

**Issue by js210711** [mintty/wsltty#357]
I got this error while launching wsltty on the latest windows OS. mintty --log option output like this.
I have tried all the things that can be tried. none of ones worked. reinstall WSL, wsltty, previledge mode run, .... 
please help me this out. i have tested office laptop, and now tested home laptop. with different HW spec, wsltty runs on both of these laptops all failed.

GetVmId:312: CreateLxProcess: Null reference pointer passed to stub

**Comment by mintty** [comment]
Duplicate #356.

**Comment by mintty** [comment]
Released 3.7.6.
