### ISSUE TITLE
font alignment changed in 3.7.6?

### ISSUE THREAD

**Issue by eeweegh** [mintty/wsltty#358]
I just upgraded from 3.7.4 to 3.7.6, and noticed that my fancy prompts and tmux/vim themes all draw this particular character combination with an extra (ugly) spacing after the 'left opening bow' char (<> 57526, Hex e0b6, Octal 160266)
![image](https://github.com/user-attachments/assets/d982370c-c0ca-4aae-a98d-522b5085fbf8)

Left side joints look tighter, although I get the impression they're a bit warped as well (the half circle looking bumped up a bit)
![image](https://github.com/user-attachments/assets/87a170c0-99b5-461c-ade1-c674036f0084)

I can make it disappear by going to fontheight=10, but that is not really what I want, and I get the impression it is still jaggy, and slightly warped
![image](https://github.com/user-attachments/assets/b34ed382-bc1d-41a9-b1b8-782de4dbf054)

My config file is this
`# To use common configuration in %APPDATA%\mintty, simply remove this file
# these are set in theme file
#ForegroundColour=179,186,187
#BackgroundColour=39,62,38
#CursorColour=191,255,0
ThemeFile=selenized.dark
Transparency=low
OpaqueWhenFocused=yes
CursorType=block
**FontHeight=9**
CopyAsRTF=no
RightClickAction=paste
Columns=241
Rows=68
PgUpDnScroll=yes
Language=@
Term=xterm-256color
BellType=-1
BellFile=ambient-drop
Locale=en_US
DeleteSendsDEL=no
SelectionShowSize=0
**Font=MesloLGM Nerd Font Mono**
Charset=UTF-8
AllowSetSelection=yes
CopyAsHTML=no
BackspaceSendsBS=no
EmojiPlacement=stretch
ElasticMouse=yes
`

Probably a silly 1st world problem, but thank you for letting me know your thoughts and any workarounds!

**Comment by mintty** [comment]
Self-drawing of Powerline symbols had been implemented in mintty for a while but accidentally not ensabled, so still they were shown only if you use a font that has them.
I "fixed" this in 3.7.6 so Powerline symbols are always available, but it turns out the self-drawing algorithm is not perfect.
I will look into this.

**Comment by eeweegh** [comment]
OK, thanks! In the meantime, is there a way I can force the old behaviour (drawing from font), maybe with a FontChoice Private config, and an explicit reference to my nerd font?

**Comment by mintty** [comment]
Not right now. Why do you think this would be a benefit?

**Comment by eeweegh** [comment]
1. pure self-interest :-) Make it work again while you take the time to look into your code;
2. it would give me a reason to better look into font config in mintty;
3. hypothetical and possibly far fetched: maybe some fonts will have variants of Powerline glyphs that users prefer to use, rather than the self-drawn versions.

**Comment by eeweegh** [comment]
Another observation, maybe it helps:

it looks OK:
1. on my laptop's high res (2496x1664, 150% scaling) screen, when wsltty is fully on that screen;
2. on an external (lower resolution, 100% scaling) monitor, when wsltty is half on the internal screen, and half on the external monitor (because of resolution difference, the part on the external monitor looks zoomed in);

It looks bad (as reported) when wsltty is completely on the external monitor.

If I set the scaling of the external monitor to 125% or 150% (matching the laptop screen) it also looks OK on the external monitor (but obviously way too big)

**Comment by eeweegh** [comment]
> Did you upgrade to wsltty 3.7.6? I actually forgot to close this issue as there is a fix now available.

yes - I actually started to see it after I upgraded to 3.7.6 (you made me doubt, but that's what in the original description :-)). 3.7.4 (and everything before) was fine.

**Comment by mintty** [comment]
Ah, right, I guess I confused issues in my question. I actually fixed this one (see above), after 3.7.6.

**Comment by mintty** [comment]
Released 3.7.7.

**Comment by eeweegh** [comment]
Confirmed fixed - thank you very much!
