### ISSUE TITLE
Sluggishness in 0.7.5

### ISSUE THREAD

**Issue by kRush-** [mintty/wsltty#36]
There seems to be a rather noticeable slowdown in v0.7.5 compared to the version before.
I have tried with the same config on both and scrolling a large log file or screen buffer is very laggy/slow now.

**Comment by mintty** [comment]
Does it change with option FontRender=textout?
Do you have many box drawing characters in your scroll buffer?
Do you make use of the new scroll markers features?
Do you have an old CPU?
I cannot reproduce the symptom right now, please describe more specifically (length of text, what exactly you do to measure slowness...)

**Comment by kRush-** [comment]
Yes, it is better. About the same es the version before.
No.
No.
Intel Celeron N3150, so not old but low-end.
Just looking at the screen really, it's that obvious here.
Opening a large text file in less and scrolling around with PgUp/Dn I can see the screen refresh over multiple frames in the new version w/o textout.
Opening two sessions side-by-side to the same tmux instance shows this takes about 2-3x more CPU w/o textout.
In journalctl if I scroll long enough the side w/o textout will still be at it for several seconds after I let the key go.

**Comment by mintty** [comment]
> /e: It's more noticeable the larger my terminal window is, still rather slow in fullscreen

Yes, I forgot to ask about your screen size. Mintty is not the fastest, but neither the slowest terminal.

> Yes, it is better. About the same es the version before.

So this is due to the change in 2.7.5:
  * Changing default FontRender=uniscribe (#605, #573).

Uniscribe needs some more effort to render. That's the trade-off.

**Comment by mintty** [comment]
Acknowleged some noticeable "sluggishness" e.g. on an Atom processor.
Now disabling Uniscribe for ASCII-only output chunks.

**Comment by mintty** [comment]
Released with mintty 2.7.7, optimizing ASCII output.
