### ISSUE TITLE
Cannot start wsltty on WSL2

### ISSUE THREAD

**Issue by mikoto2000** [mintty/wsltty#360]
When you launch wsltty, a window briefly appears and then disappears.

I run this command on command prompt:

```
%LOCALAPPDATA%\wsltty\bin\mintty.exe --tabbar=4 -o "KeyFunctions=t:new-window-cwd;w:close;AppID=wsltty" --WSL="Ubuntu" --configdir="%APPDATA%\wsltty" -h always -
```

I get this error:

```
/bin/wslbridge2: Exit 1.
[sock_connect: 134)](note: backend error output: Assertion failed: connectRet == 0 (nix-sock.c: nix_vsock_connect: 134))
```

How can I launch wsltty?

WSL version:

```
> wsl --version
WSL バージョン: 2.3.24.0
カーネル バージョン: 5.15.153.1-2
WSLg バージョン: 1.0.65
MSRDC バージョン: 1.2.5620
Direct3D バージョン: 1.611.1-81528511
DXCore バージョン: 10.0.26100.1-240331-1435.ge-release
Windows バージョン: 10.0.22631.4317
```

wsltty(mintty) version:

```
mintty 3.7.6 (x86_64-pc-cygwin) - wsltty 3.7.6
```

**Comment by mikoto2000** [comment]
assert is this position.
https://github.com/Biswa96/wslbridge2/blob/5f444e639cc5ff6eff8945094ee68d0583adaafe/src/nix-sock.c#L134

**Comment by mikoto2000** [comment]
Restarting the PC several times resolved the issue.

**Comment by mintty** [comment]
> Restarting the PC several times resolved the issue.

Thanks for notifying. In that case, it might have been sufficient to do `wsl --shutdown`.
