### ISSUE TITLE
Still can not load WSL2 on wsltty 3.7.6, terminal closes instantly, no output

### ISSUE THREAD

**Issue by Raven-Singularity** [mintty/wsltty#361]
I installed the latest wsltty v3.7.6, but I am still having the same problem as before:

WSL2 Ubuntu does not load, the terminal just immediately closes.  Using `--hold=always` shows only an empty terminal window.

I figured I might have messed up the install by manually moving files to another folder, so I tried the quiet installer which installed to `%localappdata%/wsltty`, but it is the same, running the Ubuntu shortcut in that folder causes the terminal to close without outputting anything.

**How can I debug the issue?**

WSL2 loads fine from other terminals (CMD, Microsoft Terminal, ConEMU).

Loading the MinTTY.exe v3.7.4 or v3.7.6 from Cygwin works with this command:

`mintty.exe bash -c 'cd; bash --login'`

(I use the cd because otherwise it starts me in the Cygwin folder).

I was told that this "bash" is the old WSL bridge provided by Microsoft.

However, this leaves me with a half-working terminal where pressing Ctrl+C to terminate a command usually locks up the terminal.  I use GNU Screen, so it's not that bad, I can reopen the shell where I left off, but I want to have a working terminal.

**Comment by McG800** [comment]
I'm still having this issue as well.

**Comment by diddi-** [comment]
I'm having the same problem as well, I don't know how to debug this. The terminal just immediately closes.

**Comment by diddi-** [comment]
Alright, got it working.
1. Go to Windows Update in Settings
2. Advanced Options
3. Enable "Receive updates for other Microsoft products"
4. Go back to Windows update and Check for updates
5. This got me an update to WSL, download and install

After a reboot the terminal is working now for me.

**Comment by Raven-Singularity** [comment]
@diddi-:
Thanks for the suggestion.  Unfortunately, no WSL updates are available on my end.

**Comment by mintty** [comment]
Released 3.7.6.2.

**Comment by McG800** [comment]
This update has fixed this issue for me. Thank you!
