### ISSUE TITLE
3rd home folder and at a hidden place

### ISSUE THREAD

**Issue by detlefm** [mintty/wsltty#38]
It is not an issue but rather some thoughts. 
The default location (and I can't see how I can change it from the installer) is the Appdata\Local\....
Thats a hidden location and all changes to the home directory like theming is dealing with the Windows Explorer to show this location.
Ubuntu on windows provide a home folder (at a very hidden place), the user folder of Windows is also a "home" folder.
Well I can make a ln to (in my case) /mnt/c/Users/Detlef/AppData/Local/wsltty/home/Detlef/ like wslttyhome. Then I come around with the hidden folder issue.
But for a good integration of linux into Windows I think the binaries of wsltty must be either under Users/Detlef/<xxx> ( because it is  part of the Windows eco system) or under the linux home folder location.
But in both cases, I think, a good place for the mintty configuration files and folders are in the linux home folder because standard terminal settings under linux are in the home folder.

Maybe it is possible to provide a zip file with as a "portable" Version along with the batch files and some instructions.

**Comment by mintty** [comment]
Since mintty is not a Linux program but a cygwin program, it is not installed within the WSL domain, and I think it would not be a proper idea to place it in there. The place I chose for installation is the same as used by WSL itself.
The config file cannot be placed in your Linux home by installation default because your Linux login name is not known.

**Comment by mintty** [comment]
A portable version would need dynamic adaptation of the desktop shortcuts and scripts, thus extra effort that I'd prefer to save.

**Comment by detlefm** [comment]
Yes, it is all a little bit tricky. 
To get the login name(s) a "dir /B %LOCALAPPDATA%\lxss\home" will do the job. 
But it is no good idea to put the home there because changes made from Windows on the Linux filesystem will not always promoted. Maybe a bug or a feature. So just copy a file from c:\tmp to ..\lxss\home\user will run und you can see the file from windows but not see the file from linux. And when this happends when mintty saves the options nobody will understand this.
After looking around on the web I had decided for me to leave the default installation directory where it is (%LOCALAPPDATA%) and only change the home folder to %HOMEPATH%\MinttyHome. 
The steps are: 
Installation, 
copy from %LOCALAPPDATA%\wstty\home\<user> to %HOMEPATH%\MinttyHome. 
change the environment variable HOME to %HOMEPATH%\MinttyHome
create a .mintty\themes folder and add some theme files there
(the theme files are also tricky, some of them need to have unix linefeeds, so it might be better to edit them from within Linux or with Notepad++/ Vim)
The next bugfix update from Microsoft brings a new feature. You can call from Linux a Windows programs. And then it is possible to make all things (create a shortcut, move home folders,set environment variables and so on) from within a shell script.

As suggestion: It will be fine to install a theme folder and create some theme files. It will a good starting point for mintty beginners. Also, the trick with %HOME% var was not so easy to find.

Is there any reason not provide a binary version of mintty ?

**Comment by mintty** [comment]
I assume you would prefer wsltty to be a native WSL application. As I explained elsewhere, this is currently not possible. So it is and will remain for the foreseeable future an external application, with some obvious consequences and integration limitations.
I do not have the impression that you have an actual use case that does not work, or maybe you could describe it more clearly, please.

About the binary, I don't understand the question; the wsltty package contains one.

**Comment by mintty** [comment]
Revision of the config locations will be considered, and initial creation of the sub-folders may be a good point.
About the installer, see also issue 32.
Binaries are currently only provided within the wsltty installer because I see no other use case.
The language files are distributed as an archive in order not to have to tweak the installer every time a new one gets added. Therefore also the need for zoo, which is the only available unpacker that does not pull in a bunch of further dependencies.

**Comment by detlefm** [comment]
I have build for your system a new install.bat and build a tree of the components that must be installed on the users computer. Including shortcuts, desktop entries and context menu. All is packaged into a zip file but it is also possible to go the git way and the user will clone with git clone the tree ion his computer and run install.bat. The the issue 32 is fixed. The installer has also the capability to use an user defined folder as installation path. 
Not included is to change the home folder because mintty is using the %HOME% var to find the users home folder if it is not in the folder tree of mintty. And the %HOME% var ist also used from vim / vi and maybe other programs. And so it is not so easy to deal with different %HOME% vars.
I am not an experienced Git user - so I attached the file to this message.
To install the software call install.bat /? for a short usage, install.bat for default location and install.bat c:\folder for user defined folder
[wsltty_0.7.6.zip](https://github.com/mintty/wsltty/files/944525/wsltty_0.7.6.zip)

**Comment by mintty** [comment]
Thanks but to be honest, I don't have the nerve to analyse a huge bunch of fiddly changes, after having crafted all these scripts which are already fiddly enough, without being aware of an actual value-add.
Maybe it might be useful if you summarize, considering the discussion above, what you still see as an enhancement request and what the use case would be.

**Comment by detlefm** [comment]
Solved issues.
a) This installer overcome the problem with issue 32. 
b) An user defined installation path can be used (my wish , so issue 38)
c) Because a themes folder is created by default it is easy to put some themes into it (also issue 38)

The long story:

1. I had not changed anything on the provided programs like mintty.exe,, wslbridge, cygwin.dll, 
2. What I had changed is
2a) Changed the .bat files from hardcode "%LOCALAPPDATA%\wsltty\bin\mintty.exe"  to look into the bat file from which path it is running and start with the same path because I put the bat files into the bin directory. So there is no need to depend on environment variables like %LOCALAPPDATA%.

2b) In the zip file is same the directory tree (.\bin,\home, sorry I had forgotten .\tmp) as it is later in the install folder. So it is easy to copy all over (with xcopy) to the installation folder, I leave out the zoo.exe and uses unpacked po files in the users config folder.
2c) The install.bat makes:
Get from commandline the installation folder, xcopy the whole tree to the destination, rename the home\user folder to home\%USERNAME%. At this point all things are in place and can run (from the bat files).
Afterwards the bat file creates on the fly (with hardcoded pathes) and the help of a vbs script the shortcuts and put them first to a shortcuts folder, after then they are copied to the start menu and to the desktop.
2d) I have created a docs folder and put all docs into it. I am not sure if it is not necessary for licensing to put more attention  to the licenses. A separate folder makes it easy to maintain all this stuff on one place and maybe put later a link into the start menu.


But one of my intentions was to create a structure where you can install this more the git way
with "git clone https://github.com/mintty/wsltty". And run the install.bat from inside the created wsltty folder or just copy it to the destionation path. And not to get a windows installer exe you can trust or not. And for anybody without git: He can download a zip from git and run the install.bat

You must say if the install.bat is enough self explained or what additional documentation must be provided. I think the audience are linux people (who else want to play with the linux commandline). 
And this guys have normally more experience then the standard windows user.

What I have not done (but it was not done also with the current installer) is to clean up all (uninstall) and not only clean up the start menu and desktop. This routine I leaved mostly untouched. What I changed (same as for all other bat files) the way to determinat the install bin path. The current installer has hardcoded "%LOCALAPPDATA%\wsltty\bin" because the installtion folder is fixed. My installer looks on the running path and find out where the binaries are located.
`set _mypath=%~dp0
if "%_mypath:~-1%"=="\" set _mypath=%_mypath:~0,-1%`

I have (hopefully well) documented the install.bat. First for you and second for every user to understand what happend. I had learned a lot of looking into source codes and so I will give others the same chance.

**Comment by mintty** [comment]
> a) This installer overcome the problem with issue 32.

which can also be overcome by simply clicking "Run anyway" which I have now mentioned on the wsltty project page

> b) A user defined installation path can be used (my wish , so issue 38)

If this is your main desire, I understand it partially but I do not plan to support it, because I want to keep things simple and because as a package supporting WSL in parallel, my choice was to follow WSL in basic installation strategy: fixed target, installer, no deinstallation in Start menu. I do not see why wsltty would need to provide more installation comfort than WSL itself, sorry.

> c) Because a themes folder is created by default it is easy to put some themes into it (also issue 38)

I'll change the package to create the config subfolders, and I'll think about the config directory, see also #30.

> ... So there is no need to depend on environment variables like %LOCALAPPDATA%.

That's a standard Windows variable which always provides a reasonable personal environment reference.

> vbs

Not sure but I think VBS is not standard part of Windows.

> [install] with "git clone https://github.com/mintty/wsltty". And run [an install script]

This is a good proposal and I'll check how to easily provide this.

> audience ... have normally more experience then the standard windows user.

That does not convince me of making things more complex than necessary.
The more experienced people are, the more they do, and the more grateful are they that not everything is asking them to invest their knowledge ...

**Comment by detlefm** [comment]
I have made the installer on a fresh install of Windows 10 Professional ( Virtualbox) and as far as I know the linux subsystem only runs on Windows 10 Professional. So we can assume that a wsl_mintty user must run this machine. Even if this changed in the future it is also possible from Powershell but for me was vbs easier. I have minimal knowledge of vbs but no knowledge of Powershell.
But what ever - it is your project and your decision..
From my point of view you can close this issue. I wanted to see how long I needed for an alternative installer and I enjoyed it.

My recommendation would be to put some theme files into the theme folder. There are lot on github.
Clicking  "run anyway" is one of things I forbid everybody in my family and even me test this type of software very, very carefully in a secure environment. 

> I do not see why wsltty would need to provide more installation comfort than WSL itself, sorry.

WSL has no cofiguration, no profiling, no themes nobody must touch it. It can run where ever. But even then it might be fine when a backup knows where it is located.
Mintty is a GUI. It has all. A profile file, themes, tranlastion package. And that are things users deal with. And thats on a fixed (hidden) location?

**Comment by mintty** [comment]
Released 0.7.7.
