### ISSUE TITLE
Scrollbar doesn't work

### ISSUE THREAD

**Issue by synle** [mintty/wsltty#39]
Scrollbar doesn't work tmux

I can only see the last page, can't go back to the previous screen.

Scrolling causes the input `^B` to populate, and not scrolling.

UPDATE: Found the solution, added `set -g mouse on` to your tmux settings `~/tmux.conf``

**Comment by mintty** [comment]
Works here as usual. Describe your symptom precisely. How is ^B involved?
Are you maybe on the alternate screen?

**Comment by synle** [comment]
@mintty Look like the buffer doesn't even register stdout properly. 

Look at this screenshot, notice the scrollbar is greyed out. It only kept the last page of stdout.
![image](https://cloud.githubusercontent.com/assets/3792401/25109756/e8544632-2393-11e7-960f-84a14d7d0d10.png)

**Comment by synle** [comment]
@mintty Essentially disable tmux, everything seems to work now.

**Comment by synle** [comment]
I found the solution to my issue, simply add this to your `tmux.conf` fixed the issue

`set -g mouse on`

**Comment by mintty** [comment]
As I indicated above, likely you were on the alternate screen which does not have a scrollback.
Closing?
