### ISSUE TITLE
.minttyrc is being saved in wrong folder (Windows username vs. Linux username)

### ISSUE THREAD

**Issue by czekaj** [mintty/wsltty#4]
Yesterday I noticed that when I'm trying to save MinTTY settings it is trying to put .minttyrc in a folder that doesn't match my Linux username. It is using the Windows username which shouldn't be happening.

E.g. it tries to save it in /home/winuser/.minttyrc but it should be saving it in /home/linuxuser/.minttyrc

**Comment by mintty** [comment]
Mintty is still a Windows/Cygwin program, so it refers to the Windows username. It saves into its own dedicated /home hierarchy, anyway, so there's no point in using the Linux username there.
If you want it to save anywhere else, e.g. your Linux home directory, you can add option `-c` to its invocation in the shortcuts.

**Comment by czekaj** [comment]
Got it. Thanks!
