### ISSUE TITLE
Running under Administrator - empty console

### ISSUE THREAD

**Issue by whitecolor** [mintty/wsltty#43]
Any thoughts why can not run `wsl` from commanlines that are run under Adminstrator?

![image](https://cloud.githubusercontent.com/assets/736697/25896282/fbbb18d4-359c-11e7-9f29-407a1e972ae6.png)

vs under current user:
![image](https://cloud.githubusercontent.com/assets/736697/25896314/2a60733c-359d-11e7-8d43-c3a9fb86d4d1.png)

**Comment by mintty** [comment]
That works fine here.
Please cross-check by calling bash.exe directly, without wsltty.
You may also try to trace your profiles (~/.profile, ~/.bashrc, /etc/profile, /etc/bash.bashrc).

**Comment by whitecolor** [comment]
Hm... right
![image](https://cloud.githubusercontent.com/assets/736697/25920707/44d2608c-35ec-11e7-9f6c-fe4fd8120fa9.png)

It seem to come that way probably after update to Windows insiders preview. Didn't find the problme in google.

**Comment by mintty** [comment]
So can we close the issue?
Although we might still be bothered that there is no proper feedback if this happens within mintty.
@rprichard, any chance that wslbridge might catch this case and report an error?

**Comment by rprichard** [comment]
I would think wslbridge could do a better job of handling this situation.  It looks like it hangs forever, waiting for the wslbridge-backend to connect.  If I kill the wslbridge frontend (e.g. Ctrl-C), it leaves the bash wrapper running forever in its hidden console.  I'm not precisely sure of the fix, but it could time out or kill the bash wrapper process.  In new enough versions of Win10, I think wslbridge could redirect stdout and capture the error.  It's possible in Win10 15063.  (I just noticed that the bash.exe error is UTF-16, but ordinary WSL programs output a narrow encoding -- UTF-8 maybe?  Yuck.)

**Comment by mintty** [comment]
I may have to add another option `-h error` to the invocation to make the error message visible (or the window will just flicker and close), or imply that under the `--wsl` option.
Then the error message output breaks after 255 bytes and mintty will insert its own error message `/bin/wslbridge: Exit 1.` inmidst of the /bin/bash message. Hmm, maybe, I can add a delay...
