### ISSUE TITLE
Why my mintty cannot run windows commands

### ISSUE THREAD

**Issue by yang286** [mintty/wsltty#44]
Hey everyone. Im Roy.
I got mintty shell after I installed Github. I didnot install CYGWIN.
If I run mintty from Github which i click 'open git shell', then I can run all windows commands.
If i run mintty by itself, then I cannot use any windows commands, why? It is so weird.
Here is the pic.
http://blog.163.com/dsh808@126/prevPhDownload.do?host=dsh808@126&albumId=310061228&photoId=9790657658
The left side is that i opened by mintty itself, so all windows command cannot use.
The right side is that i opened from Github, all windows commands no problem.
Thanks for any help.
by the way, why I cannot add my pic here??

**Comment by yang286** [comment]
anybody can help?
thanks a lot

**Comment by mintty** [comment]
Described your problem clearly.
Drag-and-drop a screenshot to the comment.

**Comment by mintty** [comment]
What do you mean by "run mintty by itself"?

**Comment by yang286** [comment]
Hey Sir, thanks for your help. this windows I opened from gitshell, so all the commands are no problem.
![gitshell](https://cloud.githubusercontent.com/assets/28585814/25955280/60fd4f38-369b-11e7-9e6c-cb8954e4bf21.png)

And This window I opened from Mintty, but only little commands can be used. this is my problem. How can I use the commands such like dir, ls etc? thanks so much sir.
![mintty](https://cloud.githubusercontent.com/assets/28585814/25955447/e24085ba-369b-11e7-9192-4998a04076ed.png)

**Comment by yang286** [comment]
See sir, in this window, it work just like in win cmd window, all commands that can run in win cmd also can run here.
![gitshell](https://cloud.githubusercontent.com/assets/28585814/25955920/0965d072-369d-11e7-8d5f-1af7aec7ab5f.png)

But this window is different. commands can run in win cmd that cannot run here. how can i use all windows commands here Sir? Is my questions clear? Sorry for my English Sir.
![mintty](https://cloud.githubusercontent.com/assets/28585814/25956070/5f4fd532-369d-11e7-8732-81485742cc9e.png)

**Comment by yang286** [comment]
this 2 windows should be same things i guess, because they are from same window in the bottom you can see. This is very strange to me. 
![mintty](https://cloud.githubusercontent.com/assets/28585814/25957538/24fa74ec-36a1-11e7-9b87-991b37e6c8da.png)

**Comment by mintty** [comment]
If `ls` and most basic commands are not found, most likely /usr/bin is missing in your PATH variable.
However, this does not happen here if I start Git Bash, and start another mintty from there with Alt+F2 or a `mintty` command. My question remains unanswered, how *precisely* you started the disfunctional terminal.

**Comment by mintty** [comment]
This isn't really related to wsltty, right? Let's continue in mintty/mintty#658.

**Comment by yang286** [comment]
Hi Sir, this is where I started the Mintty, and I had made the /usr/bin in my system PATH variable.
C:\Users\roy\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\usr\bin      This fold had already been in my system PATH variable.
![mintty](https://cloud.githubusercontent.com/assets/28585814/25993258/050bb39e-373c-11e7-90f9-d8a6a7f52108.png)

**Comment by yang286** [comment]
And how about if I install a new mintty command terminal, then can I use the windows command in mintty terminal Sir? thanks for your great help Gentelmen.
