### ISSUE TITLE
Can't save options (0.7.7.1)

### ISSUE THREAD

**Issue by JDQuackers** [mintty/wsltty#45]
This is almost identical to issue #42, but on the latest version 0.7.7.1 with slightly different error:

![screenshot 2017-05-24 14 39 44](https://cloud.githubusercontent.com/assets/1397893/26407498/9c74bea2-409b-11e7-94f5-e5a289f2ce18.png)

I've never installed wsltty before, so I just did a fresh install. I then:

- Open a terminal via the auto-created desktop shortcut "WSL Bash ~ in Mintty"
- Click the icon -> Options...
- Modify window size
- Click "Save"

An error window pops up saying "could not save options to.." (see attached). The path it is using is %LOCALAPPDATA%\wsltty\home\$user\.minttyrc

Looking in this directory in Windows there are only two dirs, bin and usr:
![screenshot 2017-05-24 14 51 16](https://butt.githubusercontent.com/assets/1397893/26403986/9d2b02bc-4090-11e7-9d75-00188213de6d.png)

... is there some step I missed needing to invoke/setup a user in cygwin so that this home dir is created?

**Comment by mintty** [comment]
The configuration location from your error message is not the intended one.
I have the suspicion that the creation of the dedicated shortcuts may have failed during installation, so that the package-supplied default shortcuts were installed instead.
Can you please check that: On the desktop shortcut, right-click and open "Properties", copy the contents of the "Target:" field and report it here.
As a workaround, I can adapt the default shortcuts to point to the new default location already.

**Comment by JDQuackers** [comment]
Sure:

`%LOCALAPPDATA%\wsltty\bin\mintty.exe --wsl --configdir="%APPDATA%\wsltty" -o Locale=C -o Charset=UTF-8 /bin/wslbridge -C~ -t /bin/bash`

**Comment by mintty** [comment]
This does not confirm my suspicion.
Please check your %APPDATA% folder. Was the wsltty subfolder created? Is it writable?

**Comment by JDQuackers** [comment]
Well, `%APPDATA%\wsltty` was created and contains lang, sounds and themes, which are all empty. No config folder. I assume if it exists, then it's writable... but writable by whom? My windows user can create/edit a text file within that folder

**Comment by mintty** [comment]
So that's fine. There is no additional config folder. The config file would be `%APPDATA%\wsltty\config` -
What happens if you add such a file, and place a setting in it, e.g.
`Font=Comic Sans MS`
?

**Comment by JDQuackers** [comment]
Hmm... well. I did that and opened a new terminal via the Desktop shortcut, and now I get a blank window with `/bin/wslbridge -C~ -t /bin/bash` in the title... it's just hung. I deleted the `config` file and it's still doing that so I don't think this behavior is related. Regardless, using the Options dialog in this state still provides the same behavior:
![screenshot 2017-05-24 15 57 05](https://cloud.githubusercontent.com/assets/1397893/26406830/c68940c0-4099-11e7-9e56-8ce7b1b7f95f.png)

So this looks the same as #43 ... I tried to run the shortcut once as admin "Run as administrator...", and now if I *do not* select that, it hangs. If I run as admin, then it opens normally. In this mode, the font is still default (not Comic Sans) and the "Save" button still prompts with the exact same error as this most recent screenshot

I can do a full uninstall/reinstall next, or leave it like this if you'd prefer to continue to debug either issue?

**Comment by mintty** [comment]
Puzzled. I'll have to try myself later...

**Comment by danielrndm** [comment]
I'm having the exact same issue. I just installed wsltty today. 

Here's what I've been trying:

1. Open Cmder
2. Create task: `%LOCALAPPDATA%\wsltty\bin\mintty.exe --wsl --configdir=%USERPROFILE%\AppData\Roaming\wsltty -o Locale=C -o Charset=UTF-8 /bin/wslbridge -C~ -t /bin/bash`
3. Run new console window with newly created task.
4. Try to save options.
A dialog window pops up indicating same issue as OP. 

It's also worth noting that this happens even if I run it from Desktop shortcuts or from the wsl*.bat files. Seems to me that it's not taking the --configdir option and going always with the default path `/AppData/Local/wsl/home/<user>/.mintty.rc`

![image](https://cloud.githubusercontent.com/assets/4911465/26428779/c9e952e4-40a0-11e7-92a6-9215792df323.png)

**Comment by JDQuackers** [comment]
Hey, I was able to correct this behavior by changing the shortcut to:
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --wsl --config="%APPDATA%\wsltty\.minttyrc" -o Locale=C -o Charset=UTF-8 /bin/wslbridge -C~ -t /bin/bash`

I looked at the [mintty docs](http://mintty.github.io/mintty.1.html) and noticed there was no `configdir` option, only `config`, which should point to a filename... 

Now, after making this change, saving options works correctly; however the Administator issue still stands. I've ticked the "Run as Administator" option in my shortcut as a workaround for now

**Comment by mintty** [comment]
The option --configdir exists and is described in the manual.
The problem is that it does not enforce the config file in that directory if it does not exist already.
If you create an (empty) file %APPDATA%\wsltty\config before starting the terminal, it should work.

I had initially designed --configdir to cause saving always to go there but later revised that to allow the option to use common configuration with other mintty installations, using the %APPDATA%\mintty directory, so not to override the config file in there with the new one (in %APPDATA%\wsltty) if it does not exist. Apparently there is a dependency loop in the functional design here that needs to be resolved.

**Comment by JDQuackers** [comment]
@mintty wow, I can't believe I missed that. I was looking at an old StackExchange thread when I first noticed `--configdir` missing from the `--help` output and then didn't scrutinize the actual manual well enough. Sorry about that

**Comment by mintty** [comment]
Released 0.7.7.2 with workaround. Please recheck.

**Comment by JDQuackers** [comment]
Works great, thank you
