### ISSUE TITLE
Add "open mintty here" to context menu

### ISSUE THREAD

**Issue by nagman** [mintty/wsltty#48]
Hi,

First of all, great project! I love it!

Do you know what I should enter in the registry command in order to add a "Open Mintty here" to the context menu?

I tried `%LOCALAPPDATA%\wsltty\bin\mintty.exe --wsl --configdir="%APPDATA%\wsltty" -o Locale=C -o Charset=UTF-8 /bin/wslbridge -C~ -t /bin/zsh` but Windows can't find %LOCALAPPDATA%.

Thanks!

Quentin

**Comment by mintty** [comment]
try Start Menu – WSLtty – add to context menu

**Comment by nagman** [comment]
I don't see any "add to context menu" when I right click on WSL Bash in the start menu.

The only way I know to add something to the context menu is to modify the registry.

**Comment by mintty** [comment]
In the Start Menu, go to the WSLtty folder and open it, there should be an "add to context menu" entry.

**Comment by nagman** [comment]
Wow! Superb, thanks a lot!
