### ISSUE TITLE
Update issues to 0.7.8.1

### ISSUE THREAD

**Issue by willpower232** [mintty/wsltty#49]
I am unable to update to the latest version. I am running a standard account and get the following error message:

```
/bin/wslbridge: Exit 1.
wslbridge error: failed to start backend process
```

If I try 0.7.8, the wsltty window closes immediately on opening but I am able to install 0.7.7.2 and resume usage.

Interestingly, I get the same error if I install 0.7.7.2 as an administrator and run it as my standard user.

**Comment by mintty** [comment]
Works here.
@rprichard , any idea?

**Comment by AndySw** [comment]
I have the same problem

**Comment by rprichard** [comment]
I don't know what's going wrong.  I would guess some kind of permissions issue.  I just installed wsltty 0.7.8.1, and it worked fine, with both my ordinary administrator account and a limited account.  I then ran `wslbridge.exe` from an ordinary console running `cmd.exe`, and that too worked fine:

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\luser>cd AppData\local\wsltty\bin

C:\Users\luser\AppData\Local\wsltty\bin>wslbridge.exe --version
wslbridge 0.2.2

C:\Users\luser\AppData\Local\wsltty\bin>bash.exe -c "./wslbridge-backend --version"
wslbridge-backend 0.2.2

C:\Users\luser\AppData\Local\wsltty\bin>wslbridge.exe
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

luser@duck15063:/mnt/c/Users/luser/AppData/Local/wsltty/bin$ ls
cygwin1.dll  cygwin-console-helper.exe  mintty.exe  wslbridge-backend  wslbridge.exe  zoo.exe
luser@duck15063:/mnt/c/Users/luser/AppData/Local/wsltty/bin$ exit

C:\Users\luser\AppData\Local\wsltty\bin>
```

The wsltty installer places the files in the current user's AppData directory, so I'm not sure how to install as an admin and run as a different user.  Copy it somewhere public, I guess?  Maybe I'll give that a try.

**Comment by rprichard** [comment]
> I'm not sure how to install as an admin and run as a different user

I think this refers to running the installer elevated (i.e. "Run as Administrator"). 

I tried installing 0.7.7.2, running the installer as elevated, then running wsltty normally (non-elevated), and it worked fine.

FWIW, I'm using Windows 10.0.15063.413.

It's also important not to enable the legacy console.  (This checkbox must not be checked, because the legacy console is incompatible with the WSL wrapper, `bash.exe`: https://www.isunshare.com/windows-10/enable-use-legacy-console-for-command-prompt-in-windows-10.html).  With 0.7.8.1, though, if it *is* checked, wsltty displays an error:
```
/bin/wslbridge: Exit 1.
wslbridge error: failed to start backend process
note: bash.exe output: Unsupported console settings. In order to use this feature the legacy console must be disabled.
```

**Comment by saivert** [comment]
I get a more detailed error message: 
```
wslbridge error: failed to start backend process
note: backend error output: /mnt/c/Users/Nicolai/AppData/Local/wsltty/bin/wslbridge-backend: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /mnt/c/Users/Nicolai/AppData/Local/wsltty/bin/wslbridge-backend)
```

**Comment by rprichard** [comment]
I suppose that when I build wslbridge, I need to have the oldest possible WSL environment installed on my machine.  That's a pain.

**Comment by rprichard** [comment]
I released wslbridge 0.2.3, whose binaries are built on Ubuntu 14.04 instead of Ubuntu 16.04.  I also started compiling the backend with `-static-libgcc` and `-static-libstdc++`, which I don't think it *necessary*, but maybe it'll be helpful.  I believe the binaries in `wslbridge-0.2.3-cygwin64.tar.gz` are the ones wsltty uses.

**Comment by mintty** [comment]
Thanks a lot. Released 0.7.8.3. Please recheck.

**Comment by willpower232** [comment]
I haven't been blessed with the Creators Update yet so my Bash is still Ubuntu 14.04.5

Version 0.7.8.3 works for me

**Comment by simoncpu** [comment]
I'm also experiencing the same problem. I had to record my screen using my phone because I had trouble seeing the error message.

wsltty: 1.8.5.2
Windows 10: 1803

The same wsltty version on my other computer, which is running Windows 10 version 1709, works fine without any problems.

**Comment by Biswa96** [comment]
What error did you see? There are many problems with WSL in Windows 10 1803.

**Comment by simoncpu** [comment]
The exact error is:

`wslbridge error: failed to start backend process
note: backend error output: /bin/bash: /mnt/c/Users/Surface: No such file or directory`

Hmm, I just realized that the path wslbridge-backend path is incorrect. My user directory (I just used the default) is C:\Users\Surface Pro 4. Issue with spaces in the directory, maybe?

**Comment by simoncpu** [comment]
I manually ran wslbridge:

    C:\Users\Surface Pro 4\AppData\Local\wsltty\bin>wslbridge.exe
    wslbridge error: failed to start backend process
    note: backend error output: /bin/bash: /mnt/c/Users/Surface: No such file or directory

**Comment by Biswa96** [comment]
Oooo.... That issue was solved in latest commit in wslbridge https://github.com/rprichard/wslbridge/commit/47b41bec6c32da58ab01de9345087b1a4fd836e3

If you want you may compile that wslbridge frontend. Or @mintty may release apatched version.

**Comment by simoncpu** [comment]
Awesome, thanks for your help @Biswa96! :)
