### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by AsharLohmar** [mintty/wsltty#50]
Hi. 
First let me thank you for all the grate work, I just have a little thing to ask. 
Could you add the version number "somewhere" ? ... as a comment in the *.bat files would suffice.
So I could easier compare the installed version with the one available on the repo.
Thanks

**Comment by mintty** [comment]
The next version will display the wsltty version in About (#35).
I can add a VERSION file to the distribution additionally, if needed, but I think About would be fine.

**Comment by mintty** [comment]
Released 0.7.8.3, showing wsltty version in About info. The update availability notification in the Options dialog, however, still refers to the mintty version.
