### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by shevegen** [mintty/wsltty#51]
Hey guys,

Would you consider adding a screenshot, on the main readme, how it looks? Just one image.

Not sure if this is a useful "issue" - reason being I would like to see how mintty looks on first startup.

Feel free to close this issue at any moment in time.

**Comment by mintty** [comment]
Well, it can look quite differently, depending on your configuration, but yes, I'll add a screenshot.
Meanwhile, you can check out the screenshots on the mintty home page http://mintty.github.io/.
