### ISSUE TITLE
Can i have a setting to adjust font's height?

### ISSUE THREAD

**Issue by Po-wei** [mintty/wsltty#53]
I think the font height a little bit small?

how can i change it?

**Comment by mintty** [comment]
Open the Options dialog from the system menu (click top-left icon), section Text, Select...

**Comment by Po-wei** [comment]
Well, I think the fonts in WSL seem to be squeezed in the vertical way, so i wonder whether i have can change the ratio between height and weight, not just font sizes.

The picture below is the differenece between cmd and WSLtty.
In cmd, each Chinese character like an square while in wsltty they seem to be rectangle.

![image](https://user-images.githubusercontent.com/17596021/28409997-e9d44d2a-6d6e-11e7-8a85-2345bdc8ca23.png)

Am i too sensitive?

**Comment by mintty** [comment]
Font and character geometry depend very much on the individual fonts. Try some others until you find a nicer result for you.
While in theory, the aspect ratio height/width could be tweaked, this is not in line with the idea of font design, and I've never had that request before.
You can, however, adjust the gap between lines with the config parameter RowSpacing.

**Comment by mintty** [comment]
Can we close the issue or do you still have a request?

**Comment by Po-wei** [comment]
Oh I see!
