### ISSUE TITLE
Warn when closing last WSL terminal window

### ISSUE THREAD

**Issue by nyuszika7h** [mintty/wsltty#54]
It could be useful to display a confirmation dialog when closing the last open WSL terminal window, as that kills all WSL processes.

I'd be fine with just warning on closing the last WSLtty window if that's simpler, as I'm not going to use WSL in other terminal emulators side-by-side with mintty anyway.

**Comment by mintty** [comment]
Please describe more precisely which processes are closed. Background processes that are detached from any terminal should normally not be affected. Try `setsid`.

**Comment by nyuszika7h** [comment]
No, it kills all background processes when there is no `bash.exe` process running. This also happens with the normal "Bash on Ubuntu on Windows" shortcut, it's not specific to mintty.

**Comment by mintty** [comment]
So than you should complain to Microsoft, not here. Please close.

**Comment by mintty** [comment]
Any success with `setsid`?

**Comment by nyuszika7h** [comment]
Nope, the processes still get killed. Also, I was not complaining, just asking a suggestion. Allowing background processes is one of the top feature requests on their UserVoice, maybe they'll implement it eventually. But if they just added a prompt like this, I don't see how it would work with wsltty, that would only apply to `cmd.exe`.

**Comment by mintty** [comment]
Not sure what you mean by "prompt like this"; if they fix it, it should work in wsltty as well.
