### ISSUE TITLE
Context menu options failed to install

### ISSUE THREAD

**Issue by ly2048** [mintty/wsltty#58]
The "add context menu entry" shortcut does not work at all. Tried log out, reboot, refresh, run as admin, nothing works.

Executing the shourtcut shows even no logging window, which makes me completely unable to see what happens. And it uses `dash.exe` makes it even more difficult to debug.

**Comment by ly2048** [comment]
Got a work around. Install WSLtty 0.7.8.3, add to context menu, then reinstall latest 1.7.9.

**Comment by webskin** [comment]
+1

**Comment by mintty** [comment]
Released 1.8.0. Please recheck.
