### ISSUE TITLE
mintty.exe deletes itself?

### ISSUE THREAD

**Issue by ddx0** [mintty/wsltty#61]
Host: Windows 10 Home, Version 1703, OS Build 15063.608

Just freshly installed Bash on Ubuntu on Windows. Ran "apt update", all updates installed. cmd.exe, even with the apparent upgrades, is still terrible. I installed wsltty to be able to use mintty as a replacement. Installation is fine, and upon first attempt at opening wsltty through the installed Start Menu shortcuts, mintty.exe opens like normal. However, seconds after getting a working shell, mintty.exe suddenly closes with no warning. A look in the task manager shows the process has terminated (and is no longer listed). Attempts to reuse any of the shortcuts to open wsltty do nothing. Taking a look in "-\AppData\Local\wsltty\bin" the first time around shows mintty.exe missing from the folder entirely. Attempts to run "uninstall.bat" seem to do nothing at all. A second look at "-\AppData\Local\wsltty\bin" shows mintty.exe has reappeared, albeit with a size of 0 KB. Attempts to run again cause a Windows 10-style message, "This app can't run on your PC", but I suspect that message is of little value because I think the new mintty.exe that has appeared is a blank file. Only way to solve the issue is to rerun the installer, but the entire process repeats again. I'm not sure where to go from here.

**Comment by willpower232** [comment]
Are you running any antivirus or antimalware program that isn't Windows Defender?

**Comment by ddx0** [comment]
Sorry for the delayed response, I am also using Avast.

**Comment by willpower232** [comment]
Have you tried disabling Avast and reinstalling wsltty?

**Comment by mintty** [comment]
Closing because it's not mintty that deletes itself.
