### ISSUE TITLE
Unable to use after updating to 1.8.0

### ISSUE THREAD

**Issue by willpower232** [mintty/wsltty#64]
Upon installing 1.8.0 by running the release .exe, I am no longer able to open any prompt.

I get the following message:
![image](https://user-images.githubusercontent.com/1619102/31882989-65c6700a-b7e0-11e7-8f26-81b12e4cc2e1.png)

I presume that the empty parameter WSL on the shortcut "WSL Terminal %" would be to blame?
The shortcut path I have is `%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= -h err --configdir="%APPDATA%\wsltty" `

I am using the original WSL and have not installed one from the store. I am on Windows 1703.

**Comment by mintty** [comment]
Ah! So without any store version, it seems that the concept of "default distribution" is not yet deployed.
(The command line is correct and would invoke the default distribution if there was any.)
Please use the specific shortcut "Bash on Windows Terminal" from the Start Menu instead for now.

**Comment by willpower232** [comment]
i.e. don't use this version of wsltty until I have a version from the Windows Store?

I can reinstall 1.7.9 and use that just fine.

**Comment by mintty** [comment]
No, I mean, please try to run "Bash on Windows Terminal" from the Start Menu. Does it work?
Also, please export the following registry subtree:
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]
and paste or upload the output file here.

**Comment by willpower232** [comment]
Oh! I literally don't have that option I'm afraid
![image](https://user-images.githubusercontent.com/1619102/31897649-f1b18fe0-b80e-11e7-804d-1f3654f5759b.png)

Registry entries as follows
![image](https://user-images.githubusercontent.com/1619102/31897755-3cf95136-b80f-11e7-8eb1-06295542e6c6.png)

**Comment by mintty** [comment]
So let's find a workaround until this is fixed:
Do you have the Windows tool `wslconfig` available?
Can you set a default distribution with `wslconfig /s Legacy`?
Or you'll have to revert to the previous command line for now:
`%LOCALAPPDATA%\wsltty\bin\mintty --wsl -h err --configdir="%APPDATA%\wsltty" -o Locale=C -o Charset=UTF-8 /bin/wslbridge -C~ -t /bin/bash`
so you could still use the updated mintty version.

**Comment by willpower232** [comment]
No sign of wslconfig, I think that comes with the store versions which I don't think I can get until I get up to the Fall Creators Update. I'll try Fall Creators on a different machine if I can...

Using that shortcut as specified works nicely for now.

**Comment by nshtg** [comment]
Have you considered calling wsl.exe instead of bash? wsl.exe will respect the default shell set by the user, which means you can use ```chsh``` like on a "real" unix system.

**Comment by mintty** [comment]
This does not seem to be related to this issue;
* With previous Windows releases that would support the Legacy "Bash on Windows", `wsl` was not yet available.
* With recent Windows releases, `bash.exe` also invokes the user's default shell.
* The Windows gateway (`bash.exe` vs. `wsl.exe`) is invoked by the tty gateway (`wslbridge`) and cannot be chosen by mintty. (There was discussion about an option to change it (#56, rprichard/wslbridge#14) but with the result it's not necessary in recent Windows releases.)

**Comment by fmoo** [comment]
This is happening to me also, on a fresh install of windows.  I installed everything using the standard methods also.  The "Bash on Ubuntu on Windows" cli shortcut is working just fine for me.

**Comment by willpower232** [comment]
@fmoo if you right click "WSL Terminal" on the start menu and choose "More" > "Open File Location" you can get to the shortcut file and change the properties so it links to the reference above (here https://github.com/mintty/wsltty/issues/64#issuecomment-338701917)

I'll hopefully be updating to Fall Creators Update shortly so will switch to a store installed version and re-install 1.8.0 to get everything back to normal although I appreciate not everyone would be so keen to update.

**Comment by williscool** [comment]
Can confirm that downgrading to "1.7.9" just makes everything work.

My installation steps if it helps anyone at all.

- Install `1.8.0`
- (flally around  the internet trying to google "WSL distribution not found")
- (confusedly try to change the parameters to the short cuts. and figure out what options can be passed to WSL="" [have fun googling that lol])
- Install `1.7.9` over the original installation
- everything just works

**Comment by willpower232** [comment]
Interestingly my shortcuts did somehow reset themselves to the default values just now and I had to re apply the previous commands as before.

**Comment by mintty** [comment]
Released 1.8.1. Please recheck.

**Comment by willpower232** [comment]
Alas it is still broken. Is there any help I can be in debugging?

**Comment by willpower232** [comment]
I had to delete all my shortcuts from the start menu and reinstall and now it seems to be working, hooray!

**Comment by jshap70** [comment]
I'm still having these issues on 1.8.1, stuck on the anniversary edition because it's an enterprise machine 😕 
I get `Unknown option '--WSL='`

**Comment by willpower232** [comment]
@jshap70 have you tried manually removing all your WSL shortcuts and reinstalling?

**Comment by jshap70** [comment]
I have. it wasn't a case of me using an old shortcut, it was a new one that I was using. I'd changed the icon on the old ones, so that's how I could tell them apart. and I'd tried generating new ones by using the shell script in the installation dir. 
What is the shortcut link supposed to look like now for the `LEGACY` install? Maybe I can help see if it's working at all

**Comment by jxfreeman** [comment]
For me, I have the wslconfig tool.  Running it with the /l option showed the current installation of ubuntu as:

Ubuntu-18.04

Using that I modified the shortcut --WSL= parameter to --WSL=Ubuntu-18.04 and it started properly launching.

**Comment by roachsinai** [comment]
@jxfreeman thanks a lot!
