### ISSUE TITLE
Update makewinx.cfg

### ISSUE THREAD

**Issue by exjam** [mintty/wsltty#65]
With https://github.com/mintty/wsltty/commit/d5cc2bfe777814b6509a4422c7476ed148b34616 you removed some shortcuts such as "WSL % in Mintty.lnk" , now `make` leads to this IExpress error:

```
---------------------------
IExpress Wizard
---------------------------
Unable to find .\WSL % in Mintty.lnk.  Please check your packaged file list.
---------------------------
OK   
---------------------------
```

**Comment by mintty** [comment]
Released 1.8.1.
