### ISSUE TITLE
Error: could not fork child process: Resource temporarily unavailable 1.4.1

### ISSUE THREAD

**Issue by alix59** [mintty/wsltty#66]
hello I just installed pocketmine and an error follows the instalation in a command page "Error: could not fork child process: Resource unavailable"
to help me because I did a tour on the forums and it does not help me
for a while there is the base file but without the server.properties file

Thanks for helping me

(if the translation is bad, I'm FrenchXD)

-------------------------------------------------

bonjour je viens d installer pocketmine et une erreur suit l instalation dans une page de commande "Error: could not fork child process: Resource temporarily unavailable " 
pourier vous m aider car j ai fait un tour sur les forum et cela ne ma pas aider
pourtemps il y a bien les fichier de base mais sans le fichier server.properties

mercie de m aider

(si la traduction est mauvaise ses que je suis francaisXD)

**Comment by mintty** [comment]
What is pocketmine?
Likely duplicate of #25.
