### ISSUE TITLE
Bad performance after running 'curl wttr.in'

### ISSUE THREAD

**Issue by hsiktas** [mintty/wsltty#67]
(I don't have a cygwin installation anymore therefore I am unsure if this repo is right or if I should open this issue in the mintty repository instead.)
I am using wsltty 1.8.1 with zsh and after running 'curl wttr.in' the terminal emulator starts to lag a lot when resizing the window or just selecting the curl output with the mouse.

As a comparison, the Electron-based terminal emulator "Hyper" does not lag at all with this output and Microsoft's own conhost.exe does also shows no signs of a slowdown.

**Comment by mintty** [comment]
What is this wttr.in? What is the actual output of the curl command? Mintty is not running

**Comment by mintty** [comment]
Without evidence of an issue, the issue can only be closed.
