### ISSUE TITLE
Windows Task bar icon

### ISSUE THREAD

**Issue by Po-wei** [mintty/wsltty#68]
![image](https://user-images.githubusercontent.com/17596021/32841360-042fbacc-ca55-11e7-90f0-2c4dec3db4df.png)
icon has some zigzag at the border
Maybe it need some higher dpi version of icon.

It is a 22" monitor with 1920*1080 resolution.

**Comment by mintty** [comment]
WSLtty reuses the icon from the respective WSL distribution. It should be same as the one used if you invoke a WSL session the original way, in a Windows command window.

**Comment by Po-wei** [comment]
I activate this by click the icon form the start menu called Ubuntu terminal.
Would it cause some problem?

comparison
left WSLtty : right original WSL
![image](https://user-images.githubusercontent.com/17596021/32842948-729f8a74-ca59-11e7-8930-3b6758cb9f9a.png)

on my 13" laptop, they are almost identical
However, on my 22" monitor(DPI ~100) the difference stand out.

**Comment by mintty** [comment]
Maybe we can take the icon from the distro-specific launcher rather than from the separate icon file...

**Comment by mintty** [comment]
... no, we can't.
Either the icon (from the WSL distro installation area) is a low-res one, and the other WSL icon is retrieved magically from somewhere else, or the mintty code to load the icon catches a smaller resolution.
However, I don't seem to reproduce this with another round icon (e.g. Thunderbird). Also, another WSL distro (openSUSE) does not exhibit the effect for me. So I guess there is something wrong the Ubuntu icon.

**Comment by mintty** [comment]
After 2 years, icon association has been tweaked, and no further observation of this has been reported, I'm closing this, assuming it's not an issue anymore.
