### ISSUE TITLE
Wrong font-size

### ISSUE THREAD

**Issue by adgoncal** [mintty/wsltty#69]
The font-size in wsltty is bigger than the font-size in Windows PowerShell. See screenshot:
![wsltty-font-size](https://user-images.githubusercontent.com/10856791/32852668-b9815970-ca06-11e7-9c3c-3520809fdd14.jpg)

**Comment by willpower232** [comment]
pt != pixels

Based on https://reeddesign.co.uk/test/points-pixels.html you want to set wsltty to 14.5pt for 20 pixels

**Comment by adgoncal** [comment]
14.5 is not a valid option, it resets to 10. Why is it set in `pt` instead of pixels anyway?

**Comment by willpower232** [comment]
Unfortunately I don't know the answer to that.

Might I suggest a combination of 14pt/19px or 15pt/21px?

**Comment by mintty** [comment]
It's not the purpose of wsltty to mimic the Windows console. It brings mintty to WSL, with the enhanced features of a real terminal.

**Comment by adgoncal** [comment]
> It's not the purpose of wsltty to mimic the Windows console. It brings mintty to WSL, with the enhanced features of a real terminal.

When I asked "Why is it set in `pt` instead of pixels anyway?" I did not mean wsltty should mimic the Windows console. I was just curious as to how the decision was made to use `pt` instead of pixels.

> It would work with the built-in font selector, option `-o FontMenu=0`
That works, thank you!

**Comment by adgoncal** [comment]
> It would work with the built-in font selector, option `-o FontMenu=0`

~That works, thank you!~
Actually, it does not. It changes the interface and removes `pt` from the selected size, but still uses `pt` to set the font. I am satisfied with `14pt` font, so will not reopen the issue.

**Comment by mintty** [comment]
> Actually, it does not.

What I meant is it would be possible to implement the option with the built-in menu. It's not possible to change the Windows font chooser to that aim. You can, however, use a negative number there or in the FontSize option, which works partly as pixel size.
