### ISSUE TITLE
wsltty not starting a login shell

### ISSUE THREAD

**Issue by ramsay-jones** [mintty/wsltty#70]
First let me say that wsltty makes WSL usable - it was awful trying to use Ubuntu in the console!
However, one minor issue that I noticed was that, when launching mintty from the menu item, the
shell does not execute either .bash_profile or .profile. At the moment, I have to remember to source
my .bash_profile by hand each time. (I prefix ~/bin to $PATH, among other things, in .bash_profile).

**Comment by mintty** [comment]
Duplicate of #56. It depends on wslbridge.
@rprichard?

**Comment by mintty** [comment]
Released 1.8.2 which should be starting a login shell.

**Comment by mintty** [comment]
... actually it doesn't; previous comment still applies

**Comment by mintty** [comment]
Released 3.1.0.
