### ISSUE TITLE
wsltty not closing cleanly

### ISSUE THREAD

**Issue by vanhecke** [mintty/wsltty#71]
When I try to close a console - either by pressing the X on the window or typing `exit` - it never exits cleanly but instead freezes up.

![image](https://user-images.githubusercontent.com/3396438/32899227-ad532c98-caea-11e7-9314-b155041135d1.png)

**Comment by mintty** [comment]
As you say "console": are you sure it's a WSLtty terminal, not a WSL-native cmd window? Can you open the Options menu, and what does About say?

**Comment by vanhecke** [comment]
Hi, yes I'm sure it's a mintty window.
I can't click on About... as opening the Options also crashes the app.

![image](https://user-images.githubusercontent.com/3396438/33598540-7a4cf366-d9a3-11e7-8959-c34c1b191f90.png)

**Comment by mintty** [comment]
Please retry with 1.8.2.
