### ISSUE TITLE
Chocolatey distribution

### ISSUE THREAD

**Issue by lucastheisen** [mintty/wsltty#77]
It would be nice to have a distribution created for [chocolatey](https://chocolatey.org/).  Would make install's simpler (especially when managing with Ansible).

**Comment by mintty** [comment]
Duplicate of #30.
See also #63 which I consider more useful.
Either way, you are invited to check out on making such a package.

**Comment by lucastheisen** [comment]
Crap, sorry...  I even commented on #30.  Looks like that one just died.  I am just now getting around to Ansible for my shiny new Windows 2016 servers and Chocolatey is supported there.  Simple enough to work around for now.  If i get a moment, I might just try to provide a pull req for choco...

**Comment by mintty** [comment]
>  If i get a moment ...

What kind of "moment"? Not nagging, I'm just asking because I planned a new release around this weekend.

**Comment by lucastheisen** [comment]
Probably not till the new year.  Sorry, cramming this week then some much needed vaca.
