### ISSUE TITLE
wsltty deleting custom shortcuts

### ISSUE THREAD

**Issue by willpower232** [mintty/wsltty#78]
I had recently duplicated the start menu shortcut for wsltty in the wsltty folder and changed it to open in a specific directory however updating to 1.8.2 seems to have deleted my shortcut. I presume this was used to tidy up the multiple shortcuts from 1.7.9 and earlier but is a little too greedy IMHO.

In wsltty's defence, I was using the shortcut name `Ubuntu Terminal % - Foldername` but it would be tidier if it only deleted shortcuts that it definitely knew. Presumably those creating custom shortcuts would be comfortable getting their hands dirty and updating their custom shortcuts if necessary.

P.S. I cannot seem to figure out how to change directory on starting wsltty as part of the shortcut, any pointers?

**Comment by mintty** [comment]
I acknowledge the upgrade approach of wsltty to be a bit simplistic, and also there is no deinstallation.
I would normally expect users to place custom shortcuts in better reach than the wsltty installation folder, but yet those should not be deleted. My ambition to make this more perfect is currently limited by the unavailability of a better installation package (like MSI or even Windows Store App).

You can configure the "Start in:" folder in the shortcut. This should normally result in wsltty (the "%" versions) to start in that folder (unless you spoil it in your WSL startup scripts, of course).

**Comment by willpower232** [comment]
Thanks for your response, putting my custom shortcut in the root of my start menu means it doesn't get deleted.

The "start in" is quite nice and means less messing around with the shortcut so thanks for that too!
