### ISSUE TITLE
Closing when last command failed

### ISSUE THREAD

**Issue by IainVM** [mintty/wsltty#79]
It seems when trying to detach from WSLTTY when the last command that was run had a non-zero exit code causes the window not to close and instead show the red bar at the top of the window telling the user the exit code. 

Steps:
- Run a non-existant command.
- Try to CTRL+D to detach from the tty.

**Comment by mintty** [comment]
[Terminating the shell isn't "detaching"]

Remove "-h err" from the command line in the Windows shortcut.

**Comment by willpower232** [comment]
I have seen the red bars randomly too but never associated it with non-existant commands, presumably `-h err` picks up all sorts of things?

The text in the red bar for this error reads `/bin/wslbridge: Exit 127.` but I remember seeing other numbers there.

**Comment by mintty** [comment]
It's the exit status of the client program, usually the shell. Shells typically propagate the exit status of the last process they called.
This is actually a remainder of a testing phase, and I think I'll remove it. Users can configure the `Hold` mode in their config file if they like.

**Comment by mintty** [comment]
Released 1.8.3.
