### ISSUE TITLE
flat-ui theme: folder name not clear

### ISSUE THREAD

**Issue by guochengrz** [mintty/wsltty#81]
Just like this (ls -l):
![2017-12-30 15_09_36-james ideapad_](https://user-images.githubusercontent.com/32217089/34452139-9510f790-ed73-11e7-8108-9ed401946de7.png)

**Comment by mintty** [comment]
This is not so much a theme problem but rather an issue of its usage.
Are both foreground and background colours set explicitly for those text parts?
If not, this is a mistake in the first place. Default foreground on specific background is always a risk.
If they are, it might be green on cyan, which is not a good idea.
