### ISSUE TITLE
Support for emojis

### ISSUE THREAD

**Issue by Nek-** [mintty/wsltty#82]
Hello :D . Thanks for this terminal I like.

My idea is to make it even better by adding a "real" support for emojis. (currently, it depends on the font used)

**Comment by mintty** [comment]
Sure it depends on the font. However, there are some special cases already (e.g. VT100 line drawing graphics) which are generated by mintty.
So I would agree that mintty _could_ display emojis independently from the font. This would further have the advantage of coloured emojis support (https://github.com/mintty/mintty/issues/671#issuecomment-339306746, https://github.com/mintty/mintty/issues/600#issuecomment-335643961).

**Comment by mintty** [comment]
However, there is some implementation effort to be expected:
1. Provide emoji resources, i.e. graphic data, either as a set of images or as a (fallback) emoji reference font.
2. Provide program access to the emoji graphics, i.e. find out how they can be loaded into an application.
3. Handle the emoji characters and actually display the graphics for them.

I am offering to take care of 3. if other people contribute 1. and 2.

**Comment by Nek-** [comment]
For 1 I suggest Noto font from Google: https://www.google.com/get/noto/help/emoji/ what do you think? :)

I've no idea about the implementation.

**Comment by mintty** [comment]
Another good source is http://www.unicode.org/emoji/charts-11.0/full-emoji-list.html
In this case, code would be needed to convert PNG data (given verbatim, not loaded from a file) into some drawable bitmap. For both scenarios (SVG or PNG), there do not seem to exist code examples.

**Comment by Nek-** [comment]
What's cool with Noto is that it's an [open font](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)

**Comment by mintty** [comment]
Being cool does not help if there is no implementation available. The Windows API does not have a function to load an SVG into memory for display. And the colour font format is not supported either.

**Comment by Nek-** [comment]
Let's rewrite mintty with Electron 😂 . More seriously. I assume there is no way to replace some chars with images.

This issue is far from being fixed.

**Comment by mintty** [comment]
Note that Noto Emoji cannot even be installed in Windows (see https://github.com/googlei18n/noto-emoji/issues/43), so it's not an option to use it as a font.

About your previous comment, sure it would be possible to replace specific characters with images (item 3 above, which I offered to take care of); the problem is how to handle the images.

Also, this is not really an issue to be "fixed" because it's not a bug...

**Comment by mintty** [comment]
Actually this was a challenge. I've uploaded a mintty source version with full Emoji support 🙂

**Comment by Nek-** [comment]
Oh! Awesome. I will test as soon as I can. Didn't you commit the changes?

**Comment by mintty** [comment]
It's a mintty feature, and commited there.
For a local wsltty build, you could `make minttyver=master`.

**Comment by mintty** [comment]
Released 1.8.4 with full emoji support.
