### ISSUE TITLE
New shortcuts from version 1.8.3 just open and close wsltty window immediately

### ISSUE THREAD

**Issue by ksze** [mintty/wsltty#83]
I just upgraded from 1.8.2 to 1.8.3 and this is what happened.

Tested:
- "Ubuntu Terminal"
- "Ubuntu Terminal %"
- "WSL Terminal"
- "WSL Terminal %"

**Comment by willpower232** [comment]
This even affects custom shortcuts created previously so it must be related to the application.

FWIW, sometimes I see what looks like the help list before the window disappears.

Reinstalling 1.8.2 restores access in the meantime

**Comment by Dod9er** [comment]
Same here. Just updated from 1.8.2 to 1.8.3 and the window closes immediately now. But one shortcut keeps open, not sure if this is really the cause:
![grafik](https://user-images.githubusercontent.com/10465878/34727179-6ec73528-f556-11e7-97cc-aa36e53d3e6f.png)

**Comment by mintty** [comment]
It's related to the wslbridge version packaged, which is from the `login-mode` branch, in an attempt to start a login shell. That doesn't seem to work from a shortcut. I guess I'll just repackage wsltty to use the latest wslbridge release.

**Comment by mintty** [comment]
Released 1.8.3.2.

**Comment by mrkschan** [comment]
1.8.3.2 works for me :)

**Comment by ksze** [comment]
The shortcuts from 1.8.3.2 don't start a login shell though. Does anybody have clear instructions for modifying the shortcuts to start a login shell?

@mintty mentioned [adding an explicit invocation of `/bin/wslbridge -t /bin/bash -l`](https://github.com/mintty/wsltty/issues/56#issuecomment-350650397), but I have no idea where to add it.

**Comment by mintty** [comment]
The way it used to work apparently doesn't work anymore...

**Comment by mintty** [comment]
Actually, it now works without referring to /bin/wslbridge explicitly:
`...\mintty.exe --WSL=... --configdir=... -~ /bin/bash -l`
