### ISSUE TITLE
wsltty (or underlying libs) changing Windows ENV varaibles

### ISSUE THREAD

**Issue by djensen47** [mintty/wsltty#84]
Here's an example of the problem I'm having. When I run VS Code (or other Windows apps or command line), something is changing one of the environment variables to `%LOCALAPPDATA%\wsltty\home\%USERNAME%`. At first I thought it was `%HOME%` but now I'm thinking it might be `%HOMEPATH%` or `%USERPROFILE%`

Example of what works:
1. Open bash using the native terminal (or ConEmu)
2. Navigate to a directory with some code
3. $ code .
Result: VS Code opens in the dir and the env variables are properly set so that it can see my ssh keys for git integration

Example of what doesn't work:
1. Open wsltty
2. Navigate to a directory with some code
3. $ code .
Result: My ssh keys cannot be found it it errors on most git commands from within VS Code

Another example of what doesn't work:
1. In Windows settings, set the %HOME% env var to something else
2. Open wsltty
3. Navigate to a directory with some code
4. $ code .
Result: Same as above

---

I tried digging around to see if I could resolve this myself but I ran into a wall. Thanks!

**Comment by djensen47** [comment]
🤔 This use case might be a red herring.

**Comment by mintty** [comment]
Seems to relate to #76 which was fixed in 1.8.2. Which version do you use?

**Comment by djensen47** [comment]
I'm on 1.8.1 and just notices that 1.8.2 is out. Thanks, I'll give this a try and see what happens.
