### ISSUE TITLE
Allow WSL distribution to dictate shell

### ISSUE THREAD

**Issue by abjugard** [mintty/wsltty#86]
Since Fall Creators update, running the wsl.exe executable instead of bash.exe will correctly select which shell to launch, based on the shell selected for the default user in the currently default WSL distro. (...finally)

I think wsltty should respect this default when it launches the WSL shell. Is this something that is being worked on?

I know there is an open issue about using Zsh as default shell, but this issue is not about being able to pick shell from wsltty, but rather for wsltty to respect what is already default for the WSL system.

**Comment by mintty** [comment]
> I know there is an open issue ...

which I closed for this more generic one; however:
the solution is the same, and it's out of scope of wsltty, see rprichard/wslbridge#17

**Comment by mackenza** [comment]
it looks like the wslbridge issue has been fixed... not in a build yet but fixed. Does wsltty need to do anything to make this work?

**Comment by Biswa96** [comment]
Just compile the latest wslbridge and mintty. Then put the binary (exe file) in wsltty folder.

**Comment by mintty** [comment]
Released 1.9.0.
