### ISSUE TITLE
Double left click should select text, regardless of window focus.

### ISSUE THREAD

**Issue by cjpeterein** [mintty/wsltty#88]
SW Versions:
Window 10
Ubuntu 16.04.3 in WSL
wsltty 1.8.3.2
no custom minttyrc anywhere

Steps to reproduce:
Open a wsltty console and any other window (ex: Windows Explorer).
Arrange them so they are both visible on screen.

In wsltty:
- Left click anywhere to gain focus.
- Double left click over text to select.  (no problem, this works)

In other window (Windows Explorer):
- Left click anywhere to gain focus.

With focus on other window, in wsltty:
- Double left click over text to select.  (problem, text is not selected)

What should happen:
Double left click should select text, regardless of window focus.

What actually happens:
Double left click does not select text when window does not already have focus.

Workaround:
Click once to get focus, then double click as usual.  This is unsatisfactory because it interferes with existing muscle memory.

Notes:
This is also a problem with the default WSL console.
~~Cygwin/mintty (without WSL) does not have this problem.~~
~~Suspect something in WSL is eating the first (focus) click?~~

**Comment by mintty** [comment]
This is a consequence of a workaround for mintty/mintty#717:
  * Prevent accidental text selection on mouse-click window activation.
The workaround is simple and a bit strict for that matter, and I was expecting someone to complain...
Actually, cygwin mintty has the same behaviour, this is not wsltty-specific.

**Comment by cjpeterein** [comment]
I see.  I had an older version of Cygwin/mintty, which explains why it did not have this problem.

I would argue against mintty/mintty#717 since that is not how other apps handle double click while not focused.  For example, in windows notepad, gvim, notepad++, Firefox and IE, double click selects the text when the windows doesn't have focus.

**Comment by mintty** [comment]
Sure. It was simply quite easy to fix that issue at the front of message handling.
So there are two options:
* Find a tricky way to handle mouse focus click suppression more selectively.
* Make it configurable.

**Comment by mintty** [comment]
Fixed by https://github.com/mintty/mintty/commit/91f9c0df2bd943c0f00a179143aff98a5d4d9f74.

**Comment by mintty** [comment]
Released 1.8.4.
