### ISSUE TITLE
Feature Request - Remove Cygwin/WSL Bridge as dependency

### ISSUE THREAD

**Issue by DarthSpock** [mintty/wsltty#89]
I was wondering if it's possible for you to simply take the necessary code out of Cygwin so you don't have to call back to Cygwin via WSLBridge. At least my impression of how this works is as I described. Logic for this for me is, if I'm installing Cygwin, why am I going to use WSL? Cygwin still can do pretty much anything WSL can with only a few minor exceptions. But considering the GUI support that Cygwin has that WSL doesn't, it kinda makes Cygwin more desirable. I would personally prefer to stick with WSL as it's more native to Windows than Cygwin but as it stands currently, running Mintty is all but impossible using with out of the box Ubuntu and OpenSuse. I did create a [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/33181663-libsixel-support-for-cmd-powershell-wsl) requesting native libsixel support but we'll see how far that goes. In the meantime, getting this improved to no longer requiring Cygwin would be a satisfactory alternative.

**Comment by mintty** [comment]
WSL is not "more native" than Cygwin - the opposite is the case. As long as WSL does not support mixed usage of POSIX and Windows APIs (which Cygwin does), it is not possible to make a "native WSL" port of mintty. You might request for that rather than for terminal features that mintty already has :)

**Comment by DarthSpock** [comment]
Which is why we have this great creation of yours called wsltty. It's my understanding that I'll need to install Cygwin in order to use this. What I'm proposing is instead of having to install Cygwin, you copy the code that is actually utilized to make this project possible (giving credits to Cygwin of course) so all the other superfluous code (and installation of the program itself) isn't required. Basically I'm requesting a one-stop shop here and getting rid of the need to perform the other steps of installing Cygwin and wslbridge. I hope this makes more sense to you. 

I consider WSL more native because it lives inside the NT kernel, Cygwin does not. However it's true that POSIX/Win API mixed usage isn't complete as of yet (but that is the entire point of the WSL project is it not? At least from a developer standpoint). Therefore from that perspective, you can't really submit an issue for "mixed POSIX/Win API usage" on WSL's issue tracker.

**Comment by mintty** [comment]
What you ask for is the core of the WSLtty project and package. Didn't you install it? 
WSLtty is a standalone package that includes the Cygwin library as needed for mintty.

**Comment by DarthSpock** [comment]
Yes, I gained further understanding of the project yesterday. The description provided made me assume that there was a number of things I had to do to install it and I didn't want to go through all the effort. I would suggest perhaps improving the description on the projects home page to explicitly state that you only need to download this package to use it. Then you can put some background info in the wiki portion explaining what's running in the backend (the Cygwin runtime libraries and wslbridge) as well as whatever miscellaneous info you'd like. Having a historical and technical background for people to read would probably be very helpful from a learning perspective. I'm closing this issue and since the issue is for something that already exists, you can delete the issue too if you want.

**Comment by mintty** [comment]
The project page has a section "Installation" which starts "Run the installer" with a link to the release area.
That should be sufficient to point people to the installer download. I could add an explicit title "Download" if that makes it better (?).
About technical background, admittedly, the last line of the project page
"For interacting with WSL, it uses wslbridge."
may be a bit sparse. Maybe I'll find some time for a few more sentences.
