### ISSUE TITLE
configuration files?

### ISSUE THREAD

**Issue by musm** [mintty/wsltty#9]
So  it looks like the .minttyrc file has to be in
`%APPDATA%\wsltty\home\USER`

whereas the themes etc. must be in the
`%APPDATA%\Local\lxss\home\USER\.config\mintty`
folder?

A little more description in the README would be helpful here

**Comment by mintty** [comment]
No, in general, mintty scans 4 places, with the following precedence:

* `~/.minttyrc`
* `~/.config/mintty/config`
* `$APPDATA/mintty/config`
* `/etc/minttyrc`

In the case of `wsltty`, the mintty root is `%LOCALAPPDATA%\wsltty`, also note that in general `%LOCALAPPDATA%` is not the same as `%APPDATA%\Local`. This results in the following places:
* `%LOCALAPPDATA%\wsltty\home\%USERNAME%\.minttyrc`
* `%LOCALAPPDATA%\wsltty\home\%USERNAME%\.config\mintty\config`
* `%APPDATA%\mintty\config`
* `%LOCALAPPDATA%\wsltty\etc\minttyrc`

**Comment by musm** [comment]
thank you!

**Comment by mintty** [comment]
Released 0.7.0.

**Comment by papesch** [comment]
Thanks @mintty for the above comment. Additionally, on Windows 10 Enterprise the config file wound up in my Roaming profile:
* `C:\Users\%USERNAME%\AppData\Roaming\wsltty\config`

**Comment by mintty** [comment]
> * `C:\Users\%USERNAME%\AppData\Roaming\wsltty\config`

which is `%APPDATA%\mintty\config` as listed above; the other locations (in `%LOCALAPPDATA%`) are not really useful in wsltty.

**Comment by mintty** [comment]
> > C:\Users\%USERNAME%\AppData\Roaming\wsltty\config

> which is %APPDATA%\mintty\config as listed above; the other locations (in %LOCALAPPDATA%) are not really useful in wsltty.

No, sorry, it's `%APPDATA%\wsltty\config` of course, and that's added to the mintty default configuration sequence by an explicit `--configdir` parameter in the wsltty invocation shortcuts.
