### ISSUE TITLE
Emojis display

### ISSUE THREAD

**Issue by grolongo** [mintty/wsltty#93]
Hi, is it possible to show me a screenshot of how emojis should be displayed with the last version?
Here is how they are shown after I updated to 1.8.4:

![emojiwsltty](https://user-images.githubusercontent.com/34292770/36244304-008c7a54-1226-11e8-840c-2d8b18278c3d.jpg)

For info they are displayed the same as with previous versions so I don't know if I'm missing something in my config file (couldn't find anything in the readme though).

**Comment by mintty** [comment]
These are only the emoji symbols from the font.
For graphic emoji display, see the mintty home page for screenshots, and the mintty wiki for setup instructions. Both are linked from the last section of the wsltty project page; I guess I should add those links in a more visible place.

**Comment by grolongo** [comment]
I indeed missed quiet a few steps to have this working. Now all emojis are showing as expected, even in (neo)vim (useful for visual grepping linter errors and some info in the statusbar for my case).

For reference this is what I did (more infos in the mintty wiki & manual):
1. Downloaded https://github.com/iamcal/emoji-data/archive/v4.0.3.zip
2. Extracted folder `img-apple-64` into `%APPDATA%\wsltty\emojis`
3. Renamed folder `img-apple-64` as `apple`
4. Edited `%APPDATA%\wsltty\config` by adding two lines: `Charwidth=unicode` & `Emojis=apple` 

![onpoint](https://user-images.githubusercontent.com/34292770/36292367-a653ba28-12d1-11e8-925b-98233617a03a.jpg)

For you @mintty, do you think we could avoid downloading a set of emojis by using the ones already available in Windows (couldn't find where they were located in the system though)?

**Comment by mintty** [comment]
> For you @mintty, do you think we could avoid downloading a set of emojis by using the ones already available in Windows (couldn't find where they were located in the system though)?

That's the point. If you find them, sure...

**Comment by grolongo** [comment]
One different way would be to use Segoe UI Emoji font as fallback like in Visual Studio Code.
Terminal and iTerm2 on macOS use this method too (with Apple Color Emoji font).

Not sure if that could work with mintty as it's a different approach than yours.

**Comment by mintty** [comment]
No, mintty needs access to the individual emoji graphics. If you know how to pulll them out of the font, that might help. But the Segoe font does not work with the normal Windows API, it's not even installable here.

**Comment by mintty** [comment]
> it's not even installable here.

No, that was the NotoColorEmoji font. Anyway, access to an installed font with coloured glyphs is not possible in the API that mintty uses.

**Comment by grolongo** [comment]
OK so I've found some ruby extractor script (https://github.com/tmm1/emoji-extractor) for the Apple Color Emoji font and tried to change the code to make it work for Segoe UI Emoji font under WSL but without success.

I'll try to see if there is anything else that could make it work in my free time.

Since my original question has been resolved you can close this issue or let me do it later.

**Comment by mintty** [comment]
With seguiemj.ttf, this script just says "Could not find the font file. Exiting."
With NotoColorEmoji.ttf, it says that too, but then does in fact extract png files.
However, the result is quite useless as the files are numbered sequentially (1.png ... 2419.png), so they cannot be mapped to the Unicode emojis. It seems this script is crap.

**Comment by mintty** [comment]
Closing this generic issue.
To propose other ways to access emoji resources (Windows built-in, font...), please open a fresh issue (preferably with technical hints).
