### ISSUE TITLE
default shell argument

### ISSUE THREAD

**Issue by Po-wei** [mintty/wsltty#95]
```
To invoke your favourite shell or launch the shell in login mode, you may append a 
shell pathname and an optional -l parameter to the mintty invocation

%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" /bin/bash -l
```

what is the different between -l and without -l argument?
Aren't they both login shell ?

**Comment by mintty** [comment]
No, only `-l` enforces a login shell (see `man bash`).

**Comment by evaryont** [comment]
Is there a way for wsltty to launch the correct login shell without having to specify it in the `.bat` file? That is, I expected that when I ran `chsh` in Ubuntu, the next launch of WSLtty to launch not bash but whatever the default shell for my user is.

When launching a session via cmd.exe directly, i.e. running 'ubuntu', it does behave like this.

**Comment by mintty** [comment]
The next release of wsltty will integrate the latest wslbridge version.

**Comment by Biswa96** [comment]
This is solved.
