### ISSUE TITLE
Screen Crash

### ISSUE THREAD

**Issue by hortune** [mintty/wsltty#98]
![image](https://user-images.githubusercontent.com/13596054/38652726-d050dbce-3e39-11e8-972f-cc54ce3c2119.png)

If the line is too long, the right one thing would be on the left.

**Comment by mintty** [comment]
1. This is not a crash. Please use an appropriate issue title.
2. There is not enough information to assess the situation. What's your screen size (`stty size`)? Which programs were run?
3. Assuming, your screen size may be less than 80 columns, it's quite normal that some programs don't "fit" in it. Long lines are wrapped around, that is absolutely normal terminal behaviour.
Closing.
